達成方法集 H80の翻訳
waic/wcag21 pull request #1021
Opened 2021-07-07 07:19 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-07 07:22 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0の日本語訳で、訳注がありましたので、流用しました。

一点、2.0からの差分として、「Example 3: Newspaper Web site」の中に下記の文面が 2.1 で追加されていたので、日本語訳を行っています。

> A script is used to find each element with a class of card-link and append an additional paragraph with a "Read more" link at the end of the div with the class .card-link that goes to the same location as the link in the heading.

2021-07-17 06:33 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-07-17 06:33 UTC, momdo commented on techniques/html/H80.html
> +            <p>この達成方法の目的は、リンクとその直前にある見出しの文脈から、リンクの目的を特定することである。直前にある見出しは、リンクテキストだけでは不明瞭なリンクに文脈を提供する。それによって、利用者がそのリンクと、そのウェブページ内にある他のリンクとを区別できるようになり、そのリンク先へ移動するかどうかを判断しやすくなる。
達成基準がコンテキストとしてますし、コンテキストにあわせておきますか…
```suggestion
            <p>この達成方法の目的は、リンクとその直前にある見出しのコンテキストから、リンクの目的を特定することである。直前にある見出しは、リンクテキストだけでは不明瞭なリンクにコンテキストを提供する。それによって、利用者がそのリンクと、そのウェブページ内にある他のリンクとを区別できるようになり、そのリンク先へ移動するかどうかを判断しやすくなる。
```

2021-07-17 06:33 UTC, momdo commented on techniques/html/H80.html
> +                  <p>可能なかぎり、文脈による補足を必要とせずにリンクの目的が特定できるリンクテキストを提供すべきである。
```suggestion
                  <p>可能なかぎり、コンテキストによる補足を必要とせずにリンクの目的が特定できるリンクテキストを提供すべきである。
```

2021-07-17 06:33 UTC, momdo commented on techniques/html/H80.html
> +&lt;/div&gt;</pre><p>スクリプトを用いて <code>class="card-link"</code> の各要素を探し出し、<code>class="card-link"</code> を持つ div 要素の末尾に、"Read more" リンクを持つ段落を追加して、見出し内のリンクと同じ所に行くようにしている。
よいと思います。

2021-07-19 06:36 UTC, caztcha commented
@momdo レビューありがとうございます。
2点、修正提案をいただきましたが、いずれも確認のうえ、コミットしました。
よろしければ、マージいただけますと幸いです。

2021-07-19 07:25 UTC, momdo approved these changes

2021-07-19 07:26 UTC, merged

2021-07-19 07:26 UTC, momdo commented
@caztcha 
確認ありがとうございます。マージしました。