達成方法集 H79の翻訳
waic/wcag21 pull request #1022
Opened 2021-07-07 07:42 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-07 07:44 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-17 06:53 UTC, momdo requested changes
@caztcha レビューしましたのでご確認ください。

2021-07-17 06:53 UTC, momdo commented on techniques/html/H79.html
> +            <p>この達成方法の目的は、リンクとそれを含んでいるデータテーブルの文脈から、リンクの目的を特定することである。文脈とは、そのリンクを含んでいるテーブルセルと、そのセルに関連付けられたテーブルの見出しセルとの関係を指している。データテーブルの文脈によって、リンクを含んでいるセルが、先祖要素であるブロックレベル要素の中で最もそのリンクに近い場合、リンクテキストだけでは不明瞭
宛先→コンテキストに変更しつつ、大幅に手を加えてみました。
おかしなところがないところがないか確認いただければと。
```suggestion
            <p>この達成方法の目的は、リンクとそれを含んでいるデータテーブルのコンテキストから、リンクの目的を特定することである。このコンテキストは、そのリンクを含んでいるテーブルセルと、そのセルに関連付けられたテーブルの見出しセルとの関係を指している。そうでなければデータテーブルのコンテキストは、テーブルセルが最も近いブロックレベルの先祖要素で囲んでいる場合、不明瞭なリンクの目的を提供する。それによって、利用者がこのリンクと他の宛先につながるウェブページの他のリンクを区別できるようになり、そのリンクをたどるかどうかを判断するのに役立つ。単に目的地の URI を示すだけでは、障害のある利用者、特に認知障害のある利用者にとってはリンク先の説明として不十分であることに注意する。
```

2021-07-19 07:29 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、原文と照らして確認しました。問題ないと思いますので、commit change しました。よろしければマージいただけますと幸いです。

2021-07-20 00:07 UTC, momdo approved these changes

2021-07-20 00:08 UTC, merged

2021-07-20 00:08 UTC, momdo commented
@caztcha 
確認ありがとうございます。問題ないのでマージしました。