達成方法集 H78の翻訳
waic/wcag21 pull request #1023
Opened 2021-07-08 05:37 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-08 05:37 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-18 01:59 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。
解説に関しては、もしかしたらH79と訳文をあわせたほうがよいのかもしれません。

2021-07-18 01:59 UTC, momdo commented on techniques/html/H78.html
> +            <p>この達成方法の目的は、リンクとそれを含んでいるパラグラフの文脈から、リンクの目的を特定することである。リンクを含んでいるパラグラフが、先祖要素であるブロックレベル要素の中で最もそのリンクに近い場合、リンクテキストだけでは不明瞭なリンクに文脈を与えることになる。その説明によって、利用者がそのリンクと、そのウェブページ内にある他のリンクとを区別できるようになり、そのリン
見出しと達成基準にあわせます
```suggestion
            <p>この達成方法の目的は、リンクとそれを含んでいる段落のコンテキストから、リンクの目的を特定することである。リンクを含んでいる段落が、先祖要素であるブロックレベル要素の中で最もそのリンクに近い場合、リンクテキストだけでは不明瞭なリンクにコンテキストを与えることになる。その説明によって、利用者がそのリンクと、そのウェブページ内にある他のリンクとを区別できるようになり、そのリンク先へ移動するかどうかを判断しやすくなる。一般的に、リンクテキストとして単に目的地の URI を示すだけでは、リンク先の説明として不十分であることに注意すべきである。
```

2021-07-20 05:34 UTC, caztcha commented
@momdo レビューありがとうございました。
一点、「解説」の訳文の表現をH79と合わせてみました。
よろしければ、マージいただけますと幸いです。

2021-07-20 23:02 UTC, momdo approved these changes

2021-07-20 23:02 UTC, merged

2021-07-20 23:03 UTC, momdo commented
@caztcha 
ありがとうございます。確認してマージしました。