達成方法集 H74の翻訳
waic/wcag21 pull request #1027
Opened 2021-07-08 07:02 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-08 07:04 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。

2021-07-18 02:17 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-07-18 02:17 UTC, momdo commented on techniques/html/H74.html
> +            <p> HTML 及び XHTML。</p>
```suggestion
            <p>HTML 及び XHTML</p>
```

2021-07-18 02:17 UTC, momdo commented on techniques/html/H74.html
> +            <p>この達成方法の目的は、支援技術がコンテンツを解析するときに生じる (ことで知られている) キーエラーを回避することである。このエラーは、コンテンツが、仕様に準じて用いられていない開始タグや終了タグを含むときに起こる。HTML あるいは XHTML のメカニズムをウェブコンテンツ技術やウェブコンテンツ技術のバージョンを特定するために用いたり、このようなタイプのエラーが
さすがにキーでは通じないと思うので
```suggestion
            <p>この達成方法の目的は、支援技術がコンテンツを解析するときに生じる (ことで知られている) 基本的なエラーを回避することである。このエラーは、コンテンツが、仕様に準じて用いられていない開始タグや終了タグを含むときに起こる。HTML あるいは XHTML のメカニズムをウェブコンテンツ技術やウェブコンテンツ技術のバージョンを特定するために用いたり、このようなタイプのエラーがないようにウェブページを制作したりすることで回避できる。バリデーターにはコンテンツ開発者が利用可能なものがいくつかあり、バリデーターのレポートではこのようなタイプのエラーが指摘される。この達成方法は、間違って形成された開始タグと終了タグに関連するエラーのみを対象としている。文書型宣言は、この検証では必ずしも必要ではないが、文書型宣言をしておくことでバリデーターを活用しやすくなる。
```

2021-07-18 02:17 UTC, momdo commented on techniques/html/H74.html
> +               <p>HTML ページが文書型宣言を含んでいる (!DOCTYPE として示されることが多い)。コンテンツ開発者はオフラインあるいはオンラインでバリデーターを利用できる (下記の参考リソース参照)。バリデーターでは、すべての id 属性の値が一意的で、かつ開始タグと終了タグが仕様に準じて用いられていることをチェックできる。
```suggestion
               <p>HTML ページが文書型宣言を含んでいる (!DOCTYPE として示されることが多い)。コンテンツ開発者はオフライン又はオンラインでバリデーターを利用できる (下記の参考リソース参照)。バリデーターでは、すべての id 属性の値が一意的で、かつ開始タグと終了タグが仕様に準じて用いられていることをチェックできる。
```

2021-07-18 02:17 UTC, momdo commented on techniques/html/H74.html
> +               <p>XHTML その他の XML ベースの文書同様に、XHTML 文書は、文書型定義 (DTD) や他のタイプの XML スキーマを参照する。コンテンツ開発者はオンラインあるいはオフラインでバリデーターを利用でき (エディターに組み込まれているバリデーションツールを含む)、開始タグや終了タグが仕様に準じて用いられていることをチェックする。
```suggestion
               <p>XHTML その他の XML ベースの文書同様に、XHTML 文書は、文書型定義 (DTD) や他のタイプの XML スキーマを参照する。コンテンツ開発者はオンライン又はオフラインでバリデーターを利用でき (エディターに組み込まれているバリデーションツールを含む)、開始タグや終了タグが仕様に準じて用いられていることをチェックする。
```

2021-07-18 02:17 UTC, momdo commented on techniques/html/H74.html
> +               <p>ウェブサイトが静的なページではなく、HTML あるいは XHTML のページが動的に生成されるときは、コンテンツ開発者は <a href="http://xhtmlunit.sourceforge.net/">XHTMLUnit</a>や <a href="http://xmltestsuite.sourceforge.net/">XML Test Suite
```suggestion
               <p>ウェブサイトが静的なページではなく、HTML 又は XHTML のページが動的に生成されるときは、コンテンツ開発者は <a href="http://xhtmlunit.sourceforge.net/">XHTMLUnit</a>、 <a href="http://xmltestsuite.sourceforge.net/">XML Test Suite</a> 又は類似のフレームワークを用いて生成される XHTML コードのチェックを行うことができる。
```

2021-07-20 04:53 UTC, caztcha commented
@momdo レビューありがとうございました。修正提案につきまして、原文と照らし合わせて確認のうえ、コミットしました。
よろしければ、マージいただけますと幸いです。

2021-07-20 23:03 UTC, momdo approved these changes

2021-07-20 23:03 UTC, merged

2021-07-20 23:03 UTC, momdo commented
@caztcha 
ありがとうございます。確認してマージしました。