達成方法集 H69の翻訳
waic/wcag21 pull request #1030
Opened 2021-07-12 06:12 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-12 06:13 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-19 03:13 UTC, momdo approved these changes
@caztcha 
作業ありがとうございます。編集的なコメントをしていますのでご確認ください。

2021-07-19 03:13 UTC, momdo commented on techniques/html/H69.html
> +            <p>HTML 及び XHTML。</p>
```suggestion
            <p>HTML 及び XHTML</p>
```

2021-07-19 03:13 UTC, momdo commented on techniques/html/H69.html
> +            <p>見出しは論理的な階層を伝えるためにデザインされている。見出しの階層の中のレベルを飛ばすと、文書構造がきちんと検討されなかったのではないか、又は一部の見出しが意味ではなく視覚的な表現を得るために選択されたのではないか、といった印象を与えてしまうかもしれない。著者には見出しを階層的に入れ子にすることが推奨される。見出しが階層的である場合、もっとも重要な情報には最も高い論
```suggestion
            <p>見出しは論理的な階層を伝えるためにデザインされている。見出しの階層の中のレベルを飛ばすと、文書構造がきちんと検討されなかったのではないか、又は一部の見出しが意味ではなく視覚的な表現を得るために選択されたのではないか、といった印象を与えてしまうかもしれない。コンテンツ制作者には見出しを階層的に入れ子にすることが推奨される。見出しが階層的である場合、もっとも重要な情報には最も高い論理レベルが与えられ、下位のセクションにはその後の論理レベルが与えられる (すなわち、h2 は h1 の下位セクションである)。このような種類の見出しを与えることは、コンテンツの全体的な構成を、利用者がより簡単に理解することに役立つ。
```

2021-07-19 03:15 UTC, momdo requested changes
Approveになってたので変更しておきます…

2021-08-05 05:16 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。
よろしければマージいただけますと幸いです。

2021-08-05 12:07 UTC, momdo approved these changes

2021-08-05 12:07 UTC, merged

2021-08-05 12:07 UTC, momdo commented
@caztcha 
ありがとうございます。マージしました。