達成方法集 H65の翻訳
waic/wcag21 pull request #1032
Opened 2021-07-12 11:52 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-12 12:05 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
いくつか、2.0 からの変更点がありましたので、翻訳しました。

> ## Description
> 
> The objective of this technique is to use the title attribute to **provide an accessible name for** form controls when the visual design **does not include** text on the screen that can be **associated with the control as** a label. User agents, including assistive technology, can speak the title attribute.

> ## Example 4: A data table of form controls
> 
> A data table of form controls needs to associate each control with the column and row headers for that cell. Without a title (or off-screen **label**) it is difficult for non-visual users to pause and interrogate for corresponding row **or** column header values using their assistive technology while tabbing through the form.
> 
> For example, a survey form has four column headers in first row: Question, Agree, Undecided, Disagree. Each following row contains a question and a radio button in each cell corresponding to answer choice in the three columns. The title attribute for every radio button **contains the information necessary to identify the control**.

> ## Tests
> ### Procedure
> 
> **For all form controls that are not associated with a label element**:
> 1. (略)
> 2. Check that the purpose of the form control is clear to users who can see the control.
> 3. Check that the title attribute identifies the purpose of the control **and that it matches the apparent visual purpose**.

---

それから、「参考リソース」のところに 2.0 では下記の訳注がありましたが、参考リソースのリスト項目に 2.1 では「HTML5 The title attribute」が追加されたので、ふたつめのセンテンス（「上記は〜」）は削除しました。

> HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記は、HTML 5.2§3.2.5.1. The title attribute を代わりに参照できる。

2021-07-22 01:14 UTC, momdo requested changes
@caztcha 
ありがとうございます。レビューしましたので確認ください。

2021-07-22 01:14 UTC, momdo commented on techniques/html/H65.html
> +                  <p><a href="https://www.w3.org/TR/html52/dom.html#the-title-attribute">HTML 5.2§3.2.5.1. The title attribute</a> の Warning で述べられているように、多くのユーザエージェントではアクセシブルな形でこの属性を公開しないので、<code>titl
```suggestion
                  <p><a href="https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute">HTML Standard§3.2.6.1 The title attribute</a> の Note で述べられているように、多くのユーザエージェントではアクセシブルな形でこの属性を公開しないので、<code>title</code> 属性に依存することを勧めていない。
```

2021-07-22 01:14 UTC, momdo commented on techniques/html/H65.html
> +               <p>フォームコントロールのデータテーブルでは、各コントロールとそのセルの列及び行ヘッダーを関連付ける必要がある。 title (又はオフスクリーンの label) がないと、視覚を持たない利用者にとっては、フォームをタブで移動しながら支援技術を用いて対応する行あるいは列のヘッダー値を一時停止して調べることが困難である。
off-screenをそのまま訳して画面外とするのは厳しいので

```suggestion
               <p>フォームコントロールのデータテーブルでは、各コントロールとそのセルの列及び行ヘッダーを関連付ける必要がある。 title (又は画面に現れない label) がないと、視覚を持たない利用者にとっては、フォームをタブで移動しながら支援技術を用いて対応する行又は列のヘッダー値を一時停止して調べることが困難である。
```

2021-07-25 05:49 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた修正提案を確認のうえ、コミットしました。よろしければマージいただけますと幸いです。

2021-07-27 23:54 UTC, momdo approved these changes

2021-07-27 23:54 UTC, merged

2021-07-27 23:54 UTC, momdo commented
@caztcha 
修正ありがとうございます。確認してマージしました。