達成方法集 H63の翻訳
waic/wcag21 pull request #1037
Opened 2021-07-15 07:07 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-15 07:08 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-20 23:17 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。編集上のコメントをしてますので確認ください。

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +            <p>HTML 及び XHTML。</p>
```suggestion
            <p>HTML 及び XHTML</p>
```

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +            <p>この達成方法の目的は、<code class="att">scope</code> 属性を利用して見出しセルとデータセルを関連付けることである。 <code class="att">scope</code> 属性を利用するのは、見出しとして利用するあらゆるセルが及ぶ範囲を明確にするためである。範囲とは、そのセルが行、列、行グループ、列グループのどの見出しであるかを特
```suggestion
            <p>この達成方法の目的は、<code class="att">scope</code> 属性を利用して見出しセルとデータセルを関連付けることである。 <code class="att">scope</code> 属性を利用するのは、見出しとして利用するあらゆるセルが及ぶ範囲を明確にするためである。範囲とは、そのセルが行、列、行グループ、列グループのどの見出しであるかを特定するものである。row、col、rowgroup、colgroup という値によって範囲を特定することになる。</p>
```

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +            <p>事例 1 のように、見出しが 1 行目や 1 列目にない単純なテーブルに対してこの達成方法が利用できる。今日のスクリーンリーダーのサポートを考えると、単純なテーブルについて次の二つの状況が当てはまる場合に、この達成方法の利用が示唆される:            </p>
```suggestion
            <p>事例 1 のように、見出しが 1 行目や 1 列目にない単純なテーブルに対してこの達成方法が利用できる。今日のスクリーンリーダーのサポートを考えると、単純なテーブルについて次の二つの状況が当てはまる場合に、この達成方法の利用が示唆される:</p>
```

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +                  </p>
```suggestion
                  </p>
```

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +                  </p>
```suggestion
                  </p>
```

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +                  <p>複雑なテーブルについては、For complex tables use ids and headers as in <a href="#H43">H43: データテーブルのデータセルを見出しセルと関連付けるために、id 属性及び headers 属性を使用する</a>の通り、id 属性と headers 属性を利用する。
英語が残ったままです。

2021-07-20 23:17 UTC, momdo commented on techniques/html/H63.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記はそれぞれ、<a href="https://www.w3.org/TR/html52/tabular-data.html#the-th-element">HTML 5.2§4.9.10. The th element</a> を代わり
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記はそれぞれ、<a href="https://html.spec.whatwg.org/multipage/tables.html#the-th-element">HTML Standard§4.9.10 The th element</a> を代わりに参照できる。
```

2021-07-21 08:24 UTC, caztcha commented on techniques/html/H63.html
> +                  <p>複雑なテーブルについては、For complex tables use ids and headers as in <a href="#H43">H43: データテーブルのデータセルを見出しセルと関連付けるために、id 属性及び headers 属性を使用する</a>の通り、id 属性と headers 属性を利用する。
```suggestion
                  <p>複雑なテーブルについては、<a href="H43">H43: データテーブルのデータセルを見出しセルと関連付けるために、id 属性及び headers 属性を使用する</a>の通り、id 属性と headers 属性を利用する。
```

2021-07-21 08:26 UTC, caztcha commented
@momdo レビューありがとうございます。一箇所、英語が残ったままのところがあり、失礼いたしました。
訳文を修正して、またリンク先URLも修正しています。お手数ですが、ご確認いただけますと幸いです。

2021-07-22 00:49 UTC, momdo approved these changes

2021-07-22 00:49 UTC, merged

2021-07-22 00:49 UTC, momdo commented
@caztcha 
ありがとうございます。問題なさそうなのでマージしました。