達成方法集 H62の翻訳
waic/wcag21 pull request #1038
Opened 2021-07-15 07:39 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-15 07:39 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-20 23:25 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。レビューしましたのでご確認ください。

2021-07-20 23:25 UTC, momdo commented on techniques/html/H62.html
> +            <p>XHTML 1.1 及び HTML5。</p>
```suggestion
            <p>XHTML 1.1 及び HTML5</p>
```

2021-07-20 23:25 UTC, momdo commented on techniques/html/H62.html
> +            <p>「Ruby Annotation」は XHTML 1.1 又は HTML5 のモジュールのひとつとして定義されている。コンテンツ制作者は「Ruby Annotation」によって、読み方や、場合によっては定義を提供すべく、「ベーステキスト」に注釈を加えることができる。日本語など東アジア言語のテキストでは、ルビが当たり前に利用される。
分の順序が入れ替わっているので原文にあわせました
```suggestion
            <p>コンテンツ制作者はRuby Annotationによって、読み方や、場合によっては定義を提供すべく、「ベーステキスト」に注釈を加えることができる。日本語など東アジア言語のテキストでは、ルビが当たり前に利用される。Ruby Annotationは XHTML 1.1 又は HTML5 のモジュールのひとつとして定義されている。
```

2021-07-20 23:25 UTC, momdo commented on techniques/html/H62.html
> +               <p>次は、日本語の事例である。日本語では漢字の読み (ふりがな) を提供するのにルビが用いられる。ルビのカッコを指定する <code class="el">rp</code> 要素は、読み方を提供する <code class="el">rt</code> 要素のテキスト、つまりルビをサポートしていないユーザエージェントが利用し、ベーステキストの直後にカッコ付きで読
```suggestion
               <p>次は、日本語の事例である。日本語では漢字の読み (ふりがな) を提供するのにルビが用いられる。ルビのカッコを指定する <code class="el">rp</code> 要素は、読み方を提供する <code class="el">rt</code> 要素のテキスト、つまりルビをサポートしていないユーザエージェントが利用し、ベーステキストの直後にカッコ付きで読み方をレンダリングする (ルビをサポートしているユーザエージェントでは、カッコは表示されない) 。
```

2021-07-20 23:25 UTC, momdo commented on techniques/html/H62.html
> +               <p> この事例では、Web Content Accessibility Guidelines という複数の単語の 1 文字目をとって作った頭文字語 (頭字語) の読み方を提供するために、ルビを用いている。WCAG という文字がルビベース (<code class="el">rb</code> 要素) であり、読み方をルビテキスト (<code class="el"
```suggestion
               <p> この事例では、Web Content Accessibility Guidelines という複数の単語の 1 文字目をとって作った頭文字語 (頭字語) の読み方を提供するために、ルビを用いている。WCAG という文字がルビベース (<code class="el">rb</code> 要素) であり、読み方をルビテキスト (<code class="el">rt</code> 要素) として示す。ルビのカッコを指定する <code class="el">rp</code> 要素は、ルビをサポートしていないユーザエージェントに対して、<code class="el">rt</code> 要素で囲まれたテキストが読み方を提供していることを示すために用いられる。ベーステキストの直後にカッコ付きで読み方をレンダリングする (ルビをサポートしているユーザエージェントでは、カッコは表示されない)。
```

2021-07-21 08:18 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案について、ひととおり確認し、コミットしました。
よろしければ、マージいただけますと幸いです。

2021-07-22 00:51 UTC, momdo approved these changes

2021-07-22 00:51 UTC, merged

2021-07-22 00:52 UTC, momdo commented
@caztcha 
確認してマージしました。