達成方法集 H58の翻訳
waic/wcag21 pull request #1041
Opened 2021-07-16 05:18 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-16 05:24 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、若干変更があり、翻訳をしました。
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FNOTE-WCAG20-TECHS-20161007%2FH58.html&doc2=https%3A%2F%2Fwaic.github.io%2Fwcag21%2Ftechniques%2Fhtml%2FH58

2021-07-22 01:43 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-07-22 01:43 UTC, momdo commented on techniques/html/H58.html
> +            <p>この達成方法の目的は、<code class="att">lang</code> 属性を用いることで、ページ上で用いられている自然言語の変化を明示することである。
```suggestion
            <p>この達成方法の目的は、<code class="att">lang</code> 属性を用いることで、ページ上の言語の変更を明示することである。
```

2021-07-22 01:43 UTC, momdo commented on techniques/html/H58.html
> +            <p>lang 属性に指定できる値については、以下に示す参考リソースに示されている。言語タグは、言語を表すプライマリーコードと、その言語が使用される地域や記述に用いる文字コードなどを表すサブコードから成っている。サブコードの指定は任意で、指定する場合にはプライマリーコードに続けてハイフンを記述し、その後に記述する。たとえば、プライマリーコード「en」は英語を示し、「en-
（あまり嬉しくないですが、）一応原文に沿った形で訳出しました。
```suggestion
            <p>lang 属性に指定できる値については、以下に示す参考リソースに示されている。言語タグは、言語を表すプライマリーコードと、その言語の変形を表すオプションの (ハイフン文字で区切られる) サブコードを使用する。たとえば、英語はプライマリーコード「en」はで示される。イギリス英語とアメリカ英語はそれぞれ「en-GB」と「en-US」を用いて区別できる。この達成方法において、プライマリーコードの使用は重要である。サブコードの使用は任意だが、状況によっては有用なものになり得る。            </p>
```

2021-07-25 05:55 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた修正提案、原文と照らし合わせて確認の上、コミットしました。よろしければ、マージいただけますと幸いです。

2021-07-27 23:55 UTC, momdo approved these changes

2021-07-27 23:55 UTC, merged

2021-07-27 23:55 UTC, momdo commented
@caztcha 
修正ありがとうございます。確認してマージしました。