達成方法集 CSS7の翻訳
waic/wcag21 pull request #1047
Opened 2021-07-20 08:49 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-20 08:52 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
一部、差分があったので訳文を調整しました。
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FNOTE-WCAG20-TECHS-20161007%2FC7.html&doc2=https%3A%2F%2Fwaic.github.io%2Fwcag21%2Ftechniques%2Fcss%2FC7

2021-07-23 06:03 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。意訳の箇所が多かったため、全般的に訳を見直しています。おかしな箇所がないかを確認いただければと思います。

2021-07-23 06:03 UTC, momdo commented on techniques/css/C7.html
> +                  <li>説明を付加するテキストを提供する要素のスタイルが、1 ピクセル四方の中に収められ、かつ「overflow: hidden;」の状態で表示領域の外側に配置されるように定義されていることを確認する。
```suggestion
                  <li>要素の表示を 1 ピクセルに制限し、かつテキストを非表示にするその要素が定義されていることを確認する。
```

2021-07-23 06:03 UTC, momdo commented on techniques/css/C7.html
> +                  <li>そのスタイルが定義されている要素が <code>a</code> 要素の中に含まれていることを確認する。</li>
```suggestion
                  <li>そのクラスの要素が <code>a</code> 要素のコンテンツに含まれていることを確認する。</li>
```

2021-07-23 06:03 UTC, momdo commented on techniques/css/C7.html
> +                  <li><code>a</code> 要素の中のコンテンツを組み合わせると、何へのリンクであるかの説明になっていることを確認する。</li>
```suggestion
                  <li><code>a</code> 要素の組み合わせたコンテンツがリンクの目的を説明していることを確認する。</li>
```

2021-07-25 06:13 UTC, caztcha commented on techniques/css/C7.html
> +                  <p>リンクテキストを非表示にするこの達成方法は、スクリーンリーダーの利用者や企業のウェブコンテンツ制作者の一部によって支持されている。一部のウェブサイトにおいては効果があることも立証されている。しかし、結果的に説明が冗長になることがある上に、熟練したスクリーンリーダーの利用者にはその冗長な説明の読み上げを制御することを要求することもありうるため、スクリーンリ
```suggestion
                  <p>リンクテキストを非表示にするこの達成方法は、スクリーンリーダーの利用者や企業のウェブコンテンツ制作者の一部によって支持されている。一部のウェブサイトにおいては効果があることも立証されている。しかし、結果的に説明が過度に冗長になり、熟練したスクリーンリーダーの利用者にはその冗長性を制御する能力を制約する可能性もあるため、スクリーンリーダーの利用者やアクセシビリティの専門家の中には、一般的な達成方法としてこれを推奨していない人もいる。AG ワーキンググループとしては、非表示のテキスト領域で繰り返されるコンテンツがないウェブページに対して、この達成方法は有用であると考えている。
```

2021-07-25 06:22 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた修正提案を、ひととおり確認しました。
一点、
https://github.com/waic/wcag21/pull/1047#discussion_r675319792
のみ、私の方で修正しました。

2021-07-31 03:27 UTC, momdo approved these changes

2021-07-31 03:28 UTC, momdo commented
@caztcha 
内容確認ありがとうございます。修正で問題ありませんのでマージします。

2021-07-31 03:28 UTC, merged