達成方法集 CSS8の翻訳
waic/wcag21 pull request #1050
Opened 2021-07-25 06:52 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-25 06:54 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
一点、2.0 の訳注を流用するにあたって、修正をしました。

> 訳注: 「CSS 2: Letter and word spacing」は、CSS Text Module Level 3§**8**. Spacing で再定義されている。
↓
> 訳注: 「CSS 2: Letter and word spacing」は、CSS Text Module Level 3§**7**. Spacing で再定義されている。

2021-07-31 03:41 UTC, momdo requested changes
@caztcha 
ありがとうございます。1点翻訳を調整しましたのでご確認ください。

2021-07-31 03:41 UTC, momdo commented on techniques/css/C8.html
> +            <p>この達成方法の目的は、意味の伝わるテキストの流れを維持しながら、スタイルシートによって表示上の文字間隔を調整する方法を示すことである。 文字間隔の量を調整するには、CSS の letter-spacing プロパティを使用する。 単語の途中に空白文字を入れると意味や発音のされ方が変わってしまうため、間隔の調整はこの方法で行うことが推奨されている。
text sequencingが「テキストの流れ」は微妙なので…
```suggestion
            <p>この達成方法の目的は、意味のあるテキストのシーケンスを維持しながら、スタイルシートによって表示上の文字間隔を調整する方法を示すことである。文字間隔の量を調整するには、CSS の letter-spacing プロパティを使用する。単語の途中に空白文字を入れると意味や発音のされ方が変わってしまうため、間隔の調整はこの方法で行うことが推奨されている。
```

2021-07-31 22:34 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2021-08-01 06:24 UTC, momdo approved these changes

2021-08-01 06:24 UTC, momdo commented
@caztcha 
ありがとうございます。マージします。

2021-08-01 06:24 UTC, merged