達成方法集 CSS9の翻訳
waic/wcag21 pull request #1051
Opened 2021-07-25 07:25 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-25 07:26 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-07-31 03:53 UTC, momdo requested changes
@caztcha 
ありがとうございます。レビューしましたのでご確認ください。

2021-07-31 03:53 UTC, momdo commented on techniques/css/C9.html
> +            <p>この達成方法の目的は、単に装飾することだけが目的の画像と、マークアップを追加することなくウェブコンテンツに対して視覚的な整形を行うための画像を追加する方法を示すことである。これによって、支援技術がテキストではないコンテンツを無視することが可能になる。文字サイズの拡大やハイコントラストの設定を妨げている CSS の背景画像を消すことができるように、一部のユーザエージェ
non-text contentをWCAGにあわせておきます…
```suggestion
            <p>この達成方法の目的は、単に装飾することだけが目的の画像と、マークアップを追加することなくウェブコンテンツに対して視覚的な整形を行うための画像を追加する方法を示すことである。これによって、支援技術が非テキストコンテンツを無視することが可能になる。文字サイズの拡大やハイコントラストの設定を妨げている CSS の背景画像を消すことができるように、一部のユーザエージェントでは、利用者の要求に応じて CSS を無視または無効にすることができる。
```

2021-07-31 03:53 UTC, momdo commented on techniques/css/C9.html
> +                  <p>「background property」は、<a href="https://www.w3.org/TR/css-backgrounds-3/#the-background">CSS Backgrounds and Borders Module Level 3§2.10. Backgrounds Shorthand: the background pr
```suggestion
                  <p>「background property」は、<a href="https://www.w3.org/TR/css-backgrounds-3/#the-background">CSS Backgrounds and Borders Module Level 3§2.10. Backgrounds Shorthand: the background property</a> で再定義されている。この仕様は W3C 勧告ではないが、<a href="https://www.w3.org/TR/css-2020/">CSS Snapshot 2020</a> によれば、今日の CSS を構成する仕様として位置づけられている。
```

2021-07-31 03:53 UTC, momdo commented on techniques/css/C9.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。HTML5 において、body 要素の background 属性は、は <a href="https://www.w3.org/TR/html52/obsolete.html#element-attrdef-body-background
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。HTML Standard において、body 要素の background 属性は、<a href="https://html.spec.whatwg.org/multipage/obsolete.html#attr-background">HTML Standard§16.2 Non-conforming features</a> で不適合な機能として定義されている。
```

2021-07-31 22:37 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認の上、コミットいたしました。
（仕様書周りのアップデート、ありがとうございます...！）
よろしければマージいただけますと幸いです。

2021-08-01 06:25 UTC, momdo commented
@caztcha 
作業ありがとうございます。マージします。

2021-08-01 06:25 UTC, merged