達成方法集 CSS15の翻訳
waic/wcag21 pull request #1055
Opened 2021-07-27 09:16 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-27 09:17 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-08-01 06:50 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。いずれも軽微な修正ですが、内容確認ください。

2021-08-01 06:50 UTC, momdo commented on techniques/css/C15.html
> +            <p>この達成方法の目的は、インタラクティブな要素がフォーカスされたとき、又は利用者がポインティングデバイスを使ってカーソルを上にのせたときに、スタイルシートを使って視覚的なフィードバックを返すようにすることで視覚表現がどれだけ強調されるのかを示すことである。 フォーカスされた要素又はカーソルが上にのせられた要素をハイライトすることで、その要素がインタラクティブであること
```suggestion
            <p>この達成方法の目的は、インタラクティブな要素がフォーカスされたとき、又は利用者がポインティングデバイスを使ってカーソルを上にのせたときに、スタイルシートを使って視覚的なフィードバックを返すようにすることで視覚表現がどれだけ強調されるのかを示すことである。フォーカスされた要素又はカーソルが上にのせられた要素をハイライトすることで、その要素がインタラクティブであること、又はインタラクティブな要素の範囲内であるなどの情報を提供することができる。
```

2021-08-01 06:50 UTC, momdo commented on techniques/css/C15.html
> +&lt;/ul&gt;</pre><p>マウス又はキーボードでフォーカスを受け取ったときに、上記要素の背景色を変更するCSSは次の通り:
```suggestion
&lt;/ul&gt;</pre><p>マウス又はキーボードでフォーカスを受け取ったときに、上記要素の背景色を変更する CSS は次の通り:
```

2021-08-01 06:50 UTC, momdo commented on techniques/css/C15.html
> +            </pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/C15/focus-pseudo-class.html">フォーカスを受け取る要素を強調表示する例</a>.
```suggestion
            </pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG21/working-examples/focus-pseudo-class/">フォーカスを受け取る要素を強調表示する例</a>.
```

2021-08-01 06:50 UTC, momdo commented on techniques/css/C15.html
> +                  <p>セレクターに関する仕様は、<a href="https://www.w3.org/TR/selectors-3/">Selectors Level 3</a> を参照のこと。この仕様が、CSS 2 のセレクターに関する記述に取って代わることに注意されたい。<a href="https://www.w3.org/TR/css-2018/">CSS Snap
```suggestion
                  <p>セレクターに関する仕様は、<a href="https://www.w3.org/TR/selectors-3/">Selectors Level 3</a> を参照のこと。この仕様が、CSS 2 のセレクターに関する記述に取って代わることに注意されたい。<a href="https://www.w3.org/TR/css-2020/">CSS Snapshot 2020</a> も参照のこと。
```

2021-08-01 07:56 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。
よろしければマージいただけますと幸いです。

2021-08-01 09:09 UTC, momdo approved these changes

2021-08-01 09:09 UTC, merged

2021-08-01 09:09 UTC, momdo commented
@caztcha 確認ありがとうございます。マージしました。