達成方法集 CSS17の翻訳
waic/wcag21 pull request #1056
Opened 2021-07-28 06:38 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-28 06:39 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。

2021-08-01 06:59 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。少し語句を変更しているところがありますので確認ください。

2021-08-01 06:59 UTC, momdo commented on techniques/css/C17.html
> +            <p>この達成方法の目的は、ユーザエージェントによってテキストサイズが変更されたとき、テキストベースのフォームコントロールのサイズ変更を確かにすることである。これは、利用者によって必要とされるサイズでテキストが表示されるため、利用者がテキストを登録し、そして何を入力ボックスに登録したかを読むことができるであろう。
```suggestion
            <p>この達成方法の目的は、ユーザエージェントによってテキストサイズが変更されたとき、テキストベースのフォームコントロールのサイズ変更を確実にすることである。これは、利用者によって必要とされるサイズでテキストが表示されるため、利用者がテキストを登録し、そして何を入力ボックスに登録したかを読むことを可能にするだろう。
```

2021-08-01 06:59 UTC, momdo commented on techniques/css/C17.html
> +               <p>お問い合わせフォームには、いくつかの初歩的な情報があり、利用者が自分の姓と名、電話番号、電子メールアドレスを入力するフォームコントロールがある。すべてのテキスト及びフォームコントロールは、拡大縮小可能な方法で実装されている。これは、Internet Explorer でフォントサイズが継承されていないため、フォームコントロール自体のフォントサイズを指定すること
```suggestion
               <p>お問い合わせフォームには、いくつかの前置き情報があり、利用者が自分の姓と名、電話番号、電子メールアドレスを入力するフォームコントロールがある。全てのテキスト及びフォームコントロールは、拡大縮小可能な方法で実装されている。これは、Internet Explorer でフォントサイズが継承されていないため、フォームコントロール自体のフォントサイズを指定することも含まれる。
```

2021-08-01 06:59 UTC, momdo commented on techniques/css/C17.html
> +            p, label, input { font-size: 1em; }</pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/C17/input-resize.html">CSS によって入力のサイズを変更す
```suggestion
            p, label, input { font-size: 1em; }</pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG21/working-examples/input-resize/">CSS によって入力のサイズを変更する例</a>.
```

2021-08-01 06:59 UTC, momdo commented on techniques/css/C17.html
> +height: 1.2em;}</pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/C17/radio-checkbox-resize.html">CSS によってラジオボタンとチェックボックスのサイズを変更する例</a>.
```suggestion
height: 1.2em;}</pre><p class="working-example">このコードの使用例: <a href="https://www.w3.org/WAI/WCAG21/working-examples/radio-checkbox-resize/">CSS によってラジオボタンとチェックボックスのサイズを変更する例</a>.
```

2021-08-02 08:31 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、ひととおり確認してコミットいたしました。
よろしければ、マージいただけますと幸いです。

2021-08-03 22:59 UTC, momdo approved these changes

2021-08-03 22:59 UTC, merged

2021-08-03 22:59 UTC, momdo commented
@caztcha 
確認ありがとうございました。マージしました。