達成方法集 CSS27の翻訳
waic/wcag21 pull request #1068
Opened 2021-07-29 09:22 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-07-29 09:23 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-08-01 09:06 UTC, momdo requested changes
@caztcha 
内容を大幅に調整している箇所があります。
あと、visual orderは表示順序でよいですかね…（本文では視覚的順序としていますが）
cc @bakera

2021-08-01 09:06 UTC, momdo commented on techniques/css/C27.html
> +            <p>ソースの順序が表示結果の順序と同じである場合、すべての人が同じ (正しい) 順序でコンテンツを読んで情報のやり取りをすることができる。
```suggestion
            <p>ソースの順序が視覚的順序と一致する場合、全ての人が同じ (正しい) 順序でコンテンツを読んで情報のやり取りをすることができる。 
```

2021-08-02 07:59 UTC, caztcha commented on techniques/css/C27.html
> +            <p>ソースの順序が表示結果の順序と同じである場合、すべての人が同じ (正しい) 順序でコンテンツを読んで情報のやり取りをすることができる。
原文が「visual order」なので、もんどさんご指摘の通り、「視覚的順序」のほうが良いと思います。

2021-08-02 08:04 UTC, caztcha commented
@momdo レビューありがとうございます。
修正提案、原文と照らして確認の上、コミットしました。原文の「visual order」は、もんどさんご指摘の通り、「視覚的順序」のほうがよいとおもいます。

2021-08-03 22:53 UTC, momdo commented
@caztcha コメントありがとうございます。

> 原文の「visual order」は、もんどさんご指摘の通り、「視覚的順序」のほうがよいとおもいます。

とすると、C27のタイトルが

> C27: Making the DOM order match the visual order

であるので、こちらも修正する必要があり、タイトルが変わりますと、C27へリンクしている、他の達成方法集と解説書も修正する必要がありますね……。

大変お手数ですが、そちらも修正いただけますでしょうか。

2021-08-05 05:39 UTC, caztcha commented
@momdo C27のタイトル、および C27 にリンクしているラベルをひととおり、
3bb36a4 にて修正しました。たびたびお手数ですが、レビューいただけますと幸いです。
waic/wcag21 リポジトリ全体に対してマルチファイル検索 (grep) かけたので、抜け漏れはないと思いますが...

2021-08-05 12:11 UTC, momdo approved these changes

2021-08-05 12:12 UTC, merged

2021-08-05 12:12 UTC, momdo commented
@caztcha 
ありがとうございます…！問題ないと思いますのでマージしました。