達成方法集 CSS30の翻訳
waic/wcag21 pull request #1073
Opened 2021-08-05 07:09 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-08-05 07:10 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-08-05 12:53 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。少し手を加えましたのでご確認ください。

2021-08-05 12:53 UTC, momdo commented on techniques/css/C30.html
> +                  <p>Background に関するプロパティは、<a href="https://www.w3.org/TR/css-backgrounds-3/#the-background">CSS Backgrounds and Borders Module Level 3</a> で再定義されている。この仕様は W3C 勧告ではないが、<a href="https:
```suggestion
                  <p>Background に関するプロパティは、<a href="https://www.w3.org/TR/css-backgrounds-3/#the-background">CSS Backgrounds and Borders Module Level 3</a> で再定義されている。この仕様は W3C 勧告ではないが、<a href="https://www.w3.org/TR/css-2020/">CSS Snapshot 2020</a> によれば、今日の CSS を構成する仕様として位置づけられている。
```

2021-08-05 12:53 UTC, momdo commented on techniques/css/C30.html
> +            <p>この達成方法の目的は、利用者が彼らの好みに従ってコンテンツを見ることができるような方法で構造化された HTML テキストを画像化されたテキストに置き換えるための CSS の用い方を実践することである。この達成方法を用いるには、コンテンツ制作者はページの構造をマークアップするためにセマンティックな要素を用いる HTML ページを作ることから始める。次にコンテンツ制作者
images of textが文字画像になっていなかったので、それとあわせて少し手を加えました。

```suggestion
            <p>この達成方法の目的は、利用者が好みに従ってコンテンツを表示できるように、構造化された HTML テキストを文字画像に置き換える CSS の用い方を示すことである。この達成方法を用いるには、コンテンツ制作者はページの構造をマークアップするためにセマンティックな要素を用いる HTML ページを作ることから始める。次にコンテンツ制作者はページに対して二つ以上のスタイルシートを作成する。一つめのスタイルシートは HTML テキストをテキストとして表現し、二つめはいくつかの HTML テキストを文字画像に置き換えるために CSS の機能を用いている。最後に、サーバーサイド又はクライアントサイドスクリプトの使用を通して、コンテンツ制作者は利用者が利用するビューを切り替えることができるコントロールを提供する。
```

2021-08-06 03:25 UTC, caztcha commented
@momdo レビュー、ありがとうございます。修正提案を確認の上、コミットしました。
（CSS Snapshot は 2020年版がありますね。訂正ありがとうございます！）
よろしければマージいただけますと幸いです。

2021-08-06 04:48 UTC, momdo approved these changes

2021-08-06 04:48 UTC, merged

2021-08-06 04:48 UTC, momdo commented
@caztcha 
確認ありがとうございます。マージしました。