達成方法集 H90の翻訳
waic/wcag21 pull request #1097
Opened 2021-08-16 06:35 UTC by cure-tmk

[達成方法集 H90](https://waic.jp/docs/WCAG21/Techniques/html/H90)の翻訳 (fixes: #905)

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

よろしくお願いします🙇‍♂️

2021-08-16 13:33 UTC, momdo requested changes
@cure-tmk 
作業ありがとうございます。
コード例は日本語化せず、英語のままとしてくださいませ。。 
その他いくつかコメントしましたのでご確認ください。

2021-08-16 13:33 UTC, momdo commented on techniques/html/H90.html
> +               <p>ラジオボタン及びチェックボックスは、個々のラジオボタンやチェックボックスではなく、そのグループ全体で一つの必須項目となるため、他のインタラクティブなコントロールとは異なった扱われかたをする。事例 1〜3 で使用された方法は、ラジオボタン及びチェックボックスに適用されるが、必須状態の表示は、<code class="el">label</code> 要素ではなく
```suggestion
               <p>ラジオボタン及びチェックボックスは、個々のラジオボタン及びチェックボックスではなく、そのグループ全体で一つの必須項目となるため、他のインタラクティブなコントロールとは異なった扱われかたをする。事例 1〜3 で使用された方法は、ラジオボタン及びチェックボックスに適用されるが、必須状態の表示は、<code class="el">label</code> 要素ではなく <code class="el">legend</code> 要素に配置すべきである。</p>
```

2021-08-16 13:50 UTC, cure-tmk commented
@momdo ありがとうございます，上記修正いたしましたのでご確認ください🙇‍♂️

2021-08-16 21:49 UTC, momdo requested changes
@cure-tmk 
修正ありがとうございます。いくつかコメントしていますのでご確認ください。

2021-08-16 21:49 UTC, momdo commented on techniques/html/H90.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。<a href="https://html.spec.whatwg.org/multipage/images.html#alt">HTML §4.8.4.4 Requirements for providing text to act as
サンプルママなのでリンクを修正します
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。<a href="https://html.spec.whatwg.org/multipage/forms.html#the-label-element">HTML §4.10.4 The label element</a> を代わりに参照できる。
```

2021-08-16 21:49 UTC, momdo commented on techniques/html/H90.html
> +               <p>以下のコード例にあるテキストフィールドには、明示的なラベル「名前 (必須)」がある。<code class="el">label</code> 要素の <code class="att">for</code> 属性値が、<code class="el">input</code> 要素の <code class="att">id</code> 属性値と合致してい
コード例にあわせて説明文を変更しておきます。
```suggestion
               <p>以下のコード例にあるテキストフィールドには、明示的なラベル「First name (required):」がある。<code class="el">label</code> 要素の <code class="att">for</code> 属性値が、<code class="el">input</code> 要素の <code class="att">id</code> 属性値と合致していて、<code class="el">label</code> 要素でマークアップされたテキストによってそのコントロールが必須項目であることを示している。</p>
```

2021-08-16 21:49 UTC, momdo commented on techniques/html/H90.html
> +&lt;p&gt;&lt;img src="req_img.gif" alt="必須項目" /&gt; はコントロールが必須であることを示す&lt;/p&gt;
もとに戻し忘れ
```suggestion
&lt;p&gt;&lt;img src="req_img.gif" alt="Required Control" /&gt; indicates that the form control is required&lt;/p&gt;
```

2021-08-16 21:49 UTC, momdo commented on techniques/html/H90.html
> +               <h3>事例3: 画像を用いて必須項目であることを示す</h3>
```suggestion
               <h3>事例 3: 画像を用いて必須項目であることを示す</h3>
```

2021-08-17 01:16 UTC, cure-tmk commented
@momdo 失礼しました，ご指摘ありがとうございます🙇‍♂️

2021-08-17 04:30 UTC, momdo approved these changes
@cure-tmk 
修正ありがとうございます。
すべて解決されていることを確認しましたのでマージします…！

2021-08-17 04:30 UTC, merged