達成方法集 F32の翻訳
waic/wcag21 pull request #1127
Opened 2021-09-01 08:20 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-01 08:20 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳に訳注があったので流用しました。

2021-09-09 09:01 UTC, caztcha commented on techniques/failures/F32.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
a

2021-09-09 09:01 UTC, caztcha commented on techniques/failures/F32.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
```suggestion
         <p>この達成方法 (参考) の使用法と、この達成方法が WCAG 2.1 達成基準 (規定) とどのように関係するのかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) のセクションは、その達成方法の範囲について説明しており、特定の技術に関する達成方法の存在は、その技術があらゆる状況で WCAG 2.1 を満たすコンテンツを作成するために使用できることを意味するものではない。
```

2021-09-09 09:01 UTC, caztcha commented
@momdo 「達成方法に関する重要な情報」も修正済です。

2021-09-12 09:15 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
1点修正を加えていますのでご確認ください。

2021-09-12 09:15 UTC, momdo commented on techniques/failures/F32.html
> +               <p>データテーブルの行見出しセルに日本語が含まれる場合に、制作者は改行文字を使用して縦書きのテキストを表現することがよくある。しかし、単語中に改行文字があるために、スクリーンリーダーはこのような縦書き文字列にある単語を正しく読み上げることができない。次の例は「東京都 (とうきょうと)」ではなく「ひがし　きょう　みやこ」と読み上げられてしまう。
```suggestion
               <p>データテーブルの行見出しセルに日本語が含まれる場合に、コンテンツ制作者は改行文字を使用して縦書きのテキストを表現することがよくある。しかし、単語中に改行文字があるために、スクリーンリーダーはこのような縦書き文字列にある単語を正しく読み上げることができない。次の例は「東京都 (とうきょうと)」ではなく「ひがし　きょう　みやこ」と読み上げられてしまう。
```

2021-09-13 07:05 UTC, caztcha commented
@momdo レビューありがとうございます。「制作者」→「コンテンツ制作者」の修正提案、すみませんでした。確認のうえコミットしましたので、マージいただけますと幸いです。

2021-09-14 04:25 UTC, momdo approved these changes
@caztcha 確認ありがとうございます。
マージします。

2021-09-14 04:25 UTC, merged