達成方法集 F40の翻訳
waic/wcag21 pull request #1135
Opened 2021-09-02 04:49 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-02 04:51 UTC, caztcha commented
@momdo 翻訳作業を実施しました。

「検証」のセクションが全面的に変更されていたので、その部分を新しく翻訳しました。

2021-09-02 05:02 UTC, caztcha commented on techniques/failures/F40.html
> +      <title>F40: 達成基準 2.2.1、達成基準 2.2.4 及び 達成基準 3.2.5 の失敗例 － 制限時間付きの meta 要素リダイレクトを使用している
```suggestion
      <title>F40: 達成基準 2.2.1、達成基準 2.2.4、及び 達成基準 3.2.5 の失敗例 － 制限時間付きの meta 要素リダイレクトを使用している
```

2021-09-02 05:04 UTC, caztcha commented on techniques/index.html
> +      <li><a href="failures/F40">F40: 達成基準 2.2.1、達成基準 2.2.4 及び 達成基準 3.2.5 の失敗例 － 制限時間付きの meta 要素リダイレクトを使用している</a></li>
```suggestion
      <li><a href="failures/F40">F40: 達成基準 2.2.1、達成基準 2.2.4、及び 達成基準 3.2.5 の失敗例 － 制限時間付きの meta 要素リダイレクトを使用している</a></li>
```

2021-09-09 09:15 UTC, caztcha commented on techniques/failures/F40.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
a

2021-09-09 09:15 UTC, caztcha commented on techniques/failures/F40.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
```suggestion
         <p>この達成方法 (参考) の使用法と、この達成方法が WCAG 2.1 達成基準 (規定) とどのように関係するのかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) のセクションは、その達成方法の範囲について説明しており、特定の技術に関する達成方法の存在は、その技術があらゆる状況で WCAG 2.1 を満たすコンテンツを作成するために使用できることを意味するものではない。
```

2021-09-09 09:16 UTC, caztcha commented
@momdo 「達成方法に関する重要な情報」も修正済です。

2021-09-16 11:19 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
訳注を変更しましたが、これで問題ないかご確認ください。

2021-09-16 11:19 UTC, momdo commented on techniques/failures/F40.html
> +                     <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記は、<a href="https://www.w3.org/TR/html52/document-metadata.html#the-meta-element">HTML 5.2§4.2.5. The meta element</
```suggestion
                     <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記は、<a href="https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element">HTML §4.2.5 The meta element</a> を代わりに参照できる。
```

2021-09-17 07:45 UTC, caztcha commented
@momdo 訳注の修正提案、ありがとうございました。問題ありません。コミットしました。

2021-09-17 10:55 UTC, momdo approved these changes

2021-09-17 10:55 UTC, momdo commented
@caztcha 確認ありがとうございます。マージします。

2021-09-17 10:55 UTC, merged