達成方法集 F42の翻訳
waic/wcag21 pull request #1137
Opened 2021-09-02 05:47 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-02 05:50 UTC, caztcha commented
@momdo 翻訳作業を実施しました。

「適用 (対象)」のセクションで、SC 2.1.3 および 4.1.2 が原文から抜けています。しれっと追加しておいたほうがよいですかね...

2021-09-09 09:19 UTC, caztcha commented on techniques/failures/F42.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
a

2021-09-09 09:19 UTC, caztcha commented on techniques/failures/F42.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
```suggestion
         <p>この達成方法 (参考) の使用法と、この達成方法が WCAG 2.1 達成基準 (規定) とどのように関係するのかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) のセクションは、その達成方法の範囲について説明しており、特定の技術に関する達成方法の存在は、その技術があらゆる状況で WCAG 2.1 を満たすコンテンツを作成するために使用できることを意味するものではない。
```

2021-09-09 09:22 UTC, caztcha commented
@momdo 「達成方法に関する重要な情報」も修正済です。

2021-09-16 11:21 UTC, momdo commented
@caztcha 

>「適用 (対象)」のセクションで、SC 2.1.3 および 4.1.2 が原文から抜けています。しれっと追加しておいたほうがよいですかね...

訳注にするかしれっと追加するかどうしましょうか…？

2021-09-16 11:28 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
細かいですが1点だけ確認ください。

2021-09-16 11:28 UTC, momdo commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
「の」は不要ですかね…
```suggestion
                  <li>プログラムによる解釈された要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
```

2021-09-17 07:47 UTC, caztcha commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
```suggestion
                  <li>プログラムにより解釈された要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
```

2021-09-17 07:51 UTC, caztcha commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
@momdo そうですね。「の」は不要かと。
「プログラムによる解釈された」→「プログラムに**より**解釈された」としてみました。

2021-09-17 10:58 UTC, momdo commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
@caztcha 

日本語としては「より」のほうがよさそうではありますが、一方で

https://waic.jp/docs/WCAG21/#dfn-programmatically-determinable

> プログラムによる解釈 (プログラムによる解釈が可能) (programmatically determined (programmatically determinable))

とどう整合性を取るか、ですね…

2021-09-19 21:35 UTC, caztcha commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
@momdo たしかに。用語として「プログラムに**よる**解釈」は維持したほうがよさそうに思います。
とすると、一周回って「プログラムによる解釈**の**された」でよいのかな、と思ったり。

2021-09-19 21:52 UTC, momdo commented on techniques/failures/F42.html
> +                  <li>プログラムによる解釈のされた要素の役割 (role) が <code class="prop">link</code> かどうかを確認する。
では、ママとしましょう…！

2021-09-19 21:53 UTC, momdo commented
@caztcha 確認ありがとうございます。
確認箇所はママとしてマージします。

2021-09-19 21:54 UTC, momdo approved these changes

2021-09-19 21:54 UTC, merged