達成方法集 F46の翻訳
waic/wcag21 pull request #1143
Opened 2021-09-03 02:02 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-03 02:03 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。

2021-09-09 11:22 UTC, caztcha commented on techniques/failures/F46.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
a

2021-09-09 11:22 UTC, caztcha commented on techniques/failures/F46.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セ
```suggestion
         <p>この達成方法 (参考) の使用法と、この達成方法が WCAG 2.1 達成基準 (規定) とどのように関係するのかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) のセクションは、その達成方法の範囲について説明しており、特定の技術に関する達成方法の存在は、その技術があらゆる状況で WCAG 2.1 を満たすコンテンツを作成するために使用できることを意味するものではない。
```

2021-09-09 11:23 UTC, caztcha commented
@momdo 「達成方法に関する重要な情報」も修正済です。

2021-09-17 11:39 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
既存の翻訳に手を入れてみましたので確認いただけるでしょうか。

2021-09-17 11:39 UTC, momdo commented on techniques/failures/F46.html
> +            <p>支援技術は、HTML 及び XHTML のテーブルに含まれる構造的な情報を用いて、利用者に対してデータを論理的な形で伝えるようになっている。th 要素は、行や列の見出しを表すために用いられる。スクリーンリーダーを利用している場合、表の中を移動しながら読む時、移動した先のセルの行や列の見出しを読み上げるために th 要素の内容が利用される。summary 属性は、その
ぬるっと原文に近づけてみました。
```suggestion
            <p>支援技術は、HTML 又は XHTML のテーブルに含まれる構造を用いて、利用者に対してデータを論理的な形で伝える。th 要素は、行及び列の見出しをマークすすために用いられる。スクリーンリーダーは、利用者が表をナビゲートすると、変化する見出し情報を読み上げるために th 要素の情報を利用する。table 要素の summary 属性は、その表の目的及び機能についてのテキストによる説明を提供する。支援技術は、summary 属性の情報を利用者が利用できるようにする。caption 要素は表の一部であり、その表を特定する役割を持つ。
```

2021-09-17 11:39 UTC, momdo commented on techniques/failures/F46.html
> +               WCAG 2 はレイアウトテーブルの使用を禁止していないが、HTML のテーブル関連要素の定義されたセマンティックな意味を保持し、コンテンツから提示を分離するコーディングの慣習に従うためにも、CSS ベースのレイアウトが推奨される。テーブルがレイアウトの目的で使用されるとき、th 要素を使用すべきではない。そのテーブルはデータを示していないため、どのセルも行又は列の
```suggestion
               WCAG 2 はレイアウトテーブルの使用を禁止していないが、HTML のテーブル関連要素の定義されたセマンティックな意味を保持し、コンテンツから提示を分離するコーディングの慣習に従うためにも、CSS ベースのレイアウトが推奨される。テーブルがレイアウトの目的で使用されるとき、th 要素を使用すべきではない。そのテーブルはデータを示していないため、どのセルも行又は列の見出しとしてマークアップする必要はない。同様に、コンテンツをレイアウトするためにのみ用いられているテーブルについて、追加の説明を提供する必要はない。summary 属性を含めない。そして、テーブルを「レイアウトテーブル」のような説明をするために summary 属性を使用しない。音声の場合、この情報は価値を提供せず、スクリーンリーダーを通してコンテンツをナビゲートする利用者の気を散らすだけである。空の summary 属性はレイアウトテーブルで許容されるが、推奨されない。
```

2021-09-17 11:39 UTC, momdo commented on techniques/failures/F46.html
> +                     <p>そのコンテンツ中で、視覚的レイアウトのみの目的でテーブルが用いられている場合
```suggestion
                     <p>そのコンテンツの中で、視覚的レイアウトのみの目的でテーブルが用いられている場合
```

2021-09-19 21:40 UTC, caztcha commented
@momdo レビューありがとうございます。既存翻訳部部分の見直しも含め確認しコミットしました。よろしければマージいただけますと幸いです。

2021-09-19 21:54 UTC, momdo approved these changes

2021-09-19 21:55 UTC, momdo commented
@caztcha 確認ありがとうございます。
マージします。

2021-09-19 21:55 UTC, merged