達成方法集 F52の翻訳
waic/wcag21 pull request #1167
Opened 2021-09-13 07:42 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-13 07:42 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
訳注があるので流用しました。

2021-09-18 02:24 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
loadの訳語の調整をしてみましたのでご確認ください。

2021-09-18 02:24 UTC, momdo commented on techniques/failures/F52.html
> +            <p>製品又はサービスを宣伝するために、あるウェブサイトではページが読みこまれた時に新しいウィンドウが開く。この達成方法の目的は、ページが読み込まれたと同時に一つ以上の新しいウィンドウが開かれることによって、ページが利用者を混乱させないようにすることである。
タイトルの「読み込む」にあわせてみました
```suggestion
            <p>製品又はサービスを宣伝するために、あるウェブサイトではページが読み込まれた時に新しいウィンドウが開く。この達成方法の目的は、ページが読み込まれたと同時に一つ以上の新しいウィンドウが開かれることによって、ページが利用者を混乱させないようにすることである。
```

2021-09-18 02:24 UTC, momdo commented on techniques/failures/F52.html
> +                  <li>新しいページをロードする</li>
```suggestion
                  <li>新しいページを読み込む</li>
```

2021-09-18 02:24 UTC, momdo commented on techniques/failures/F52.html
> +                  <li>新しいページをロードしたことの結果として新しいウィンドウが開かれたかどうかを確認する
```suggestion
                  <li>新しいページを読み込んだ結果として新しいウィンドウが開かれたかどうかを確認する 
```

2021-09-19 21:50 UTC, caztcha commented
@momdo レビューありがとうございます。load の訳語調整、確認しコミットしました。よろしければマージいただけますと幸いです。

2021-09-19 21:59 UTC, momdo commented
@caztcha 確認ありがとうございます。
マージします。

2021-09-19 21:59 UTC, momdo approved these changes

2021-09-19 21:59 UTC, merged