達成方法集 F59の翻訳
waic/wcag21 pull request #1171
Opened 2021-09-14 07:59 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-14 08:01 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
「WAI-ARIA 1.0」は現状では「1.1」なので、訳注の追加と修正を加えています。

2021-09-18 03:08 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
roleの訳語に手を入れてみました。ご確認ください。

2021-09-18 03:08 UTC, momdo commented on techniques/failures/F59.html
> +            <p>この失敗例では、ユーザインタフェースコントロールを生成するために汎用的な HTML 要素を用いたとき、どのようにしてコントロールが支援技術に対してアクセシブルでなくなるかを示している。コンポーネントについての情報を利用者に伝達する際、支援技術は、コンポーネントのロール及びカレントステートの情報に依存している。多くの HTML 要素は、リンク、ボタン、テキストフィール
```suggestion
            <p>この失敗例では、ユーザインタフェースコントロールを生成するために汎用的な HTML 要素を用いたとき、どのようにしてコントロールが支援技術に対してアクセシブルでなくなるかを示している。コンポーネントについての情報を利用者に伝達する際、支援技術は、コンポーネントの役割 (role) 及びカレントステートの情報に依存している。多くの HTML 要素は、リンク、ボタン、テキストフィールドなどといった明確な役割 (role) を持っている。<code class="el">div</code> 及び <code class="el">span</code> などの汎用的な要素は、事前に定義された役割 (role) がない。これらの汎用的な要素が、HTML でユーザインタフェースコントロールを生成するために使用されると、支援技術は、コントロールを表現したり、コントロールとやり取りしたりするために必要な情報を得られないかもしれない。
```

2021-09-19 21:58 UTC, caztcha commented
@momdo レビューありがとうございます。role の訳語、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2021-09-19 22:01 UTC, momdo commented
@caztcha 確認ありがとうございます。
マージします。

2021-09-19 22:02 UTC, momdo approved these changes

2021-09-19 22:02 UTC, merged