達成方法集 F61の翻訳
waic/wcag21 pull request #1173
Opened 2021-09-15 07:59 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-15 08:02 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
原文では、2.0 と 2.1 で差分はなかったのですが、なぜか 2.0 の日本語訳で、Tests セクションの Procedure の翻訳が抜け落ちていました（イレギュラーですが、この達成方法では Procedure がふたつあって、ひとつめの Procedure の日本語訳がない状態でした）。その部分だけ、新規で英訳を起こしています。

2021-09-18 03:16 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
1点だけ確認ください。

2021-09-18 03:16 UTC, momdo commented on techniques/failures/F61.html
> +            <p>この文書では、メインの<a href="https://waic.jp/docs/WCAG21/#dfn-viewport">ビューポート</a>に表示されているコンテンツが自動的に更新され、コンテンツに利用者がこの振る舞いを停止するための選択肢をがない失敗例について述べている。
```suggestion
            <p>この文書では、メインの<a href="https://waic.jp/docs/WCAG21/#dfn-viewport">ビューポート</a>に表示されているコンテンツが自動的に更新され、コンテンツに利用者がこの振る舞いを停止するための選択肢がない失敗例について述べている。 
```

2021-09-19 22:00 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2021-09-19 22:03 UTC, momdo commented
@caztcha 確認ありがとうございます。
マージします。

2021-09-19 22:03 UTC, momdo approved these changes

2021-09-19 22:04 UTC, merged