達成方法集 F63の翻訳
waic/wcag21 pull request #1174
Opened 2021-09-15 08:25 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-09-15 08:28 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、下記の通り若干の差分がありましたので、調整しています。
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FNOTE-WCAG20-TECHS-20161007%2FF63.html&doc2=https%3A%2F%2Fwaic.github.io%2Fwcag21%2Ftechniques%2Ffailures%2FF63

2021-09-18 03:23 UTC, momdo requested changes
@caztcha 作業ありがとうございます。
少しコメントしましたのでご確認ください。

2021-09-18 03:23 UTC, momdo commented on techniques/failures/F63.html
> +            <p>この文書は、リンクの目的を理解するために必要な文脈が、プログラムによる解釈が可能なリンクの文脈ではないコンテンツの中に置かれているという失敗例について解説する。リンクの文脈が次のいずれかの方法で提供されていない場合:
ここで出てくるcontextって、「リンクの目的 (コンテキスト内)」のコンテキストなのですかね…そうであれば、コンテキストとすべきかなと。

2021-09-18 03:23 UTC, momdo commented on techniques/failures/F63.html
> +               <li>リンクとして同じ文章、段落、リストの項目、またはテーブルのセルの場合</li>
```suggestion
               <li>リンクと同じ文章、段落、リストの項目、又はテーブルのセルの場合</li>
```

2021-10-01 01:45 UTC, caztcha commented on techniques/failures/F63.html
> +            <p>この文書は、リンクの目的を理解するために必要な文脈が、プログラムによる解釈が可能なリンクの文脈ではないコンテンツの中に置かれているという失敗例について解説する。リンクの文脈が次のいずれかの方法で提供されていない場合:
確認しました。この F63 の中に出てくる「文脈」は、ひととおり「コンテキスト」に変換します。（タイトルも含めて。）

タイトル変更を伴うので、index.html、および他の達成方法の中で F63 へのリンクが設けられている箇所をひととおり grep 検索して、置換するようにします。

2021-10-01 04:57 UTC, caztcha commented
@momdo 「文脈」→「コンテキスト」の置換を実施しました。
F63 および index.html の修正は e8aebc1 
他の達成方法で F63 へのリンクがある箇所のラベル修正は abf36fa
です。

2021-10-02 02:51 UTC, momdo approved these changes
@caztcha 修正作業ありがとうございます…！
問題なさそうなのでマージします。

2021-10-02 02:51 UTC, merged