達成方法集 SCR1の翻訳
waic/wcag21 pull request #1236
Opened 2021-11-07 06:41 UTC by 8845musign

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-11-07 06:44 UTC, 8845musign commented
@momdo 

レビューお願いします🙇‍♂️

- 期待される結果の説明文が2.1では削除されていました
- 2.0の翻訳版で追加されていた注記はそのまま持ってきました

2021-11-10 08:59 UTC, momdo requested changes
@8845musign 
作業ありがとうございます。2点コメントしましたのでご確認ください。

2021-11-10 08:59 UTC, momdo commented on techniques/client-side-script/SCR1.html
> +            <div class="note"><p class="prefix"><em>注記:</em> この達成方法は、<a href="https://waic.jp/docs/WCAG21/Understanding/timing-adjustable">達成基準 2.2.1</a> を満たす他の達成方法と組み合わせなければならない。詳細については、 <a href="ht
原文にないので、この注記は削除しておいてください…。

2021-11-10 08:59 UTC, momdo commented on techniques/client-side-script/SCR1.html
> +            <p>この達成方法の目的は、スクリプトがデフォルトの制限時間のある機能を提供する際、その時間を延長するメカニズムを提供することによって、利用者がデフォルトの制限時間を延長できるようにすることである。利用者がより長い制限時間を要求できるようにするために、利用者がより長い制限時間を入力できる、又はより多くの時間を必要としていることを示す (例えば) フォームをスクリプトが提供
em要素を削除しておきます…
```suggestion
            <p>この達成方法の目的は、スクリプトがデフォルトの制限時間のある機能を提供する際、その時間を延長するメカニズムを提供することによって、利用者がデフォルトの制限時間を延長できるようにすることである。利用者がより長い制限時間を要求できるようにするために、利用者がより長い制限時間を入力できる、又はより多くの時間を必要としていることを示す (例えば) フォームをスクリプトが提供することができる。制限時間が切れそうであることを利用者に警告する場合 (<a href="SCR16.html">SCR16: 制限時間が切れようとしていることを利用者に警告するスクリプトを提供する</a>を参照)、このフォームを警告のダイアログから利用可能にする。どれぐらいの追加時間が必要かを示すことができるようにするか、繰り返し制限時間を延長できるようにすることによって、利用者はデフォルトの制限時間を少なくとも 10 倍延長することができる。
```

2021-11-19 02:13 UTC, momdo approved these changes

2021-11-19 02:14 UTC, merged

2021-11-19 02:14 UTC, momdo commented
@8845musign 対応ありがとうございました。マージしました。