達成方法集 G18の翻訳
waic/wcag21 pull request #1248
Opened 2021-12-14 05:47 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-14 05:48 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
2.0 の日本語版に訳注があったのを流用しました。

2021-12-16 08:24 UTC, momdo requested changes
作業aありがとうございます。
日本語の場合の文字サイズについてコメントしています。

2021-12-16 08:24 UTC, momdo commented on techniques/general/G18.html
> +            <p>この達成方法の目的は、利用者が背景の上にあるテキストを読めるようにすることである。達成基準 1.4.3 に関しては、この達成方法は 18pt (太字ではない: 日本語の場合は 22pt) 未満と 14pt (太字: 日本語の場合は 18pt) 未満のテキストのための最小コントラスト比を説明している。さらに、達成基準 1.4.6 においては、この達成方法は少なくとも
See also https://github.com/waic/wcag21/issues/1240

日本語の場合の記述は原文にはないわけですから、訳注として記載するのがよいかなと。

2021-12-16 08:24 UTC, momdo commented on techniques/general/G18.html
> +            <p>もし背景が無地の色 (または真っ黒、真白) の場合、各テキストの文字が背景とのコントラスト比を 4.5:1 で保持することによってテキストの相対輝度を維持することができる。
```suggestion
            <p>背景が無地の色 (または真っ黒、真白) の場合、各テキストの文字が背景とのコントラスト比を 4.5:1 で保持することによってテキストの相対輝度を維持することができる。
```

2021-12-16 08:24 UTC, momdo commented on techniques/general/G18.html
> +            <p>もし、背景画像または背景色が標準的に相対輝度で十分に違いがない場合は、他の方法として必要なコントラスト比を提供したテキストの周りに後光を提供する方法もある。
```suggestion
            <p>背景画像又は背景色が標準的に相対輝度で十分に違いがない場合、他の方法として必要なコントラスト比を提供したテキストの周りに後光を提供する方法もある。
```

2021-12-16 08:53 UTC, caztcha commented on techniques/general/G18.html
> +            <p>この達成方法の目的は、利用者が背景の上にあるテキストを読めるようにすることである。達成基準 1.4.3 に関しては、この達成方法は 18pt (太字ではない: 日本語の場合は 22pt) 未満と 14pt (太字: 日本語の場合は 18pt) 未満のテキストのための最小コントラスト比を説明している。さらに、達成基準 1.4.6 においては、この達成方法は少なくとも
なるほど、そのとおりです。訳注として記載する形で、改めてコミット出します。

2021-12-17 01:16 UTC, caztcha commented
@momdo いただいた[コメント](https://github.com/waic/wcag21/pull/1248#discussion_r770312122) (日本語の場合のポイント数について、原文にはない内容なので、本文ではなく訳注に記載すべき件) について、コミット f8ac1bf にて対応しました。
ポイントとピクセルの換算についてはここでは特に触れず、WCAG 2.1 日本語訳の用語集「[サイズの大きな (テキスト) (large scale (text))](https://waic.jp/docs/WCAG21/#dfn-large-scale)」にある訳注の内容を流用しています。

2021-12-24 05:58 UTC, momdo approved these changes

2021-12-24 05:58 UTC, merged

2021-12-24 05:58 UTC, momdo commented
@caztcha 
対応ありがとうございます。問題ないかと思いますのでマージしました。