達成方法集 G53の翻訳
waic/wcag21 pull request #1250
Opened 2021-12-14 06:44 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-14 06:45 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
2.0 の日本語版に訳注があったのを流用しました。

2021-12-24 08:34 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしましたのでご確認ください。

2021-12-24 08:34 UTC, momdo commented on techniques/general/G53.html
> +            <p>この達成方法の目的は、リンク及びその文脈からリンクの目的を特定することである。そのリンクを含んでいる文章によって、リンクテキストだけでは不明瞭なリンクに文脈が与えられることになる。その説明によって、利用者がそのリンクと、そのウェブページ内にある他のリンクとを区別できるようになり、そのリンク先へ移動するかどうかを判断しやすくなる。一般的に、リンクテキストとして単に目的
文脈→コンテキスト　ですね。
あと、全体的に意訳されてる気もしますがまあ、これについてはよいでしょう…。

2022-01-13 07:18 UTC, caztcha commented
@momdo レビューありがとうございます。「文脈」→「コンテキスト」に修正しました。 3b837da

2022-01-22 09:51 UTC, momdo approved these changes

2022-01-22 09:51 UTC, momdo commented
@caztcha 
修正ありがとうございます。問題なさそうなのでマージします。

2022-01-22 09:51 UTC, merged