達成方法集 G163の翻訳
waic/wcag21 pull request #1253
Opened 2021-12-15 02:28 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 02:29 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:06 UTC, momdo requested changes
@caztcha 
1点コメントしましたのでご確認ください。

2021-12-24 09:06 UTC, momdo commented on techniques/general/G163.html
> +            <p>単語の発音を正しく示したり、単語同士の区別に役立つように、多くの言語で発音区別符号が利用されている。一部の言語は、母音、重子音、母音や子音の欠落を示したり、他の目的のために発音区別符号を用いている。発音区別符号がなくてもテキストを読むことはできるが、発音区別符号の追加によって読解可能性 (リーダビリティ: Readability) を改善できる。
readability は単にリーダビリティでよいと思うのですが、いかがでしょう。。

2022-01-13 07:20 UTC, caztcha commented on techniques/general/G163.html
> +            <p>単語の発音を正しく示したり、単語同士の区別に役立つように、多くの言語で発音区別符号が利用されている。一部の言語は、母音、重子音、母音や子音の欠落を示したり、他の目的のために発音区別符号を用いている。発音区別符号がなくてもテキストを読むことはできるが、発音区別符号の追加によって読解可能性 (リーダビリティ: Readability) を改善できる。
ですね。あえて英語表記は不要かと思います。修正します。

2022-01-13 07:23 UTC, caztcha commented
@momdo レビューありがとうございます。「リーダビリティ」部分の表記を修正しました。 1f1c4c0

2022-01-22 09:52 UTC, momdo approved these changes

2022-01-22 09:52 UTC, momdo commented
@caztcha 
修正ありがとうございます。マージします。

2022-01-22 09:52 UTC, merged