達成方法集 G206の翻訳
waic/wcag21 pull request #1255
Opened 2021-12-15 03:01 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 03:01 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:13 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。2点コメントしましたので、ご確認ください。

2021-12-24 09:13 UTC, momdo commented on techniques/general/G206.html
> +            <p>制作者は、横スクロールを必要とするようなレイアウトを使用することがある。その場合でも、横スクロールを必要とせずに 1 行のテキストを読めるレイアウトに切り替えるオプションをコンテンツ内で提供することで、達成基準を満たすことができる。これは、標準的なスタイル切り替えの技術を用いることで達成できる。
```suggestion
            <p>コンテンツ制作者は、横スクロールを必要とするようなレイアウトを使用することがある。その場合でも、横スクロールを必要とせずに 1 行のテキストを読めるレイアウトに切り替えるオプションをコンテンツ内で提供することで、達成基準を満たすことができる。これは、標準的なスタイル切り替えの技術を用いることで達成できる。
```

2021-12-24 09:13 UTC, momdo commented on techniques/general/G206.html
> +                  <p>この達成方法は、適合していないなコンテンツに代わって<a href="https://waic.jp/docs/WCAG21/#dfn-conforming-alternate-version">適合している代替版</a>のページを表示させるためのスタイル切り替え技術と組み合わせて使うこともできる。詳細は、<a href="../css/C29">C29
```suggestion
                  <p>この達成方法は、適合していないコンテンツに代わって<a href="https://waic.jp/docs/WCAG21/#dfn-conforming-alternate-version">適合している代替版</a>のページを表示させるためのスタイル切り替え技術と組み合わせて使うこともできる。詳細は、<a href="../css/C29">C29: 適合している代替版を提供するために、スタイルスイッチャーを使用する</a> 及び <a href="https://waic.jp/docs/WCAG21/Understanding/conformance#conforming-alt-versions">適合している代替版を理解する</a> を参照のこと。
```

2022-01-13 07:27 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2022-01-22 09:53 UTC, momdo approved these changes

2022-01-22 09:53 UTC, momdo commented
@caztcha 
確認ありがとうございます。マージします。

2022-01-22 09:53 UTC, merged