達成方法集 G205の翻訳
waic/wcag21 pull request #1256
Opened 2021-12-15 03:12 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 03:12 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:16 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしました（多分これでよいはず）
ご確認ください。

2021-12-24 09:16 UTC, momdo commented on techniques/general/G205.html
> +            <p>この達成方法の目的は、情報を伝えるために、色と、テキスト又は文字による手がかりを併用することである。ほとんどの利用者は色の差を用いた情報を素早く認識できる。色を識別できない利用者は、視覚的又は聴覚的にテキストによる手がかりを認識する。点字ディスプレイや、他の触覚インタフェースを使っている人々は触ることでテキストによる手がかりを見つけられる。
```suggestion
            <p>この達成方法の目的は、情報を伝えるために、色及び、テキスト又は文字による手がかりを併用することである。ほとんどの利用者は色の差を用いた情報を素早く認識できる。色を識別できない利用者は、視覚的又は聴覚的にテキストによる手がかりを認識する。点字ディスプレイや、他の触覚インタフェースを使っている人々は触ることでテキストによる手がかりを見つけられる。
```

2022-01-13 07:30 UTC, caztcha commented
@momdo レビューありがとうございました。いただいた修正提案、原文と照らして確認のうえ、コミットしました。よろしければマージいただけますと幸いです。

2022-01-22 09:55 UTC, merged