達成方法集 G204の翻訳
waic/wcag21 pull request #1257
Opened 2021-12-15 03:25 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 03:26 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
2.0 の日本語版に訳注があったのを流用しました。

2021-12-24 09:21 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしましたのでご確認ください。

2021-12-24 09:21 UTC, momdo commented on techniques/general/G204.html
> +            <p>この達成方法は、横スクロールが起こる状況を回避することを助けるものである。ブロックやテキストの横スクロールは、支援技術を用いていない認識障害がある人々やロービジョンの利用者にとっては大きな問題となる。ウィンドウ幅が狭い時にテキストのリフローを妨げないことも含まれる。最善の方法のひとつは、テキストブロックコンテナの横幅をパーセントで定義することである。
```suggestion
            <p>この達成方法は、横スクロールが起こる状況を回避することを助けるものである。ブロックやテキストの横スクロールは、支援技術を用いていない認識障害がある人及びロービジョンの利用者にとっては大きな問題となる。ウィンドウ幅が狭い時にテキストのリフローを妨げないことも含まれる。最善の方法のひとつは、テキストブロックコンテナの横幅をパーセントで定義することである。
```
こうですかね

2022-01-13 07:49 UTC, caztcha commented
@momdo レビューありがとうございます。ご指摘いただいた箇所ですが、改めて原文と照らして、誤訳が見られましたので、コミット 3a92c8d にて修正しました。お手数をおかけいたしますが、ご確認いただけますと幸いです。

2022-01-22 10:00 UTC, merged