達成方法集 G201の翻訳
waic/wcag21 pull request #1260
Opened 2021-12-15 05:02 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 05:02 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:30 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしましたのでご確認ください。

2021-12-24 09:30 UTC, momdo commented on techniques/general/G201.html
> +            <p>この達成方法の目的は、自動的に新しいウィンドウまたはタブを開く前に利用者に知らせることである。リンクを動作させたときに自動的に新しいウィンドウを開くことは、もし事前にそのことを知らせていなければ、視覚的なコンテンツを知覚するのに困難を伴う利用者や認知障害のある利用者が混乱する原因となりうる。事前に知らせることによって、利用者は現在のウィンドウから離れるかどうかを判断
こうですかね
```suggestion
            <p>この達成方法の目的は、自動的に新しいウィンドウ又はタブを開く前に利用者に知らせることである。リンクを動作させたときに自動的に新しいウィンドウを開くことは、もし事前にそのことを知らせていなければ、視覚的なコンテンツを知覚するのに困難を伴う利用者や認知障害のある利用者が混乱する原因となりうる。事前に知らせることによって、利用者は現在のウィンドウから離れるかどうかを判断することができるようになる。また、利用者が新しいウィンドウを開くことを選んだ場合にも、元のウィンドウに戻りやすくなる。さらに、ブラウザの [戻る] ボタンが使えないこと及び、直前まで自分がいた場所を見つけるためには元のウィンドウに戻らなければならないことを利用者が理解する手助けにもなる。
```

2022-01-13 08:05 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2022-01-22 10:02 UTC, momdo approved these changes
@caztcha 
確認ありがとうございます。マージします。

2022-01-22 10:02 UTC, merged