達成方法集 G200の翻訳
waic/wcag21 pull request #1261
Opened 2021-12-15 05:23 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-15 05:24 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:40 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。いくつかコメントしていますのでご確認ください。

2021-12-24 09:40 UTC, momdo commented on techniques/general/G200.html
> +            <p>この達成方法の目的は、ウェブコンテンツ内で新しいウィンドウまたはタブを開くリンクまたはボタンの使用を限定することである。一般的に、新しいウィンドウやタブを開かないほうがよい。なぜなら、特に視覚的なコンテンツを知覚するのに困難を伴う利用者をはじめ、利用者にとっては混乱の原因となりうるからである。しかし、アクセシビリティの観点から、新しいウィンドウやタブを開くことが望ま
こうですかね
```suggestion
            <p>この達成方法の目的は、ウェブコンテンツ内で新しいウィンドウ又はタブを開くリンクまたはボタンの使用を限定することである。一般的に、新しいウィンドウ及びタブを開かないほうがよい。なぜなら、特に視覚的なコンテンツを知覚するのに困難を伴う利用者をはじめ、利用者にとっては混乱の原因となりうるからである。しかし、アクセシビリティの観点から、新しいウィンドウ又はタブを開くことが望ましい状況というのもある。例えば、次の二つのような場合である:
```

2021-12-24 09:40 UTC, momdo commented on techniques/general/G200.html
> +               <li>例えば、ヘルプの説明文またはカレンダーを用いたデートピッカー (日付選択) のようなフォーム入力の代替手段のように、状況に応じた情報を含むウェブページを開く際に、もしそういったウェブページが同じウィンドウやタブで開かれるとしたら、フォームを入力したり送信したりするような複数のステップから成るワークフローを著しく中断させることになる。
> Opening a page containing context-sensitive information, such as help instructions, or an alternate means of completing a form, such as a calendar-based date picker,  

は

Opening (a page containing context-sensitive information, such as help instructions), or (an alternate means of completing a form, such as a calendar-based date picker)

という構造なのでは…？

2021-12-24 09:40 UTC, momdo commented on techniques/general/G200.html
> +               <p>セキュアなウェブサイト内のあるウェブページにセキュアなセッション外にあるウェブページへのリンクがある。そのリンクを同じウィンドウで開くとセキュアなセッションが無効になってしまうため、新しいウィンドウまたはタブで開くようになっている。
```suggestion
               <p>セキュアなウェブサイト内のあるウェブページにセキュアなセッション外にあるウェブページへのリンクがある。そのリンクを同じウィンドウで開くとセキュアなセッションが無効になってしまうため、新しいウィンドウ又はタブで開くようになっている。
```

2021-12-24 09:40 UTC, momdo commented on techniques/general/G200.html
> +               <p>オンラインフォームに日付のフィールドがあり、利用者は日付を入力するか、別ページのカレンダーを用いたデートピッカーから日付を選択することができるようになっている。すでに入力済みのフォームデータが失われないように、カレンダーを用いたデートピッカーへのリンクは新しいウィンドウまたはタブを開くようになっている。
```suggestion
               <p>オンラインフォームに日付のフィールドがあり、利用者は日付を入力するか、別ページのカレンダーを用いたデートピッカーから日付を選択することができるようになっている。すでに入力済みのフォームデータが失われないように、カレンダーを用いたデートピッカーへのリンクは新しいウィンドウ又はタブを開くようになっている。
```

2021-12-24 09:40 UTC, momdo commented on techniques/general/G200.html
> +               <p>各入力項目に対する状況に応じたヘルプをフォーム上で提供するには文字量が多すぎるため、別のウェブページで提供しているオンラインフォームがある。すでに入力済みのフォームデータが失われないように、状況に応じたヘルプへのリンクは新しいウィンドウまたはタブを開くようになっている。
```suggestion
               <p>各入力項目に対する状況に応じたヘルプをフォーム上で提供するには文字量が多すぎるため、別のウェブページで提供しているオンラインフォームがある。すでに入力済みのフォームデータが失われないように、状況に応じたヘルプへのリンクは新しいウィンドウ又はタブを開くようになっている。
```

2022-01-13 08:19 UTC, caztcha commented on techniques/general/G200.html
> +            <p>この達成方法の目的は、ウェブコンテンツ内で新しいウィンドウまたはタブを開くリンクまたはボタンの使用を限定することである。一般的に、新しいウィンドウやタブを開かないほうがよい。なぜなら、特に視覚的なコンテンツを知覚するのに困難を伴う利用者をはじめ、利用者にとっては混乱の原因となりうるからである。しかし、アクセシビリティの観点から、新しいウィンドウやタブを開くことが望ま
修正提案ありがとうございます。

> ウェブコンテンツ内で新しいウィンドウ又はタブを開くリンクまたはボタンの使用を限定することである。

...の「リンク**または**ボタン」も含め、別途修正します。

2022-01-13 08:47 UTC, caztcha commented on techniques/general/G200.html
> +               <li>例えば、ヘルプの説明文またはカレンダーを用いたデートピッカー (日付選択) のようなフォーム入力の代替手段のように、状況に応じた情報を含むウェブページを開く際に、もしそういったウェブページが同じウィンドウやタブで開かれるとしたら、フォームを入力したり送信したりするような複数のステップから成るワークフローを著しく中断させることになる。
そのとおりですね。翻訳修正します。

2022-01-13 08:50 UTC, caztcha commented
@momdo レビューありがとうございます。いただいたコメント https://github.com/waic/wcag21/pull/1261#discussion_r774949632
https://github.com/waic/wcag21/pull/1261#discussion_r774951309
について、コミット 6b30ca0 にて修正対応しました。

2022-01-22 10:09 UTC, momdo approved these changes
@caztcha 
修正ありがとうございます。問題なさそうなのでマージします。

2022-01-22 10:10 UTC, merged