達成方法集 G199の翻訳
waic/wcag21 pull request #1263
Opened 2021-12-16 01:23 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-16 01:23 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:44 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。2点コメントしましたのでご確認ください。

2021-12-24 09:44 UTC, momdo commented on techniques/general/G199.html
> +            <p>アクションを確認するために、情報に目を通すことが容易ではない利用者の大きな手間が費やされる時がある (例えば、データベースにデータが正常に送信されたか、人に送られたのか、または編集されているコンテンツに追加されたのか)。
例示ですので、「または」を除いてみました。
```suggestion
            <p>アクションを確認するために、情報に目を通すことが容易ではない利用者の大きな手間が費やされる時がある (例えば、データベースにデータが正常に送信された、人に送られた、編集されているコンテンツに追加された)。
```

2021-12-24 09:44 UTC, momdo commented on techniques/general/G199.html
> +               <li>利用者がクイズやテストを送信する。応答において、テストが正常に送信されたと知らせている。そのため、利用者は送信が正常に行われたかを確認するために、送信されたテストのリストなどを探し回る必要がない。
```suggestion
               <li>利用者がクイズ又はテストを送信する。応答において、テストが正常に送信されたと知らせている。そのため、利用者は送信が正常に行われたかを確認するために、送信されたテストのリストなどを探し回る必要がない。
```

2022-01-13 08:55 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットしました。よろしければマージいただけますと幸いです。

2022-01-22 10:11 UTC, merged