達成方法集 G198の翻訳
waic/wcag21 pull request #1264
Opened 2021-12-16 01:43 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-16 01:43 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:47 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしましたのでご確認ください。

2021-12-24 09:47 UTC, momdo commented on techniques/general/G198.html
> +            <p>制限時間を解除するメカニズム自体に制限時間が設けられておらず、またウェブページ全体の制限時間前に完了できるようにすることが非常に重要である。そのためには、さまざまな障害のある利用者がすばやく見つけて解除できるように、このメカニズムをページの上部又は上部近くで提供すべきである。
> 制限時間が設けられておらず、またウェブページ全体の制限時間前に

また、でよいですかね…？

2022-01-13 08:59 UTC, caztcha commented on techniques/general/G198.html
> +            <p>制限時間を解除するメカニズム自体に制限時間が設けられておらず、またウェブページ全体の制限時間前に完了できるようにすることが非常に重要である。そのためには、さまざまな障害のある利用者がすばやく見つけて解除できるように、このメカニズムをページの上部又は上部近くで提供すべきである。
原文では and なので、「かつ」ですね。別途修正します。

2022-01-13 09:03 UTC, caztcha commented
@momdo レビューありがとうございます。いただいたコメントについて、コミット 8cb8ba5 にて修正対応しました。

2022-01-22 10:13 UTC, momdo approved these changes
@caztcha 
確認ありがとうございます。マージします。

2022-01-22 10:13 UTC, merged