達成方法集 G192の翻訳
waic/wcag21 pull request #1270
Opened 2021-12-17 02:01 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-17 02:02 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2021-12-24 09:59 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点コメントしましたのでご確認ください。

2021-12-24 09:59 UTC, momdo commented on techniques/general/G192.html
> +      <title>G192: 仕様に完全に準拠する</title>
conform、準拠というより適合なのでは…？

2022-01-13 09:11 UTC, caztcha commented on techniques/general/G192.html
> +      <title>G192: 仕様に完全に準拠する</title>
そのとおりですね。別途修正します。

2022-01-13 09:14 UTC, caztcha commented
@momdo レビューありがとうございます。conform to の訳語、「準拠」→「適合」に修正しました。

また、念のため G192 のタイトルをリンクラベルとして使用しているページがないかを、/techniques/ フォルダ以下を対象にマルチファイル検索したところ、該当箇所はありませんでした。

2022-01-22 10:15 UTC, momdo approved these changes
@caztcha 
確認ありがとうございます。マージします。

2022-01-22 10:15 UTC, merged