G56の訳出
waic/wcag21 pull request #1275
Opened 2021-12-27 03:04 UTC by 8845musign

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-12-31 10:55 UTC, 8845musign commented on techniques/general/G56.html
> +            <p>この達成方法の目的は、聴覚に問題を持つ利用者が主音声を理解しづらくならないように、コンテンツ制作者が音声に背景音を入れられるようにすることである。前景にある主音声を背景音より 20 デジベル大きくすることで、その主音声は背景音よりも 4 倍大きいことになる。デシベル (dB) に関する情報は、<a href="http://trace.wisc.edu/docs/2
リンク切れを起こしているようです……。

2021-12-31 11:07 UTC, 8845musign commented
参考リソースとして記載されている、次の２ページはリンク切れを起こしています。

- [About Decibels] (http://trace.wisc.edu/docs/2004-About-dB/)
- [Audio creation / contrast tutorial](http://www.eramp.com/david/audio_contrast_general_techs.htm)

2021-12-31 11:09 UTC, 8845musign commented on techniques/general/G56.html
> +               <div class="note"><p class="prefix"><em>訳注: </em>音声が英語なので、和訳していない。</p></div>
不要でしたらご指示お願いいたします。

2021-12-31 11:10 UTC, 8845musign commented
@momdo レビューよろしくお願いいたします！

2022-01-09 07:06 UTC, momdo requested changes
@8845musign 作業ありがとうございます。
いくつかコメントしていますのでご確認ください。
リンク切れを起こしているものに関する対処はお任せしますが、訳注で補足しておくとよいと思います。

2022-01-09 07:06 UTC, momdo commented on techniques/general/G56.html
> +                  <a href="../../working-examples/audio-contrast/good-contrast.mp3">音声サンプル: 前景音声が背景音楽よりも 20 デシベル大きい (mp3 形式)</a>
```suggestion
                  <a href="https://www.w3.org/WAI/WCAG21/working-examples/audio-contrast/good-contrast.mp3">音声サンプル: 前景音声が背景音楽よりも 20 デシベル大きい (mp3 形式)</a>
```

2022-01-09 07:06 UTC, momdo commented on techniques/general/G56.html
> +               <div class="note"><p class="prefix"><em>訳注: </em>音声が英語なので、和訳していない。</p></div>
https://github.com/waic/wcag21/blob/master/work-step.md#%E8%A8%B3%E6%B3%A8%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
に従って、マークアップを書き換えてください。

2022-01-09 07:06 UTC, momdo commented on techniques/general/G56.html
>                    <a href="../../working-examples/audio-contrast/bad-contrast.mp3">Audio Example: Foreground is less than 20 decibels above the background (mp3)</a>
英語のままです

2022-01-09 07:06 UTC, momdo commented on techniques/general/G56.html
> +               <div class="note"><p class="prefix"><em>訳注: </em>音声が英語なので、和訳していない。</p></div>
こちらも訳注のマークアップを要変更

2022-01-26 19:24 UTC, 8845musign commented on techniques/general/G56.html
> +               <div class="note"><p class="prefix"><em>訳注: </em>音声が英語なので、和訳していない。</p></div>
対応いたしました

2022-01-26 19:44 UTC, 8845musign commented on techniques/general/G56.html
>                    <a href="../../working-examples/audio-contrast/bad-contrast.mp3">Audio Example: Foreground is less than 20 decibels above the background (mp3)</a>
失礼しました！　対応いたしました

2022-01-26 19:46 UTC, 8845musign commented
@momdo
対応に間が空き申し訳ありません。レビューありがとうございました。
ご指摘いただいた箇所は対応いたしました！

リンク切れしていた参考リソース、アーカイブのようなものがないか探してみました（そもそもサイトごと閉鎖しているようです）。
残念ながら見つからなかっため、「サイトがない」と記載しました。

2022-02-03 11:53 UTC, momdo approved these changes

2022-02-03 11:53 UTC, momdo commented
@8845musign 

遅くなりましたが、対応ありがとうございました。
問題なさそうなのでマージします。

2022-02-03 11:53 UTC, merged