SM14の訳出
waic/wcag21 pull request #1314
Opened 2022-02-16 16:18 UTC by 8845musign

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-04-07 03:34 UTC, 8845musign commented
@momdo 

訳出しました。
レビュー、よろしくお願いいたします。

2022-04-20 05:25 UTC, momdo requested changes
@8845musign 
作業ありがとうございます。問題ありませんでした。

※レビュー期間中のため、マージ待ちとします。

2022-04-20 05:27 UTC, momdo commented
@8845musign 
1つ忘れてました。index.html の翻訳もお願いします…！

2022-04-21 03:57 UTC, 8845musign commented
@momdo 
レビューありがとうございます。

> 1つ忘れてました。index.html の翻訳もお願いします…！

https://github.com/waic/wcag21/pull/1314/commits/2c7e10558932dec9d4c369a8e383620ee57f0f26

失礼しました。対応しました！

2022-04-26 00:01 UTC, momdo approved these changes

2022-04-26 00:01 UTC, merged