達成方法集 PDF22の翻訳
waic/wcag21 pull request #1335
Opened 2022-03-21 23:00 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-03-21 23:01 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
`figcaption` が未翻訳だったので、新規で翻訳しました。

2022-04-20 05:41 UTC, momdo requested changes
@caztcha 
いくつかコメントしましたのでご確認ください。

2022-04-20 05:41 UTC, momdo commented on techniques/pdf/PDF22.html
> +            <p>必須形式が使用されていない場合、エラーの性質について説明するテキストがアラートダイアログボックスで表示される。これは作成者が作成したスクリプトを通じて指定できる (例えば、「<a href="../client-side-script/SCR18">SCR18: クライアントサイドのバリデーション及びアラートを提供する</a>」を参照のこと)。Adobe LiveC
かぎ括弧を取っておきますか。

```suggestion
            <p>必須形式が使用されていない場合、エラーの性質について説明するテキストがアラートダイアログボックスで表示される。これは作成者が作成したスクリプトを通じて指定できる (例えば、<a href="../client-side-script/SCR18">SCR18: クライアントサイドのバリデーション及びアラートを提供する</a>を参照のこと)。Adobe LiveCycle などのユーザエージェントでは、(以下の事例で説明されているように) 自動的にアラートを表示できる。
```

2022-04-20 05:41 UTC, momdo commented on techniques/pdf/PDF22.html
> +               <p>エラーが発生する可能性があることを利用者が認識することも重要である。この情報は、「日付 (MM/DD/YYYY)」のように、ラベルに組み込むことができる。「<a href="PDF10">PDF10: PDF 文書内のインタラクティブなフォームコントロールにラベルを付ける</a>」を参照のこと。
こちらも同じく
```suggestion
               <p>エラーが発生する可能性があることを利用者が認識することも重要である。この情報は、「日付 (MM/DD/YYYY)」のように、ラベルに組み込むことができる。<a href="PDF10">PDF10: PDF 文書内のインタラクティブなフォームコントロールにラベルを付ける</a>を参照のこと。
```

2022-04-20 05:41 UTC, momdo commented on techniques/pdf/PDF22.html
> +               <p>この事例は Adobe Acrobat Pro の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。 他のソフトウェアツールのリストについては、「<a href="#pdf_notes_acc-sup_files_applications">アクセシビリティがサポートされている PDF オーサリングツール</a>」を参照のこと。
これってTechniques for WCAG 2.0だと
<https://www.w3.org/TR/WCAG20-TECHS/pdf_notes.html#pdf_notes_acc-sup_files_applications>
なのですけど、2.1には見当たらないですね…

2022-04-20 06:43 UTC, caztcha commented
@momdo レビューありがとうございます。
「アクセシビリティがサポートされている PDF オーサリングツール」については、原文が以下のようにセンテンスが中途半端に略される形になっています。

>  See the list of other software tools in (←ここでセンテンスがピリオドなしで終わっている。in の後に、空の `<a>` 要素があります。)

センテンスの体をなしていないので、この「See the list of other software tools in」自体を日本語版から削除する、というのが現実的かな、と個人的には思います。
その場合、このセンテンスだけを削除するのか、同パラグラフ内にある手前のセンテンス（下記）も併せて削除するのか、判断に迷うところです。

> This example is shown with Adobe Acrobat Pro. There are other software tools that perform similar functions.

> この事例は Adobe Acrobat Pro の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。

2022-04-20 07:30 UTC, momdo commented
https://www.w3.org/TR/WCAG20-TECHS/PDF22.html

> See the list of other software tools in ***PDF Authoring Tools that Provide Accessibility Support***.

というのがもともとの文だと思ってて、2.1で複写するときにリンクテキストがすっぽり抜けてしまった格好なのかなと。

リンクを修復よりかは、土屋さんの提案のように、センテンスごと削除するのが現実的かもしれませんね…。

2022-04-22 05:23 UTC, caztcha commented
1) なるべく原文に忠実にするのであれば、当該センテンス (原文の「See the list of other software tools in」) のみを削除する。
2) 意味的な不自然さを解消することも含めて対応するのであれば、パラグラグごと削除する。
... のどちらか、かなと思います。

2022-04-28 07:57 UTC, caztcha commented
2022-04-28 の WAIC WG4 での議論を受けて、翻訳は原文に忠実に行うこととし、そのうえで訳注を設ける、という結論になりましたので、以下のようにします。

> この事例は Adobe Acrobat Pro の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。 他のソフトウェアツールのリストについては、「」を参照のこと。 

> 訳注 :  上記「」に該当するリンク先は、WCAG 2.1 達成方法集の原文において存在しない。WCAG 2.0 達成方法集においては、[PDF テクノロジーノート](https://waic.jp/docs/WCAG-TECHS/pdf_notes.html)の中に「[アクセシビリティがサポートされている PDF オーサリングツール](https://waic.jp/docs/WCAG-TECHS/pdf_notes.html#pdf_notes_acc-sup_files_applications)」というセクションがある。

2022-04-28 08:14 UTC, caztcha commented
@momdo [WAIC WG4での議論](https://github.com/waic/wcag21/pull/1335#issuecomment-1111868009) を踏まえて、修正しました。[faa84bf](https://github.com/waic/wcag21/pull/1335/commits/faa84bfceaa17afe3a5f64347cf7f48ee1582da5)

特に問題なければ、他のPDF関連の達成方法にも適用していきます。

2022-04-29 01:33 UTC, momdo approved these changes
@caztcha 対応ありがとうございます…！これでいきましょう。

2022-04-29 01:33 UTC, merged