達成方法集 PDF21の翻訳
waic/wcag21 pull request #1336
Opened 2022-03-22 22:24 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-03-22 22:25 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
`figcaption` が未翻訳だったので、新規で翻訳しました。

2022-04-20 05:48 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。

「アクセシビリティがサポートされている PDF オーサリングツール」へのリンク どうしましょうか…

2022-04-20 05:48 UTC, momdo commented on techniques/pdf/PDF21.html
> +               <p>この事例は Microsoft Word の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。 他のソフトウェアツールのリストについては、「<a href="#pdf_notes_acc-sup_files_applications">アクセシビリティがサポートされている PDF オーサリングツール</a>」を参照のこと。
アクセシビリティがサポートされている PDF オーサリングツール　へのリンク

2022-05-02 09:35 UTC, caztcha commented
@momdo 「アクセシビリティがサポートされている PDF オーサリングツール」について、 [8280ff1](https://github.com/waic/wcag21/pull/1336/commits/8280ff1de32b70c82ff088f8b34a6f7ad53792c2) にて訳注化しました。

2022-05-03 09:14 UTC, momdo approved these changes
@caztcha 追加作業ありがとうございます。問題なさそうなのでマージします。

2022-05-03 09:14 UTC, merged