Nagano pdf1 20220329
waic/wcag21 pull request #1345
Opened 2022-03-30 05:06 UTC by nagano-y-20181127

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-03-30 05:08 UTC, nagano-y-20181127 commented
PDF1の作業を実施しました。
ご確認のほど、よろしくお願いいたします。

2022-04-27 01:33 UTC, momdo requested changes
@nagano-y-20181127 
作業ありがとうございます。いくつか空のa要素が存在する箇所については保留とさせてください。

2022-04-27 01:33 UTC, momdo commented on techniques/pdf/PDF1.html
> +            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/non-text-content">達成基準 1.1.1: 非テキストコンテンツ</a></span>  (十分な達成方法) に関する達成方法である。
```suggestion
            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/non-text-content">達成基準 1.1.1: 非テキストコンテンツ</a></span> (十分な達成方法) に関する達成方法である。
```

2022-04-27 01:33 UTC, momdo commented on techniques/pdf/PDF1.html
> +               <p>この事例は Adobe Acrobat Pro の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。他のソフトウェアツールのリストを参照。<a href="#pdf_notes_acc-sup_files_applications"></a>.
（空の要素については保留）

2022-04-27 01:33 UTC, momdo commented on techniques/pdf/PDF1.html
> +               <p>この事例は Adobe Acrobat Pro の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。他のソフトウェアツールのリストを参照。<a href="#pdf_notes_acc-sup_files_applications"></a>.
（空の要素について保留）

2022-05-02 08:47 UTC, caztcha commented
おつかれさまです。
「事例」に出てくる空の `<a>` 要素の扱いについて、2022-04-28 の WG4 定例会で確認しました。
以下のように、お願いできますと幸いです。(他の PDF 関連の達成方法においても、同様です。)

- ●●●は、具体的なオーサリングツール名 (例 : Adobe Acrobat Pro) が入ります。
- 空の `<a>` 要素に該当する部分は、空の鉤括弧 (「」) で表現し、訳中で説明を加える、という形です。
- 訳注の div の `aria-level="3"` は、文脈に応じて適宜、レベルの値を変更いただければと思います。(基本的に「3」のママでよいかと思いますが。)

```
<p>この事例は ●●● の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。 他のソフトウェアツールのリストについては、「」を参照のこと。  </p>

<div class="note">
<div role="heading" class="note-title marker" aria-level="3">訳注:</div>
<div>
<p>上記「」に該当する記述が、WCAG 2.1 達成方法集の原文では削除されている。WCAG 2.0 達成方法集においては、<a href="https://waic.jp/docs/WCAG-TECHS/pdf_notes.html">PDF テクノロジーノート</a>の中に「<a href="https://waic.jp/docs/WCAG-TECHS/pdf_notes.html#pdf_notes_acc-sup_files_applications">アクセシビリティがサポートされている PDF オーサリングツール</a>」というセクションがある。</p>
</div>
</div>
```

2022-05-18 06:21 UTC, momdo approved these changes

2022-05-18 06:22 UTC, momdo commented
@nagano-y-20181127 
追加のコミットありがとうございます。マージします。

2022-05-18 06:22 UTC, merged