PDF2の作業をしました。
waic/wcag21 pull request #1346
Opened 2022-03-30 07:21 UTC by nagano-y-20181127

PDF2の作業をしました。
よろしくご確認ください。

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-05-02 08:49 UTC, caztcha commented
おつかれさまです。
「事例」に出てくる空の `<a>` 要素の扱いについて、2022-04-28 の WG4 定例会で確認しました。
以下のように、お願いできますと幸いです。(他の PDF 関連の達成方法においても、同様です。)

- ●●●は、具体的なオーサリングツール名 (例 : Adobe Acrobat Pro) が入ります。
- 空の `<a>` 要素に該当する部分は、空の鉤括弧 (「」) で表現し、訳中で説明を加える、という形です。
- 訳注の div の `aria-level="3"` は、文脈に応じて適宜、レベルの値を変更いただければと思います。(基本的に「3」のママでよいかと思いますが。)

```
<p>この事例は ●●● の場合を示している。同様の機能を実行するソフトウェアツールは他にも存在する。 他のソフトウェアツールのリストについては、「」を参照のこと。  </p>

<div class="note">
<div role="heading" class="note-title marker" aria-level="3">訳注:</div>
<div>
<p>上記「」に該当する記述が、WCAG 2.1 達成方法集の原文では削除されている。WCAG 2.0 達成方法集においては、<a href="https://waic.jp/docs/WCAG-TECHS/pdf_notes.html">PDF テクノロジーノート</a>の中に「<a href="https://waic.jp/docs/WCAG-TECHS/pdf_notes.html#pdf_notes_acc-sup_files_applications">アクセシビリティがサポートされている PDF オーサリングツール</a>」というセクションがある。</p>
</div>
</div>
```

2022-05-03 09:37 UTC, momdo requested changes
@nagano-y-20181127 作業ありがとうございます。
いくつかコメントしましたので、あわせて確認ください。

2022-05-03 09:37 UTC, momdo commented on techniques/pdf/PDF2.html
> +                        <figcaption>図1. [目次] ツールが表示されたWordリボンの [参照] タブ</figcaption>
```suggestion
                        <figcaption>図1. [目次] ツールが表示された Word リボンの [参照] タブ</figcaption>
```

2022-05-03 09:37 UTC, momdo commented on techniques/pdf/PDF2.html
> +               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/PDF2/bookmarks.docx">working example of creating bookmarks with Word 2007</a> でしおりを
```suggestion
               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG21/working-examples/pdf-bookmarks/bookmarks.docx">working example of creating bookmarks with Word 2007</a> でしおりを作成するサンプル (Word ファイル) がある。
```

2022-05-03 09:37 UTC, momdo commented on techniques/pdf/PDF2.html
> +               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/PDF2/bookmarks.odt">working example of creating bookmarks with OpenOffice Writer</a
```suggestion
               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG21/working-examples/pdf-bookmarks/bookmarks.odt">working example of creating bookmarks with OpenOffice Writer</a> でしおりを生成するサンプル (Open Document Text ファイル) がある。
```

2022-05-03 09:37 UTC, momdo commented on techniques/pdf/PDF2.html
> +               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG20/Techniques/working-examples/PDF2/bookmarks.pdf">working example of creating bookmarks with Acrobat Pro</a> で作成し
```suggestion
               <p class="working-example">この事例には、<a href="https://www.w3.org/WAI/WCAG21/working-examples/pdf-bookmarks/bookmarks.pdf">working example of creating bookmarks with Acrobat Pro</a> で作成したしおりのサンプル (PDF ファイル) がある。
```

2022-05-03 09:37 UTC, momdo commented on techniques/pdf/PDF2.html
> +               <li><a href="https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G64.html">G64: 目次を提供する</a></li>
```suggestion
               <li><a href="../general/G64">G64: 目次を提供する</a></li>
```

2022-05-18 06:26 UTC, momdo approved these changes
@nagano-y-20181127 
追加コミットありがとうございます。1点こちらで調整してマージします。

2022-05-18 06:26 UTC, momdo commented on techniques/pdf/PDF2.html
> +                        <figcaption>図1. [目次] ツールが表示された Wordリボンの [参照] タブ</figcaption>
```suggestion
                        <figcaption>図1. [目次] ツールが表示された Word リボンの [参照] タブ</figcaption>
```

2022-05-18 06:26 UTC, merged