達成方法集 PDF12の翻訳
waic/wcag21 pull request #1351
Opened 2022-04-06 09:44 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-04-06 09:45 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
`figcaption` が未翻訳だったので、新規で翻訳しました。

2022-05-03 09:59 UTC, momdo requested changes
@caztcha 作業ありがとうございます。2箇所コメントしましたのでご確認ください。

2022-05-03 09:59 UTC, momdo commented on techniques/pdf/PDF12.html
> +             <table id="PDF12_spec" border="1"><tbody><tr><th scope="col">インタラクティブなフォーム辞書エントリ</th><th scope="col">定義する項目</th><th scope="col">コメント</th></tr><tr><th scope="row">FT</th><td>役割 (role)</td
少なくとも`border="1"`は存在しないので削除頂ければと。あとは多分もとのHTMLコードと一致しているでしょう…。

2022-05-03 09:59 UTC, momdo commented on techniques/pdf/PDF12.html
> +            <table id="PDF12_acrobat" border="1"><tbody><tr valign="top"><th>PDF フォームエレメント</th><th>役割 (FT エントリ)</th><th>名前 (name) (TU エントリ)</th><th>値 (V エントリ)</th><th>設定可能な状態</th></tr><tr valign="top
こちらも`border="1"`をトリで

2022-06-09 05:49 UTC, caztcha commented
@momdo レビューありがとうございます。テーブルの `border="1"` をトリました。

2022-06-09 11:06 UTC, momdo approved these changes

2022-06-09 11:08 UTC, momdo commented
@caztcha 
追加作業ありがとうございます。確認しましたのでマージします。

2022-06-09 11:08 UTC, merged