達成方法集 PDF10の翻訳
waic/wcag21 pull request #1356
Opened 2022-04-11 04:46 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-04-11 04:47 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。
`figcaption` が未翻訳だったので、新規で翻訳しました。

2022-05-03 10:04 UTC, momdo requested changes
@caztcha 作業ありがとうございます。1点確認してください。

2022-05-03 10:04 UTC, momdo commented on techniques/pdf/PDF10.html
> +               <table id="PDF10_placement-rules_table" border="1">
`border="1"`をトリで

2022-06-09 05:43 UTC, caztcha commented
@momdo レビューありがとうございます。`テーブルの border="1"` をトリました。

2022-06-09 11:08 UTC, momdo approved these changes

2022-06-09 11:08 UTC, momdo commented
@caztcha 
追加作業ありがとうございます。確認しましたのでマージします。

2022-06-09 11:09 UTC, merged