達成方法集 SM1の翻訳
waic/wcag21 pull request #1365
Opened 2022-04-18 02:55 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2022-04-18 02:56 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0 と 2.1 との間で、特に差分はありませんでした。

2022-04-26 00:28 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。1点細かいコメントをしました。

2022-04-26 00:28 UTC, momdo commented on techniques/smil/SM1.html
> +</pre><p>上記のマークアップは、五つの &lt;par&gt; セグメントに分割されている。各セグメントに &lt;video&gt; と &lt;audio&gt; のタグが一つずつある (ただし、最後の &lt;par&gt; に &lt;audio&gt; がないのは意図的なものである)。拡張音声解説の通常の使い方は、音声解説が提供される間、メインのメディアを一時停止するというもの
> fill=「freeze」

これはfill="freeze"であるべきなのかなと。

2022-04-26 07:30 UTC, caztcha commented on techniques/smil/SM1.html
> +</pre><p>上記のマークアップは、五つの &lt;par&gt; セグメントに分割されている。各セグメントに &lt;video&gt; と &lt;audio&gt; のタグが一つずつある (ただし、最後の &lt;par&gt; に &lt;audio&gt; がないのは意図的なものである)。拡張音声解説の通常の使い方は、音声解説が提供される間、メインのメディアを一時停止するというもの
そのとおりですね！修正いたします。

2022-04-26 07:36 UTC, caztcha commented
@momdo レビューありがとうございました。
[ご指摘の、fill=「freeze」の件](https://github.com/waic/wcag21/pull/1365#discussion_r858123158)、 [ab2ddc1](https://github.com/waic/wcag21/pull/1365/commits/ab2ddc15e4b052d9cc3304ceb6491cd3ff27b045) にて修正しました。

2022-04-27 00:49 UTC, momdo approved these changes

2022-04-27 00:49 UTC, momdo commented
@caztcha 修正ありがとうございます。確認できたのでマージします。

2022-04-27 00:49 UTC, merged