用語集：一般閃光閾値及び赤色閃光閾値の見直し
waic/wcag21 pull request #1541
Opened 2022-12-23 09:19 UTC by momdo

Close #1390

「彩度の高い赤色を含む相反する遷移の組合せ」を直すだけのつもりだったのですが、訳文に不満が出てきてしまったので、全体的に見直してみました。

これでよければ、解説書も更新します。

2023-01-26 07:00 UTC, bakera requested changes
ひとまず一点だけコメントしておきます。

2023-01-26 07:03 UTC, momdo commented
一度持ち帰って確認いただく。

2023-01-27 05:43 UTC, bakera reviewed
少し気になった点をコメントしました。

2023-01-27 05:43 UTC, bakera commented on guidelines/index.html
> +      <li><strong>一般閃光</strong>は、暗い映像の<a href="#dfn-relative-luminance" class="internalDFN" data-link-type="dfn">相対輝度</a>が 0.80 未満である、最大相対輝度の 10％以上の相対輝度の相反する変化の組合せとして定義される。ここでいう「相反する変化の組合せ」とは、増加した後に減
「暗い映像」だと "dark image" のように読めますが、ここでの原文は "the darker image" で、ここでとりあげている画像群のうち相対的に暗いほう、という意味です。「暗いほうの映像」くらいのほうが良いかもしれません。

2023-01-27 05:43 UTC, bakera commented on guidelines/index.html
> +   <div class="note" id="issue-container-generatedID-83"><div role="heading" class="note-title marker" id="h-note-83" aria-level="3"><span>注記</span></div><p class="">一般的なソフトウェア又はウェブコンテンツの場合、コンテンツを 10
「推定値を得られる」となっていますが、ここでは数値などが得られるわけではないように思います。
原文は estimate (using ... rectangle ... will provide a good estimate) で訳し方が難しいですが……。たとえば「矩形を使用すると...視野 10 度の適切な見積もりとなる」というくらいではどうでしょうか? (もっと良い訳がありそうな気もしますが)

2023-01-29 03:43 UTC, momdo commented on guidelines/index.html
> +      <li>典型的な閲覧距離で、同時に発生する閃光の領域の合計が、画面上のどの視野 10 度 (画面上の視野 10 度の 25％) 内で、合計 0.006 ステラジアン よりも多くを占めていない。
なるほど。括弧を元の位置に戻します。

2023-01-29 03:44 UTC, momdo commented on guidelines/index.html
> +      <li><strong>一般閃光</strong>は、暗い映像の<a href="#dfn-relative-luminance" class="internalDFN" data-link-type="dfn">相対輝度</a>が 0.80 未満である、最大相対輝度の 10％以上の相対輝度の相反する変化の組合せとして定義される。ここでいう「相反する変化の組合せ」とは、増加した後に減
「暗いほうの映像」とします。

2023-01-29 03:56 UTC, momdo commented on guidelines/index.html
> +   <div class="note" id="issue-container-generatedID-83"><div role="heading" class="note-title marker" id="h-note-83" aria-level="3"><span>注記</span></div><p class="">一般的なソフトウェア又はウェブコンテンツの場合、コンテンツを 10
「矩形を使用すると...視野 10 度の適切な見積もりとなる」よりもよい訳がパッとは出てきませんので、これでいきますか。

2023-01-29 03:58 UTC, momdo commented
@bakera 
レビューコメントを反映してみました。いかがでしょう？
問題なければ、解説書に展開します。

2023-02-16 08:45 UTC, bakera commented
良さそうな感じがします!

2023-02-16 13:26 UTC, momdo commented
@bakera

解説書に反映しました。問題なければマージしていただければと思います。

2023-02-17 08:56 UTC, bakera approved these changes
ありがとうございます。よさそうです。

2023-02-17 08:56 UTC, merged