用語集：必要不可欠の修正
waic/wcag21 pull request #1572
Opened 2023-01-22 09:24 UTC by momdo

related #98

orを「又は」とした。
特に問題なければ、解説書にも展開します。

2023-01-26 07:16 UTC, bakera requested changes

2023-01-26 07:16 UTC, bakera commented on guidelines/index.html
> +   <p>もし取り除いてしまうと、コンテンツの情報又はは機能を根本的に変えてしまい、<strong>かつ</strong>、適合する他の方法では情報及び機能を実現できない。
「は」が重複しているようです。
```suggestion
   <p>もし取り除いてしまうと、コンテンツの情報又は機能を根本的に変えてしまい、<strong>かつ</strong>、適合する他の方法では情報及び機能を実現できない。
```

2023-01-28 03:04 UTC, momdo commented
これで各解説書に展開していきます。

2023-02-10 03:29 UTC, momdo commented
@caztcha 

解説書に展開しましたので確認いただけますでしょうか。

2023-03-02 06:51 UTC, bakera approved these changes

2023-03-02 06:52 UTC, bakera approved these changes
よさそうです。

2023-03-02 06:52 UTC, merged