WCAG 2.1解説書（2022年9月版更新）：1.4.1: 色の使用
waic/wcag21 pull request #1574
Opened 2023-01-25 08:14 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-01-25 08:21 UTC, caztcha commented
`<h2>意図</h2>` の注記が増えているので、新たに訳出しています。これに伴い、以前からあった訳注の位置が、このままでよいのか (つまり、1つめの注記の後でよいのか？あるいはすべての注記の後にあるべきか？)、判断に迷うところです。
訳注の内容が、特に1つめの注記と密接に関係しているように見えないからです。

2023-01-26 07:22 UTC, caztcha commented
訳注は、`<h2>意図</h2>` の1段落目の直下に移す。 『ここで使用している「色覚異常」という用語は〜』という書き出しにする。

2023-01-26 08:28 UTC, caztcha commented
https://github.com/waic/wcag21/pull/1574#issuecomment-1404636634
の議論を反映する形で、[c01d040](https://github.com/waic/wcag21/pull/1574/commits/c01d04092384e8792b666faa83add7538c546db3) をコミットしました。

2023-01-28 04:25 UTC, momdo requested changes
@caztcha 

追加の翻訳等ありがとうございます。レビューコメントを付けましたのでご確認ください。

2023-01-28 04:25 UTC, momdo commented on understanding/use-of-color.html
> +                  <p>逆に、色の違いによって伝達される情報が適切に支援技術に伝達されるとしても、特定の色を識別できない目の見える利用者が必ずしも支援技術を使用しているとは限らないため、必ずしもこの達成基準を満たしているとは言えない。この達成基準は、色に代わる視覚的な代替を要求するものである。
even if

```suggestion
                  <p>逆に、たとえ色の違いによって伝達される情報が適切に支援技術に伝達されたとしても、特定の色を区別できない目の見える利用者が必ずしも支援技術を使用しているとは限らないため、必ずしもこの達成基準を満たしているとはいえない。この達成基準は、色に代わる視覚的な代替を要求するものである。
```

2023-01-28 04:25 UTC, momdo commented on understanding/use-of-color.html
> +               <li>色数の制限されたモノクロのディスプレイを使用している人は、色に依存している情報を知覚できないかもしれない。</li>
accessですから、「利用する」とでもしますか
```suggestion
               <li>色数の制限されたモノクロのディスプレイを使用している人は、色に依存している情報を利用できないことがある。</li>
```

2023-01-28 04:25 UTC, momdo commented on understanding/use-of-color.html
> +                  <p>ある入力フォームには、必須項目と任意項目の両方がある。入力フォームの先頭にある説明文では、必須項目のラベルが赤字になっていてアイコンも付いていることが説明されている。任意フィールドのラベルと必須フィールドの赤いラベルの違いを知覚できない利用者でも、赤いラベルに隣接するアイコンで視認することができる。</p>
topは先頭にはならないのでは…2文目は意訳っぽくしてみました。
fieldsは項目で統一してみました。

```suggestion
                  <p>ある入力フォームには、必須項目と任意項目の両方がある。入力フォームの上部にある説明文では、必須項目は赤字とアイコンで説明されている。任意項目のラベルと必須フィールドの赤いラベルの違いを知覚できない利用者でも、赤いラベルに隣接するアイコンで視認することができる。</p>
```

2023-01-28 04:25 UTC, momdo commented on understanding/use-of-color.html
> +				<p>学生は、化合物の SVG 画像を見て、図に使用されている色及び各元素に隣接する番号の<strong>両方</strong>に基づいて、存在する化学元素を識別する。凡例によって、元素の種類ごとの色及び番号が示されている。目が見えてもすべての色の違いを知覚できない利用者は、それでも番号を頼りに画像を理解することができる。</p>
元素の横の番号が示されている、化合物の図というのがピンときませんが…まあそう書いてるので仕方ないですね。

```suggestion
				<p>学生は、化合物の SVG 画像を見て、図に使用されている色及び各元素に隣接する番号の<strong>両方</strong>に基づいて、存在する化学元素を識別する。凡例によって、元素の種類ごとの色及び番号が示されている。目が見えてもすべての色の違いを知覚できない利用者でも、番号を頼りに画像を理解することができる。</p>
```

2023-01-31 07:51 UTC, caztcha commented on understanding/use-of-color.html
> +				<p>上記の「色覚異常」という用語は、<a href="https://jams.med.or.jp/dic/colorvision.html">日本医学会 医学用語辞典「色覚関連用語について」</a>に基づいて使用している。</p>
そのとおりですね！

2023-01-31 07:53 UTC, caztcha commented on understanding/use-of-color.html
> +                  <p>色相だけでなく明度も大きく異なる色を用いてコンテンツを伝える場合、色間の相対輝度の差が 3:1 のコントラスト比になるのであれば、これは追加の視覚的な区別としてカウントされる。例えば、明るい緑と暗い赤とでは、色（色相）と明度の<strong>両方</strong>が異なるが、コントラスト比が 3:1 以上あれば合格となる。同様に、要素の前景色と背景色を反
ありがとうございます。count as の訳語、自分の中でもすっきりしていなかったので、助かりました。so のニュアンスについても、異論ありません。

2023-01-31 07:54 UTC, caztcha commented on understanding/use-of-color.html
> +                  <p>しかしながら、特定の色を正確に知覚又は区別できる利用者の能力にコンテンツが依存している場合は、色間のコントラスト比に関わらず、追加の視覚的な標識が必要となる。例えば、輪郭線が緑なら有効、赤なら無効とわかるようになっているような場合である。</p>
ですね。むしろそのほうが読みやすく感じました。ありがとうございます。

2023-01-31 07:56 UTC, caztcha commented on understanding/use-of-color.html
> +					<p>この達成基準は、支援技術の利用者のニーズに直接対応するものではない。これは、一部の色を識別できない目の見える利用者が、コンテンツを理解できるようにすることを目的としている。支援技術の利用者に情報をどう伝達するかは、別の達成基準、例えば <a href="non-text-content.html">1.1.1 非テキストコンテンツ</a>、<a href="info-and-re
なるほどたしかに。むしろ「区別」のほうがよいですね。

2023-01-31 08:00 UTC, caztcha commented on understanding/use-of-color.html
> +                  <p>ある入力フォームには、必須項目と任意項目の両方がある。入力フォームの先頭にある説明文では、必須項目のラベルが赤字になっていてアイコンも付いていることが説明されている。任意フィールドのラベルと必須フィールドの赤いラベルの違いを知覚できない利用者でも、赤いラベルに隣接するアイコンで視認することができる。</p>
2文目の意訳、異論ありません。fields に対する訳語の揺れも、ご指摘ありがとうございます。

2023-01-31 08:02 UTC, caztcha commented
@momdo レビューありがとうございました。ひととおり、代替案を確認し、異論ありませんでしたので、commit suggestion しました。

2023-02-02 23:52 UTC, momdo approved these changes

2023-02-02 23:53 UTC, momdo commented
@caztcha 

確認ありがとうございます。マージします。

2023-02-02 23:53 UTC, merged