WCAG 2.1解説書（2022年9月版更新）：1.4.4: テキストのサイズ変更
waic/wcag21 pull request #1640
Opened 2023-03-07 06:25 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-03-12 01:27 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。
`<section id="test-rules">`の箇所が抜けているようですのでご確認ください。

2023-03-15 08:14 UTC, caztcha commented
@momdo レビューありがとうございます。
`<section id="test-rules">` ですが、原文では、`<h3>Failures</h3>` と `<h2>Key Terms</h2>` の間に、存在しないのですよね...
https://www.w3.org/WAI/WCAG21/Understanding/resize-text

原文の更新日付が、Updated 24 December 2022. とあるので、9月2日版から12月24日版にアップデートされたところで、削除されたのかもしれません。どうしましょうかね...。

2023-03-18 01:04 UTC, momdo commented
@caztcha 

確認ありがとうございます。確かに今のUnderstanding WCAG 2.1にはないですね…

ただ、今時点でのUnderstanding WCAG 2.2には（末尾に移動していますが）存在しているので、
https://www.w3.org/WAI/WCAG22/Understanding/resize-text
この2.1の版の底本どおりに翻訳してもらうのがよいのかなと思います。

2023-03-18 02:16 UTC, caztcha commented
@momdo さん、ありがとうございます。
Understanding WCAG 2.2 はチェックしていませんでした...。なるほど、それでしたら、翻訳すべきですね。対応します。

2023-03-23 04:57 UTC, caztcha commented
@momdo さん、ご指摘いただいておりました `<section id="test-rules">` の訳を反映しました [e937658](https://github.com/waic/wcag21/pull/1640/commits/e9376587202c479dbdf7e1cf825aef4487068ce4)

ご確認いただけますと幸いです。

2023-03-23 12:09 UTC, momdo reviewed
@caztcha 
対応ありがとうございます。問題なさそうです。

2023-03-29 05:48 UTC, momdo approved these changes

2023-03-29 05:48 UTC, merged