WCAG 2.1解説書（2022年9月版更新）：1.4.10: リフロー
waic/wcag21 pull request #1665
Opened 2023-04-13 06:37 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-04-16 01:45 UTC, momdo requested changes
@caztcha 
作業ありがとうございます。
1点コメントしましたのでご確認ください。

2023-04-16 01:45 UTC, momdo commented on understanding/reflow.html
> +               <p>複雑なデータテーブルは、見出しとデータセルの間に 2 次元の関係がある。この関係性はコンテンツの意味を伝えるために不可欠である。したがって、この達成基準はデータテーブル全体には適用されず、それらに対して 2 次元スクロールを提供することは許容される。ただし、データテーブル内のセルは、用法又は意味のために 2 次元レイアウトを必要とする種類のコンテンツを含まない
ここのthemはデータテーブルですから、こうでしょうか

```suggestion
               <p>複雑なデータテーブルは、見出しとデータセルの間に 2 次元の関係がある。この関係性はコンテンツの意味を伝えるために不可欠である。したがって、この達成基準はデータテーブル全体には適用されず、データテーブルに対して 2 次元スクロールを提供することは許容される。ただし、データテーブル内のセルは、用法又は意味のために 2 次元レイアウトを必要とする種類のコンテンツを含まない限り、サイズ要件内に収まるべきである。</p>
```

2023-04-17 07:43 UTC, caztcha commented on understanding/reflow.html
> +               <p>複雑なデータテーブルは、見出しとデータセルの間に 2 次元の関係がある。この関係性はコンテンツの意味を伝えるために不可欠である。したがって、この達成基準はデータテーブル全体には適用されず、それらに対して 2 次元スクロールを提供することは許容される。ただし、データテーブル内のセルは、用法又は意味のために 2 次元レイアウトを必要とする種類のコンテンツを含まない
@momdo さん、レビューありがとうございます。おっしゃるように、them は「データテーブル」のことです。改善案の通り「データテーブルに対して」と書いたほうがすんなりと頭に入ってきそうですね。

2023-04-17 07:44 UTC, caztcha commented
@momdo さん、レビューありがとうございました。変更提案、確認しコミットしましたので、よろしくお願いいたします。

2023-04-20 13:17 UTC, momdo approved these changes

2023-04-20 13:18 UTC, momdo commented
@caztcha 
修正ありがとうございます。よいと思いますのでマージします。

2023-04-20 13:18 UTC, merged