WCAG 2.1解説書（2022年9月版更新）：1.4.11: 非テキストのコントラスト
waic/wcag21 pull request #1666
Opened 2023-04-13 07:49 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-04-13 07:56 UTC, caztcha commented
[G183](https://www.w3.org/WAI/WCAG21/Techniques/general/G183) のタイトルが

> Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on **hover** for links or controls where color alone is used to identify them

...になっている。

[日本語版の G183](https://waic.jp/docs/WCAG21/Techniques/general/G183) のタイトルは

> 色が単独でリンク又はコントロールを特定する場所で、周囲のテキストと一緒に 3:1 のコントラスト比を使用し、そのリンク又はコントロールの**フォーカス**に追加の視覚的な手がかりを提供する

...である。「フォーカス」は「ホバー」に変更？（G183の中身まで変更が入っているかは未確認。別 issue を立てるべきか？）

2023-04-14 07:17 UTC, caztcha commented
@momdo けっこう差分がありますが、レビューいただけますと幸いです...！

2023-04-16 03:39 UTC, momdo requested changes
@caztcha 

更新作業ありがとうございます（確かにボリュームありますね…）。

いくつかコメントをしました。また（該当箇所にコメントできなかったのでここでコメントすると、）次の`img`に（原文での変更どおりに）`width="150"`を追加してください。

```html
<img src="img/checkbox-example5.png" alt="フォーカス表示として太い灰色の追加のアウトラインがある未チェックのチェックボックス。" />
```

2023-04-16 03:39 UTC, momdo commented on understanding/non-text-contrast.html
> +                     						コントロールの境界線が青 (#4189B9) から緑 (#4B933A) に変化する。これはコンポーネント内のことであり、コンポーネント内側の背景色とのコントラストが十分でないため、非テキストのコントラストの達成基準の<strong>失敗</strong>となる。</figcaption>
> これはコンポーネント内のことであり、

コンポーネントの内側に存在することを言っているのではないかと

2023-04-16 03:39 UTC, momdo commented on understanding/non-text-contrast.html
> +                     						内側にある濃い緑 (#008000) の境界線は、黒い境界線との間でコントラストをもつが、コンポーネントの青い背景色とのコントラストが十分ないため、とは対照的でないため、非テキストのコントラストの達成基準の<strong>失敗</strong>となる。
> とは対照的でないため、

削除し忘れ？

2023-04-16 03:39 UTC, momdo commented on understanding/non-text-contrast.html
> +                  <p>グラフィックの中には、コントラストを変更したり、各グラフィカルオブジェクトにマウスオーバー／タップ／フォーカスをしたときに情報をテキストとして表示するインタラクションがあるかもしれない。人がグラフィックの存在を認識するには結局のところ、フォーカスされていないデフォルトのバージョンにおいて、あらかじめ色又はテキストのコントラストが十分でなければならない。フ
2文目：

- 「結局のところ」というのはどこから…？
- sufficiently contrasting colors or textは「十分なコントラストの色又はテキスト」としたほうが文の見通しがよくなるかもしれません。

3文目：

> フォーカスを受け取る部分

「フォーカスを受け取る領域」としたほうがよさそうです

> ポップアップテキストとして動的に情報を提供したり、コントラストを高めることで動的に前景化させたりすることができる。

どちらもinformationのことを（主語として）言っているのと、foregroundは「前景化」ではなく「…を目立たせる」（ウィズダム曰く）としましょう（そもそもテキストは前景のはず）。

「情報をポップアップテキストとして動的に提供したり、コントラストを高めることで動的に目立たせたりすることができる。」というのはどうでしょう。

2023-04-16 03:42 UTC, momdo commented
G183については、issueを立てておきました。

2023-04-17 08:14 UTC, caztcha commented on understanding/non-text-contrast.html
> +                     						内側にある濃い緑 (#008000) の境界線は、黒い境界線との間でコントラストをもつが、コンポーネントの青い背景色とのコントラストが十分ないため、とは対照的でないため、非テキストのコントラストの達成基準の<strong>失敗</strong>となる。
消し忘れでした...！

2023-04-17 08:41 UTC, caztcha commented on understanding/non-text-contrast.html
> +               <p>フォーカスインジケータが、コンポーネントの目に見える境界にある境界線を変更する場合、コンポーネントとの間でコントラストがついていなければならない。通常、アウトラインはコンポーネントの目に見える境界の周り (外側) を囲むが、この場合は、境界を変更するのはコンポーネントの目に見えるちょうど端である。</p>
ここでの inside ですが、原文は以下のようになっていて

> in this case changing the border is **just inside** the visible edge of the component.

visible edge の「ちょうど中」、つまり、辺の部分とぴったり重なるニュアンスかと思いました。なので、inside を「内側」と訳してしまうと誤解が生じるかと思い、「ちょうど辺の中」としてみました。

2023-04-17 08:50 UTC, caztcha commented on understanding/non-text-contrast.html
> +                  <p>グラフィックの中には、コントラストを変更したり、各グラフィカルオブジェクトにマウスオーバー／タップ／フォーカスをしたときに情報をテキストとして表示するインタラクションがあるかもしれない。人がグラフィックの存在を認識するには結局のところ、フォーカスされていないデフォルトのバージョンにおいて、あらかじめ色又はテキストのコントラストが十分でなければならない。フ
2文目の「結局のところ」は、「after all」を訳出したものです。

> In order for someone to discern the graphics **exist at all**, 

日本語として熟れていない感じは正直するのですが...

2023-04-18 07:17 UTC, caztcha commented
@momdo レビューありがとうございました。指摘いただいた事項、ひととおり修正しました。また、画像のアップロードも実施済です。度々お手数をおかけいたしますが、ご確認いただけますと幸いです。

2023-04-20 13:41 UTC, momdo commented on understanding/non-text-contrast.html
> +                  <p>グラフィックの中には、コントラストを変更したり、各グラフィカルオブジェクトにマウスオーバー／タップ／フォーカスをしたときに情報をテキストとして表示するインタラクションがあるかもしれない。人がグラフィックの存在を認識するには結局のところ、フォーカスされていないデフォルトのバージョンにおいて、あらかじめ色又はテキストのコントラストが十分でなければならない。フ
3文目はいただいた修正でよさそうです。

> 2文目の「結局のところ」は、「after all」を訳出したものです。

なるほど。これを活かすならば

「結局のところ人がグラフィックの存在を認識するには、」という語順のほうがまだすわりがよいかもしれませんがだうでしょうか？

2023-04-20 13:59 UTC, momdo commented
@caztcha 

修正ありがとうございます。確認しました。
2点コメントしましたので再度確認いただけるでしょうか。

2023-04-21 05:45 UTC, caztcha commented on understanding/non-text-contrast.html
> +                  <p>グラフィックの中には、コントラストを変更したり、各グラフィカルオブジェクトにマウスオーバー／タップ／フォーカスをしたときに情報をテキストとして表示するインタラクションがあるかもしれない。人がグラフィックの存在を認識するには結局のところ、フォーカスされていないデフォルトのバージョンにおいて、あらかじめ色又はテキストのコントラストが十分でなければならない。フ
> 「結局のところ人がグラフィックの存在を認識するには、」という語順のほうがまだすわりがよいかも

そうですね。よいと思います！

2023-04-21 05:48 UTC, caztcha commented on understanding/non-text-contrast.html
> +               <p>フォーカスインジケータが、コンポーネントの目に見える境界にある境界線を変更する場合、コンポーネントとの間でコントラストがついていなければならない。通常、アウトラインはコンポーネントの目に見える境界の周り (外側) を囲むが、この場合は、境界を変更するのはコンポーネントの目に見えるちょうど端である。</p>
なるほど、「コンポーネントの目に見える辺のすぐ内側」よさそうです。ありがとうございます！

2023-04-21 05:55 UTC, caztcha commented
@momdo レビューありがとうございます。コメントいただいた2件、改めて確認しましたが、いずれも、ご提案の訳文のほうがよかったので、[9cbb9af](https://github.com/waic/wcag21/pull/1666/commits/9cbb9af92822f4f15d2c0ec810bd373b5e8c7058) にて反映しました。

2023-04-22 06:31 UTC, momdo approved these changes
@caztcha 
ありがとうございます。コメント箇所の調整いただきましたのでマージします。

2023-04-22 06:31 UTC, merged