[WIP] WCAG 2.1解説書（2022年9月版更新）：2.3.1: 3 回の閃光、又は閾値以下
waic/wcag21 pull request #1694
Opened 2023-04-25 07:40 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-04-26 07:45 UTC, caztcha commented
@momdo 一部、差分により翻訳を追加したところがあります。お手数をおかけいたしますが、レビューよろしくお願いいたします。

2023-04-30 01:08 UTC, momdo requested changes
@caztcha 

作業ありがとうございます。
レビューしましたのでご確認ください。

2023-04-30 01:08 UTC, momdo commented on understanding/three-flashes-or-below-threshold.html
> +					この 75～85 ppi という解像度は、CSS 仕様の公称ピクセル解像度である 96 ppi よりも低いことが知られており、そのためより保守的である。高解像度のディスプレイで同じコンテンツのレンダリングを表示すると、より小さく安全な画像が得られるため、閾値の定義に用いられているのはより低い解像度のほうである。</p>
```suggestion
			この 75～85 ppi という解像度は、CSS 仕様の公称ピクセル解像度である 96 ppi よりも低く、したがってより保守的であると知られている。同じコンテンツのレンダリングを表示する高解像度のディスプレイは、より小さく安全な画像が得られるため、閾値値の定義に使用される解像度はより低くなる。</p>
```

2023-05-29 07:16 UTC, caztcha commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
失礼しました！追加します。

2023-05-29 07:49 UTC, caztcha commented
@momdo レビューありがとうございます。ご指摘内容を検討し、改めて修正しました。 [e4edae1](https://github.com/waic/wcag21/pull/1694/commits/e4edae1eacfd81429f428c2bd1207e9c1a6e828d)
ご確認いただけますと幸いです。

2023-05-29 09:09 UTC, momdo commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
@caztcha 

構造としてはこうなるのでは…？
((a video clip or animated image) of a series of strobe flashes), or close-ups of rapid-fire explosions.

2023-05-29 09:09 UTC, momdo commented
@caztcha 

対応ありがとうございます。1点追加でコメントしましたのでご確認いただけるでしょうか？

2023-05-29 09:21 UTC, caztcha commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
ありがとうございます。なるほど、私は以下のように解釈していました。
(a video clip or animated image) of (a series of strobe flashes, or close-ups of rapid-fire explosions).
でも「or close-ups of rapid-fire explosions」の前にカンマがあるので、もんどさんの解釈のほうが正しい気がしてきました。

> 例えばコンテンツには、ストロボの連続した閃光のビデオクリップ又はアニメーション画像、あるいは連射による爆発のクローズアップ、が含まれる可能性がある。

...ですかね。

2023-05-30 00:21 UTC, momdo commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
（少し書き直すと）
私の解釈では

連続するストロボの閃光の映像クリップもしくはアニメーション画像、または爆発のクローズアップ

土屋さんの解釈ですと、

連続するストロボの閃光又は連射による爆発のクローズアップのある、映像クリップ又はアニメーション画像

ですか。土屋さんの解釈でよい気がしてきましたね…。

2023-05-31 08:02 UTC, caztcha commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
@momdo レビューありがとうございます。いや、なかなか難しいですね。私の解釈が正しいとして、訳出のしかたは要改善かと思いますので、修正しました。 [d226f2c](https://github.com/waic/wcag21/pull/1694/commits/d226f2c3e3922e99fefa090c9334b83c5b58c887)

2023-06-01 09:46 UTC, momdo commented on understanding/three-flashes-or-below-threshold.html
> +            <p>閃光は、ディスプレイ、画像をレンダリングするコンピュータ、又はレンダリングされたコンテンツによって、発生する可能性がある。コンテンツ制作者には、最初の二つを制御することはできない。それらは、ディスプレイ及びコンピュータの設計及び速度によって対処される。この達成基準の意図は、コンテンツ自体が閃光閾値に違反する明滅を引き起こさないようにすることである。</p>
@caztcha 
ありがとうございます。よいと思います…！

2023-06-01 09:47 UTC, momdo commented
修正対応いただきましたのでマージします。

2023-06-01 09:47 UTC, merged