WCAG 2.1解説書（2022年9月版更新）：2.3.3: インタラクションによるアニメーション
waic/wcag21 pull request #1696
Opened 2023-04-28 04:54 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-04-28 04:56 UTC, caztcha commented
用語の「モーションアニメーション (motion animation)」のところで、原文の側に追加があるので、翻訳を加えました。

2023-04-28 06:57 UTC, momdo commented
@caztcha 

作業ありがとうございます。内容の詳細はこれから確認しますが、「重要な用語」の変更が入っているのですね…。
これは、解説書の他の達成基準には出てこないということでよいですかね？

2023-04-28 07:20 UTC, caztcha commented
@mondo ありがとうございます。

> 「重要な用語」の変更が入っているのですね…。
> これは、解説書の他の達成基準には出てこないということでよいですかね？

はい。対象となる用語「モーションアニメーション (motion animation)」は、幸い、この「達成基準 2.3.3: インタラクションによるアニメーションを理解する」のみです。

2023-04-29 05:21 UTC, momdo requested changes
@caztcha 

確認ありがとうございます。（とりあえずWCAG 2.2からやってきたというラベルを付けてはみましたが、役に立ちますかね…）

1点コメントをしました。よろしくお願いいたします。

2023-04-29 05:21 UTC, momdo commented on understanding/animation-from-interactions.html
> +                  <p xmlns="http://www.w3.org/1999/xhtml" class="example">例えば、別の場所に移動したりサイズが変わる要素はアニメーションしていると考えられる。推移せずに即座に表示される要素は、アニメーションを用いていない。モーションアニメーションには、知覚される要素のサイズ、形状、あるいは位置を変えないような、色、ぼかし又
ここでのorは「もしくは」とします
```suggestion
                  <p xmlns="http://www.w3.org/1999/xhtml" class="example">例えば、別の場所に移動したりサイズが変わる要素はアニメーションしていると考えられる。推移せずに即座に表示される要素は、アニメーションを用いていない。モーションアニメーションには、知覚される要素のサイズ、形状、もしくは位置を変えないような、色、ぼかし又は不透明度の変更は含まれない。
```

2023-05-25 08:17 UTC, momdo approved these changes
@caztcha 

確認ありがとうございます。マージします。

2023-05-25 08:18 UTC, merged