WCAG 2.1解説書（2022年9月版更新）：2.4.5: 複数の手段
waic/wcag21 pull request #1730
Opened 2023-06-01 07:32 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-01 07:33 UTC, caztcha commented
@momdo お手数ですが、レビューよろしくお願いいたします。

2023-06-01 09:32 UTC, momdo requested changes
@caztcha 
1点コメントしましたのでご確認ください。

2023-06-01 09:32 UTC, momdo commented on understanding/multiple-ways.html
> +               <li>認知機能に制約のある人は、理解が難しいかもしれない階層的なナビゲーションスキームを使用するよりも、検索機能を使用する方が簡単だと見出すかもしれない。</li>
```suggestion
               <li>認知機能に制約のある人は、理解が難しいかもしれない階層的なナビゲーションスキームを使用するよりも、検索機能を使用する方が簡単だと感じるかもしれない。</li>
```



> Individuals with cognitive limitations may find it easier to use search features than to use a hierarchical navigation scheme that may be difficult to understand.

https://eow.alc.co.jp/search?q=find+it+easier
find it easier to
～する方が楽だ［簡単だ］と思う［感じる］

2023-06-01 10:19 UTC, caztcha commented on understanding/multiple-ways.html
> +               <li>認知機能に制約のある人は、理解が難しいかもしれない階層的なナビゲーションスキームを使用するよりも、検索機能を使用する方が簡単だと見出すかもしれない。</li>
find の訳、「感じる」でよかったのですね。ありがとうございます。

2023-06-02 00:01 UTC, momdo approved these changes

2023-06-02 00:01 UTC, momdo commented
@caztcha 
修正ありがとうございます。問題ないのでマージします。

2023-06-02 00:01 UTC, merged