WCAG 2.1解説書（2022年9月版更新）：2.4.7: フォーカスの可視化
waic/wcag21 pull request #1732
Opened 2023-06-02 07:46 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-02 07:48 UTC, caztcha commented
@momdo お手数ですが、レビューよろしくお願いいたします。

2023-06-02 09:57 UTC, momdo requested changes
@caztcha 
ありがとうございます。1点コメントをしました。

2023-06-02 09:57 UTC, momdo commented on understanding/focus-visible.html
> +            <p>注記: キーボードのフォーカスインジケータは異なる形態をとることができる点に注意すべきである。</p>
```suggestion
            <p>キーボードのフォーカスインジケータは異なる形態をとることができる点に注意する。</p>
```

> Note that a keyboard focus indicator can take different forms.

なので、「注記:」というわけではないかなと。

2023-06-02 10:08 UTC, caztcha commented on understanding/focus-visible.html
> +            <p>注記: キーボードのフォーカスインジケータは異なる形態をとることができる点に注意すべきである。</p>
ホントですね。「注記:」は消します！

2023-06-03 03:59 UTC, momdo approved these changes

2023-06-03 03:59 UTC, merged

2023-06-03 04:00 UTC, momdo commented
@caztcha 
確認ありがとうございます。マージしました。