WCAG 2.1解説書（2022年9月版更新）：2.5.1: ポインタのジェスチャ
waic/wcag21 pull request #1737
Opened 2023-06-06 08:44 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-07 08:43 UTC, caztcha commented
@momdo お手数ですが、レビューをよろしくお願いいたします。
意図 (Intent) の中で、[達成基準 2.5.7: Dragging Movements](https://www.w3.org/WAI/WCAG22/Understanding/dragging.html) への言及が追加されていますが、WCAG 2.2 で追加される予定の達成基準のため、その旨、訳注を入れてみました。

2023-06-11 02:46 UTC, momdo requested changes
@caztcha 
いろいろと編集的にてを入れてみました。もしかしたらもとのママの方がよい箇所もあるかもしれません。それぞれご確認ください。

2023-06-14 08:01 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた修正提案、改めて原文と比較して確認しました。原文の細かいところまでケアいただき、ありがとうございます。いずれも、問題ないと思いますので修正提案を適用しました。

2023-06-14 23:34 UTC, momdo approved these changes

2023-06-14 23:34 UTC, merged

2023-06-14 23:34 UTC, momdo commented
@caztcha 
確認ありがとうございます。マージしました。