WCAG 2.1解説書（2022年9月版更新）：2.5.5: ターゲットのサイズ
waic/wcag21 pull request #1745
Opened 2023-06-15 07:52 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-15 07:57 UTC, caztcha commented
@momdo お手数ですが、レビューよろしくお願いいたします。

重要な用語 (Key Terms) で差分があったので修正しています。WCAG 2.1 から WCAG 2.2 へのアップデートで、WCAG の用語集の「pointer input (ポインタ入力)」と「target (ターゲット)」に若干の変更が加えられているようです。

2023-06-18 05:24 UTC, momdo requested changes
@caztcha 
ありがとうございます。2点コメントしました。

2023-06-18 05:24 UTC, momdo commented on understanding/target-size.html
> +                  <p xmlns="http://www.w3.org/1999/xhtml">マウス、ペン、タッチ接触のように、画面上の特定の (1 つ又は複数の) 地点を指すことができるデバイスからの入力。</p>
coordinateがどこかに行ってしまっているのと、ここは実は（達成基準の）ターゲットでよいのでは…？

```suggestion
                  <p xmlns="http://www.w3.org/1999/xhtml">マウス、ペン、タッチ接触のように、画面上の特定の (1 つ又は複数の) 座標をターゲットにできるデバイスからの入力。</p>
```

2023-06-18 05:24 UTC, momdo commented on understanding/target-size.html
> +                     <p>2 つ以上のターゲットが重なっている場合、重なっているターゲットが同じアクションを実行するか、同じページを開く場合を除いて、重なっているエリアを含めてターゲットのサイズを測定するべきでない。</p>
```suggestion
                     <p>2 つ以上のターゲットが重なっている場合、重なっているターゲットが同じアクションを実行する、又は同じページを開く場合を除いて、重なっているエリアを含めてターゲットのサイズを測定するべきでない。</p>
```

2023-06-19 05:34 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた修正提案、改めて原文を確認のうえ、適用しました。ありがとうございました。

2023-06-21 11:57 UTC, momdo approved these changes

2023-06-21 11:57 UTC, momdo commented
@caztcha 

対応ありがとうございます。マージします。

2023-06-21 11:57 UTC, merged