WCAG 2.1解説書（2022年9月版更新）：3.1.2: 一部分の言語
waic/wcag21 pull request #1749
Opened 2023-06-16 08:32 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-16 08:33 UTC, caztcha commented
@momdo お手数ですが、レビューをよろしくお願いいたします。

2023-06-16 15:54 UTC, momdo requested changes
@caztcha 
ありがとうございます。3箇所コメントしました。

2023-06-16 15:54 UTC, momdo commented on understanding/language-of-parts.html
> +						<li>複数の言語をサポートしている合成音声は、適切な発音で適切なアクセントのテキストを話すことができるようになる。言語の変化が示されていない場合、合成音声は、動作するデフォルトの言語として単語を読み上げるのに最善を尽くそうとする。したがって、自動車を表すフランス語の単語 &quot;<span lang="fr">voiture</span>&quot; は、デフォルトの言語として
どうというわけではないですが、文字参照を元に戻しておきます

```suggestion
						<li>複数の言語をサポートしている合成音声は、適切な発音で適切なアクセントのテキストを話すことができるようになる。言語の変化が示されていない場合、合成音声は、動作するデフォルトの言語として単語を読み上げるのに最善を尽くそうとする。したがって、自動車を表すフランス語の単語 "<span lang="fr">voiture</span>" は、デフォルトの言語として英語を用いている合成音声では "voyture" と発音されるだろう。</li>
```

2023-06-16 15:54 UTC, momdo commented on understanding/language-of-parts.html
> +						<p>文章中の &quot;He maintained that the DDR (German Democratic Republic) was just a &#39; <span lang="de">Treppenwitz der Weltgeschichte</span>&#39;,&quot; は、ドイツ語の一節 &#39;<span lang="de">Treppenwi
こちらも
```suggestion
						<p>文章中の "He maintained that the DDR (German Democratic Republic) was just a '<span lang="de">Treppenwitz der Weltgeschichte</span>'"は、ドイツ語の一節 '<span lang="de">Treppenwitz der Weltgeschichte</span>' がドイツ語であることが示されている。マークアップ言語に応じて、英語は、指定された箇所を除く文書全体の言語として示すこともできるし、段落レベルで示すこともできる。スクリーンリーダーがドイツ語の一節を読み上げる際は、その単語を正確に発音するために、英語からドイツ語に発音規則を変更する。</p>
```

2023-06-16 15:54 UTC, momdo commented on understanding/language-of-parts.html
> +                  <p>&quot;podcast&quot; は、次の引用 &quot;<span lang="fr">A l&#39;occasion de l&#39;exposition &quot;Energie eternelle. 1500 ans d&#39;art indien&quot;, le Palais des Beaux-Arts de Bruxel
原文を貼り付け直してみました
```suggestion
                  <p>"podcast" は、次の引用 "<span lang="fr">À l'occasion de l'exposition "Energie éternelle. 1500 ans d'art indien", le Palais des Beaux-Arts de Bruxelles a lancé son premier podcast. Vous pouvez télécharger ce podcast au format M4A et MP3</span>" の周囲にあるテキストの母国語の一部なので、言語の変更を示す必要はない。</p>
```

2023-06-19 05:38 UTC, caztcha commented
@momdo レビューありがとうございます。文字参照になっている箇所の修正提案、適用しました。また、フランス語の引用についても、フォロー頂き、ありがとうございました。

2023-06-21 11:58 UTC, momdo approved these changes

2023-06-21 11:58 UTC, momdo commented
@caztcha 
対応ありがとうございます。マージします。

2023-06-21 11:58 UTC, merged