WCAG 2.1解説書（2022年9月版更新）：3.1.5: 読解レベル
waic/wcag21 pull request #1754
Opened 2023-06-19 07:10 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-19 07:11 UTC, caztcha commented
@momdo お手数ですが、レビューをよろしくお願いいたします。

2023-06-21 12:15 UTC, momdo requested changes
@caztcha 

作業ありがとうございます。2点コメントしましたのでご確認ください。

2023-06-21 12:15 UTC, momdo commented on understanding/reading-level.html
> +               <li><a href="https://www.leesbaarnederlands.nl/">Leesbaar Nederlands</a> (&quot;Readable Dutch&quot;「読みやすいオランダ語」) では、読字障害のある人にとってアクセシブルな文書の書き方に関するガイドラインが提供されている。このガイドラインでは、言葉遣い、内容及びデザイ
```suggestion
               <li><a href="https://www.leesbaarnederlands.nl/"><span lang="nl">Leesbaar Nederlands</span></a> ("Readable Dutch"「読みやすいオランダ語」) では、読字障害のある人にとってアクセシブルな文書の書き方に関するガイドラインが提供されている。このガイドラインでは、言葉遣い、内容及びデザインについて示されている。</li>
```

2023-06-21 12:15 UTC, momdo commented on understanding/reading-level.html
> +               <li><a href="https://www.plainlanguage.gov/">米国政府の plain language ウェブサイト</a>では、法的な要件を含む米国政府の文書における平易な表現 (plain language) の使用に関する情報だけでなく、平易な表現に関する一般的情報も提供している。</li>
> 平易な表現

「表現」とするのは意訳ぎみか…？
別の箇所でlanguageは「言葉遣い」と訳している。

2023-06-22 04:14 UTC, caztcha commented on understanding/reading-level.html
> +               <li><a href="https://www.plainlanguage.gov/">米国政府の plain language ウェブサイト</a>では、法的な要件を含む米国政府の文書における平易な表現 (plain language) の使用に関する情報だけでなく、平易な表現に関する一般的情報も提供している。</li>
おっしゃるとおり、意訳がすぎる感じですね。「平易な言葉遣い」に修正します。

2023-06-22 04:27 UTC, caztcha commented
@momdo レビューありがとうございます。
https://github.com/waic/wcag21/pull/1754#discussion_r1236900298 に関して、plain language を「平易な表現」から「平易な言葉遣い」に変更しました。 [f5eaaef](https://github.com/waic/wcag21/pull/1754/commits/f5eaaef858ff366adee2d5d73a069334c73bd19f)
お手数ですが、ご確認いただけますと幸いです。

2023-06-22 06:01 UTC, momdo approved these changes

2023-06-22 06:02 UTC, momdo commented
@caztcha 

対応ありがとうございます…！マージします。

2023-06-22 06:02 UTC, merged