WCAG 2.1解説書（2022年9月版更新）：3.2.5: 要求による変化
waic/wcag21 pull request #1762
Opened 2023-06-21 02:58 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-21 02:59 UTC, caztcha commented
@momdo お手数ですが、レビューをよろしくお願いいたします。

2023-06-21 12:32 UTC, momdo requested changes
@caztcha 

ありがとうございます。1点コメントしましたのでご確認ください。

2023-06-21 12:32 UTC, momdo commented on understanding/change-on-request.html
> +                     <pこのガイドラインの適合範囲に含まれる対象となるウェブページとみなされるためには、リソースが「埋め込まれていない」リソースでなければならない。
HTMLが壊れているようです

2023-06-22 04:33 UTC, caztcha commented
@momdo レビューありがとうございます。HTML の修正をしました。[5bc3cb8](https://github.com/waic/wcag21/pull/1762/commits/5bc3cb87adc4836e1304ec4cd8439dfb100f0a30)

2023-06-22 06:02 UTC, momdo approved these changes

2023-06-22 06:29 UTC, momdo commented
@caztcha 

ありがとうございます。マージします。

2023-06-22 06:29 UTC, merged