WCAG 2.1解説書（2022年9月版更新）：3.3.2: ラベル又は説明
waic/wcag21 pull request #1776
Opened 2023-06-30 07:41 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2023-06-30 07:43 UTC, caztcha commented
@momdo お手数ですが、レビューをよろしくお願いいたします。

2023-06-30 09:56 UTC, momdo requested changes
@caztcha 
ありがとうございます。2点コメントしましたのでご確認ください。

2023-06-30 09:56 UTC, momdo commented on understanding/labels-or-instructions.html
> +            <p>この達成基準の目的は、期待される入力データが何なのかを利用者が知ることができるように、コンテンツ作成者にフォーム内のコントロールを特定する説明又はラベルを提示させることである。ラジオボタン、チェックボックス、コンボボックス、又は類似のコントロールで利用者に選択肢を提供する場合は、それぞれの選択肢に適切なラベルがあって、利用者が実際に何を選択しているかをわかるようにし
> ラジオボタン、チェックボックス、コンボボックス、又は類似のコントロールで利用者に選択肢を提供する場合は、それぞれの選択肢に適切なラベルがあって、利用者が実際に何を選択しているかをわかるようにしなければならない。

微妙に訳の取り方がおかしいような…

利用者に選択肢を提供するラジオボタン、チェックボックス、コンボボックス、又は類似のコントロールの場合、利用者が実際に何を選択しているかをわかるように、それぞれの選択肢に適切なラベルが存在しなければならない。

というような感じででしょうか…？

2023-06-30 09:56 UTC, momdo commented on understanding/labels-or-instructions.html
> +			<p>この達成基準は、データ入力に関連しないリンク又はその他のコントロール (展開／折りたたみウィジェットあるいは類似のインタラクティブなコンポーネントなど) には適用されない。</p>
「～など」があるとき、「又は」「もしくは」を使わないようにします
```suggestion
			<p>この達成基準は、データ入力に関連しないリンク又はその他のコントロール (展開／折りたたみウィジェット、類似のインタラクティブなコンポーネントなど) には適用されない。</p>
```

2023-07-11 06:36 UTC, caztcha commented on understanding/labels-or-instructions.html
> +            <p>この達成基準の目的は、期待される入力データが何なのかを利用者が知ることができるように、コンテンツ作成者にフォーム内のコントロールを特定する説明又はラベルを提示させることである。ラジオボタン、チェックボックス、コンボボックス、又は類似のコントロールで利用者に選択肢を提供する場合は、それぞれの選択肢に適切なラベルがあって、利用者が実際に何を選択しているかをわかるようにし
> In the case of radio buttons, checkboxes, comboboxes, or {similar controls that provide users with options}, 

ではなく

> In the case of {radio buttons, checkboxes, comboboxes, or similar controls} that provide users with options}, 

...というとらえかたですね。なるほどたしかに、そのほうがよさそうです。

2023-07-11 06:41 UTC, caztcha commented
@momdo [コメント](https://github.com/waic/wcag21/pull/1776#discussion_r1247683008)を受けての修正をしました。たびたびお手数ですが、ご確認いただけますと幸いです。 [5a52c6b](https://github.com/waic/wcag21/pull/1776/commits/5a52c6b6097bc9eb3ffe5a805ab8f479a91131b4)

2023-07-12 13:43 UTC, momdo approved these changes

2023-07-12 13:43 UTC, momdo commented
よさそうです！

2023-07-12 13:43 UTC, merged