[WIP] 達成方法集 F94 の翻訳
waic/wcag21 pull request #665
Opened 2020-10-12 04:29 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2020-10-12 09:22 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューよろしくお願いいたします。

2020-10-19 06:53 UTC, momdo requested changes
@caztcha 
遅くなりましたが、レビューしましたのでご確認ください。

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +      <title>F94: 達成基準 1.4.4 の失敗例 － サイズ変更のためのビューポート単位を誤って使用している
次の行に"text"が残っていますので、あわせて検討ください…

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +            <p>テキストやその他のコンテンツのサイズを増減する方法は様々あるが、ほとんどの方法は、テキストにビューポート単位が（一般的には CSS の <code>font-size</code> を介して）適用されていると、利用できない。ブラウザのコントロールを使用して画面表示を拡大したりテキストを調整したりしても機能しないだろう。CSS を完全にオーバーライドする方法のみが機能
```suggestion
            <p>テキスト及びその他のコンテンツのサイズを増減する方法は様々あるが、ほとんどの方法は、テキストにビューポート単位が（一般的には CSS の <code>font-size</code> を介して）適用されていると、利用できない。ブラウザのコントロールを使用して画面表示を拡大したりテキストを調整したりしても機能しないだろう。CSS を完全にオーバーライドする方法のみが機能するだろうが、その場合、レイアウトが崩れたりテキストが重なったりなど他の問題が発生する可能性がある。
```

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +               <p>以下のCSSとHTMLのスニペットでは、VWの単位を使ってテキストのサイズを設定している。</p><pre><code>/* CSS */
```suggestion
               <p>以下の CSS と HTMLの スニペットでは、VW の単位を使ってテキストのサイズを設定している。</p><pre><code>/* CSS */
```

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +            <p>この達成方法の目的は、テキストに<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/length">ビューポート単位</a>が使用されている場合、テキストのサイズ変更ができないという失敗を記すことである。これらの単位はビューポートに対して相対的なものであるため、画面を拡大したりテキストサイズを調整しても
MDNは日本語版に向けておきますか

```suggestion
            <p>この達成方法の目的は、テキストに<a href="https://developer.mozilla.org/ja/docs/Web/CSS/length">ビューポート単位</a>が使用されている場合、テキストのサイズ変更ができないという失敗を記すことである。これらの単位はビューポートに対して相対的なものであるため、画面を拡大したりテキストサイズを調整しても、サイズを変更することができない。
```

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +               <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/length">&lt;length&gt; - CSS: Cascading Style Sheets | <abbr title="Mozilla Development Network">MDN</abbr></a> <code>vh</
```suggestion
               <li><a href="https://developer.mozilla.org/ja/docs/Web/CSS/length">&lt;length&gt; - CSS: Cascading Style Sheets | <abbr title="Mozilla Development Network">MDN</abbr></a> <code>vh</code> 及び <code>vw</code> の単位についての説明が含まれている。
```

＃ わりとどうでもいいですが、MDNはもはや何かの略称ではなく単なるMDNなのでもにょりますね…。

2020-10-19 06:53 UTC, momdo commented on techniques/failures/F94.html
> +                  <li>手順 #5 が偽である場合、この失敗条件が適用され、コンテンツは達成基準 1.4.4 テキストのサイズ変更 を満たさないことになる。
```suggestion
                  <li>手順 #5 が偽である場合、この失敗条件が適用され、コンテンツは達成基準 1.4.4 テキストのサイズ変更を満たさないことになる。
```

2020-10-19 06:55 UTC, momdo commented
`/techniques/index.html` のF94のリンクテキストについてもあわせて更新いただければと思います。

2020-10-19 11:23 UTC, caztcha commented on techniques/failures/F94.html
> +      <title>F94: 達成基準 1.4.4 の失敗例 － サイズ変更のためのビューポート単位を誤って使用している
```suggestion
      <title>F94: 達成基準 1.4.4 の失敗例 － テキストのサイズ変更のためのビューポート単位を誤って使用している
```

2020-10-19 11:24 UTC, caztcha commented on techniques/failures/F94.html
> +      <title>F94: 達成基準 1.4.4 の失敗例 － サイズ変更のためのビューポート単位を誤って使用している
「text」の訳出漏れ、ご指摘ありがとうございます！

2020-10-19 11:30 UTC, caztcha commented on techniques/failures/F94.html
> +            <p>この達成方法の目的は、テキストに<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/length">ビューポート単位</a>が使用されている場合、テキストのサイズ変更ができないという失敗を記すことである。これらの単位はビューポートに対して相対的なものであるため、画面を拡大したりテキストサイズを調整しても
> MDNは日本語版に向けておきますか

そうですね。賛成です。（リンク先URLの修正、ありがとうございます。念のため、リンク先でページが開くことを確認しました。）

2020-10-19 11:31 UTC, caztcha commented on techniques/failures/F94.html
> +               <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/length">&lt;length&gt; - CSS: Cascading Style Sheets | <abbr title="Mozilla Development Network">MDN</abbr></a> <code>vh</
> MDNはもはや何かの略称ではなく単なるMDNなのでもにょりますね…。

(笑)

2020-10-19 11:42 UTC, caztcha commented
> `/techniques/index.html` のF94のリンクテキストについてもあわせて更新いただければと思います。

コミット a0c09c0 にて対応しました。

2020-10-19 11:45 UTC, caztcha commented
@momdo レビューありがとうございます。確認と修正、完了しました。お手数ですが、ご確認いただけますと幸いです。

2020-10-20 04:54 UTC, momdo approved these changes
@caztcha 
ご対応ありがとうざいます。問題ないことを確認したのでマージしますね。

2020-10-20 04:54 UTC, merged