F96の翻訳を行いました
waic/wcag21 pull request #671
Opened 2020-11-13 05:09 UTC by nagano-y-20181127

F96の翻訳を行いました。お手数をおかけいたしますが、ご確認のほど、よろしくお願いいたします。

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2020-11-13 05:10 UTC, nagano-y-20181127 commented
ご確認のほど、よろしくお願いいたします。

2020-11-25 14:49 UTC, momdo requested changes
@nagano-y-20181127 

遅くなりましたがざっくりレビューしました。一部コメントそのものを割愛している箇所があります。

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +      <title>F96: 達成基準 2.5.3 の失敗例 - "アクセシブルな名前 (accessible name)" が可視ラベルのテキストを含んでいない。</title>
```suggestion
      <title>F96: 達成基準 2.5.3 の失敗例 - アクセシブルな名前 (accessible name) が可視ラベルのテキストを含んでいない</title>
```
原文にはない約物は付けない方向で

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +      <h1>F96: 達成基準 2.5.3 の失敗例 - "アクセシブルな名前 (accessible name)" が可視ラベルのテキストを含んでいない。</h1>
```suggestion
      <h1>F96: 達成基準 2.5.3 の失敗例 - アクセシブルな名前 (accessible name) が可視ラベルのテキストを含んでいない</h1>
```

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>インタラクティブなコントロール (リンクやフォーム入力など) を含むすべてのテクノロジー。</p>
```suggestion
            <p>インタラクティブなコントロール (リンクやフォーム入力など) を含むすべての技術。</p>
```

ここで言うtechnologiesはWCAG用語集のそれになります https://waic.jp/docs/WCAG21/#dfn-technologies

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>この達成方法は、<span><a href="https://waic.jp/docs/WCAG21/Understanding/label-in-name">達成基準 2.5.3: 名前 (name) のラベル (不適合) </span>に関連する。</p>
```suggestion
            <p>この達成方法は、<span><a href="https://waic.jp/docs/WCAG21/Understanding/label-in-name">達成基準 2.5.3: 名前 (name) のラベル</span> (失敗) に関連する。</p>
```
適合とは書いてはいないので一応

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>この失敗例の目的は、コントロールの名前と、目に見えるラベルが異なっているために、音声入力のユーザーがコントロールの名前を正しく話せないという状況を説明することである。</p>
```suggestion
            <p>この失敗例の目的は、コントロールの名前と、目に見えるラベルが異なっているために、音声入力の利用者がコントロールの名前を正しく話せないという状況を説明することである。</p>
```

user 利用者

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>音声入力のユーザは、Webページを操作するとき、通常はコマンドの後に何らかの表示ラベル(ボタンやリンクの中のテキストや、入力欄にラベリングしてあるテキスト)への参照を続けて話す。（永野注: 日本語でも”コマンド→対象”の順で話すのかな？）表示されるラベルが、コントロールのアクセシブルな名前と一致しない場合、音声を使うユーザーは、そのコントロールを直接アクティブにでき
```suggestion
            <p>音声入力の利用者がウェブページを操作するとき、通常はコマンドの後に何らかの表示ラベル (ボタンやリンクの中のテキスト、入力欄にラベル付けしてあるテキスト) への参照を続けて話す。表示されるラベルが、コントロールのアクセシブルな名前 (accessible name) と一致しない場合、音声を使う利用者は、そのコントロールを直接アクティブにできないことがある。</p>
```

個人的なコメントは訳文に記載せず、issueのコメントに記載するなどしてください。「日本語でも”コマンド→対象”の順で話すのか」については私もよくわかっていません。

初出でない箇所も  (accessible name)  は付与します。

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>要素のラベルテキストを可視化するのではなく、それを超える方法がある。これは、視覚的な文脈を利用できない支援技術の利用者に、より多くの文脈を提供するためのアイデアである。たとえば、非表示でもアクセス可能なテキスト(例: 表示領域以外に配置したテキスト)の使用や、ラベルテキストを上書きするaria-label属性の使用、または、ページ上の1つ以上の文字列からラベルテキス
```suggestion
            <p>要素の可視ラベルテキストを超える達成方法がある。これは、視覚的なコンテキストを利用できない支援技術の利用者に、より多くのコンテキストを提供するためのアイデアである。例としては、非表示のアクセス可能なテキスト (例: 表示領域以外に配置したテキスト) の使用、ラベルテキストを上書きする aria-label 属性の使用、又はページ上の一つ以上の文字列からラベルテキストを作成する aria-labeledby 属性の使用がある。</p>
```

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +            <p>これらの方法を使用した結果、表示されているラベルの正確な文字列が、アクセシブルな名前に含まれない場合、音声を使うユーザはそのコントロールをアクティブにできない可能性があります。コントロールのアクセシブルな名前を計算する際の優先順位を決定するには、 <a href="https://www.w3.org/TR/accname/">「アクセス可能な名前と説明の計算」</
```suggestion
            <p>これらの達成方法の使用した結果、表示されているラベルの正確な文字列が、アクセシブルな名前 (accessible name) に含まれない場合、音声を使う利用者はそのコントロールをアクティブにできない可能性がある。コントロールのアクセシブルな名前 (accessible name) を計算する際の優先順位を決定するには、<a href="https://www.w3.org/TR/accname/">Accessible Name and Description Computation</a> アルゴリズムを参照のこと。</p>
```

なぜかですます調になっていますが…。また、英語の仕様をそのまま参照するので訳さずにおきます。

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +               <h3>失敗例1: 表示されているボタンのテキストと、aria-labelで指定されたアクセシブルな名前が一致しない</h3>
```suggestion
               <h3>失敗例 1: 表示されているボタンのテキストと、aria-label で指定されたアクセシブルな名前 (accessible name) が一致しない</h3>
```

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +               <p>検索ボタンのテキストは「OK」ですが、aria-label属性で提供されるアクセシブルな名前は、「このサイトで検索」です。</p>
```suggestion
               <p>検索ボタンのテキストは「Go」であるが、aria-label 属性で提供されるアクセシブルな名前 (accessible name) は、「find in this site」である。</p>
```
直後の行のレビューコメントを参照。

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +               <pre><code>&lt;button id="sitesearch" aria-label="このサイトで検索"&gt;OK&lt;/button&gt;</code></pre>
```suggestion
               <pre><code>&lt;button id="sitesearch" aria-label="Find in this site"&gt;Go&lt;/button&gt;</code></pre>
```

コード例は翻訳しません。例2と3についてもその方針で見直してください。

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +               <p>ラベルが表示されているすべてのコントロール (例えば、リンク テキスト、ボタン テキスト、プログラムでリンクされたラベル、テキストとリンクされた画像) について、次のことを確認します。</p>
```suggestion
               <p>ラベルが表示されているすべてのコントロール (例えば、リンクテキスト、ボタン テキスト、プログラムによるリンクされたラベル、テキストをもつリンクされた画像) について、次のことを確認する:</p>
```

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +                  <li>アクセシブルな名前が表示されているラベルと同じである。</li>
```suggestion
                  <li>アクセシブルな名前 (accessible name) が表示されているラベルと同じである。</li>
```

2020-11-25 14:49 UTC, momdo commented on techniques/failures/F96.html
> +                  <li>アクセシブルな名前に表示されているラベルと同じ文字列が含まれている。</li>
```suggestion
                  <li>アクセシブルな名前 (accessible name) に表示されているラベルと同じ文字列が含まれている。</li>
```

2020-12-11 03:01 UTC, nagano-y-20181127 commented
F96の修正を実施しました！

2020-12-20 06:47 UTC, momdo requested changes
@nagano-y-20181127 

いくつか修正されていない箇所があるようです。ご確認ください。

2020-12-20 06:47 UTC, momdo commented on techniques/failures/F96.html
> +            <p>音声入力の利用者は、Webページを操作するとき、通常はコマンドの後に何らかの表示ラベル(ボタンやリンクの中のテキストや、入力欄にラベリングしてあるテキスト)への参照を続けて話す。表示されるラベルが、コントロールのアクセシブルな名前 (accessible name) と一致しない場合、音声を使うユーザーは、そのコントロールを直接アクティブにできないことがある。</p
```suggestion
            <p>音声入力の利用者は、ウェブページを操作するとき、通常はコマンドの後に何らかの表示ラベル (ボタンやリンクの中のテキストや、入力欄にラベリングしてあるテキスト) への参照を続けて話す。表示されるラベルが、コントロールのアクセシブルな名前 (accessible name) と一致しない場合、音声を使う利用者は、そのコントロールを直接アクティブにできないことがある。</p>
```

2020-12-20 06:47 UTC, momdo commented on techniques/failures/F96.html
> +            <p>要素の可視ラベルテキストを超える達成方法がある。これは、視覚的なコンテキストを利用できない支援技術の利用者に、より多くのコンテキストを提供するためのアイデアである。例としては、非表示でもアクセス可能なテキスト(例: 表示領域以外に配置したテキスト)の使用、ラベルテキストを上書きするaria-label属性の使用、又はページ上の一つ以上の文字列からラベルテキストを作成
```suggestion
            <p>要素の可視ラベルテキストを超える達成方法がある。これは、視覚的なコンテキストを利用できない支援技術の利用者に、より多くのコンテキストを提供するためのアイデアである。例としては、非表示のアクセス可能なテキスト (例: 表示領域以外に配置したテキスト) の使用、ラベルテキストを上書きする aria-label 属性の使用、又はページ上の一つ以上の文字列からラベルテキストを作成する aria-labeledby 属性の使用がある。</p>
```

2020-12-20 06:47 UTC, momdo commented on techniques/failures/F96.html
> +               <h3>失敗例1: 表示されているボタンのテキストと、aria-labelで指定されたアクセシブルな名前 (accessible name) が一致しない</h3>
```suggestion
               <h3>失敗例1: 表示されているボタンのテキストと、aria-label で指定されたアクセシブルな名前 (accessible name) が一致しない</h3>
```

2020-12-20 06:47 UTC, momdo commented on techniques/failures/F96.html
> +               <p>検索ボタンのテキストは「Go」であるが、aria-label属性で提供されるアクセシブルな名前 (accessible name) は、「find in this site」です。</p>
```suggestion
               <p>検索ボタンのテキストは「Go」であるが、aria-label 属性で提供されるアクセシブルな名前 (accessible name) は、「find in this site」である。</p>
```

2020-12-20 06:47 UTC, momdo commented on techniques/failures/F96.html
> +               <p>ラベルが表示されているすべてのコントロール (例えば、リンク テキスト、ボタン テキスト、プログラムによりリンクされたラベル、テキストとをもつリンクされた画像) について、次のことを確認します。</p>
```suggestion
               <p>ラベルが表示されているすべてのコントロール (例えば、リンクテキスト、ボタンテキスト、プログラムによりリンクされたラベル、テキストをもつリンクされた画像) について、次のことを確認する:</p>
```

2020-12-21 13:04 UTC, momdo approved these changes

2020-12-21 13:05 UTC, momdo commented
@nagano-y-20181127 
こちらで反映し切れていなかった箇所について反映させました。

2020-12-21 13:05 UTC, merged