C38の翻訳
waic/wcag21 pull request #672
Opened 2020-11-14 13:54 UTC by cure-tomoki

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント
初contributionとなります🎉
至らぬ点が多々あるかと思いますが，ご確認の程よろしくお願いいたします．

fixes #641

2020-11-25 14:07 UTC, momdo requested changes
@cure-tomoki 

遅くなりましたがざっとレビューしましたのでご確認ください🙏

2020-11-25 14:07 UTC, momdo commented on techniques/css/C38.html
> +                  また、<code>select</code> のような内在的寸法を持つ要素がグリッドからはみ出るのをクロスブラウザ的に防ぐため <code>max-width</code> を指定している。
```suggestion
                  また、<code>select</code> のような置換要素は内在寸法を持つため、要素がグリッドからはみ出るのをクロスブラウザ的に防ぐため <code>max-width</code> を指定している。
```

まあHTML LS（わかりやすさのためにMDN）を見る限りC38の記述が胡散臭いことこの上ないですが、
https://developer.mozilla.org/ja/docs/Web/CSS/Replaced_element
いずれにせよreplaced elementsは置換要素と訳されることが多いと思います。

2020-11-25 14:07 UTC, momdo commented on techniques/css/C38.html
> +                  <li>コンテンツを 400% ズームが可能なユーザーエージェント上で、ビューポートサイズを 1280x1024 CSSピクセルに設定してウェブページを表示する。</li>
```suggestion
                  <li>コンテンツを 400% ズームが可能なユーザエージェント上で、ビューポートサイズを 1280x1024 CSSピクセルに設定してウェブページを表示する。</li>
```

面倒なことこの上ないルールですが、長音を省きます。

2020-11-30 00:50 UTC, cure-tomoki commented
@momdo ご確認ありがとうございます！
指摘していただいた部分を修正いたしましたので再度ご確認いただけると幸いです🙇‍♂️

2020-12-02 00:54 UTC, momdo commented on techniques/css/C38.html
> +               <li>ラベルと入力欄それぞれの width と max-width プロパティを設定することで、
コミットでは

> max-width プロパティを定義る

「す」が抜けてますね

2020-12-02 01:21 UTC, momdo commented
@cure-tomoki 

修正ありがとうございます。一箇所だけ誤字があったので、そこだけ修正ください。
あと、書き忘れていましたが、
https://github.com/waic/wcag21/blob/cure-techniques-c38-issue641/techniques/index.html
でC38のタイトルもあわせて日本語に置き換えてもらえればと思います。

よろしくお願いします。

2020-12-30 03:43 UTC, momdo approved these changes

2020-12-30 03:43 UTC, merged

2020-12-30 03:43 UTC, momdo commented
@cure-tomoki 

こちらで内容調整してマージしました。

2020-12-30 09:58 UTC, cure-tomoki commented
すみません，ありがとうございます🙇‍♂️