[WIP] 達成方法集 F100 の翻訳
waic/wcag21 pull request #673
Opened 2020-11-15 00:04 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

着手はじめました。まだ WIP です。

2020-11-15 09:25 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをよろしくお願いいたします。

2020-12-07 03:55 UTC, momdo requested changes
@caztcha 

お待たせしています。レビューはしましたのでご確認ください。

2020-12-07 03:55 UTC, momdo commented on techniques/failures/F100.html
> +            <p>これは、望ましくないと考えられるデバイスの向きが検出された場合に、コンテンツ制作者が、コンテンツすべての向きを変更する代わりに、利用者にデバイスの向きを変更するよう指示するメッセージを表示する、という失敗条件を記述するものである。
コンテンツ制作者が、（中略）メッセージを表示したときに起こる失敗条件を失敗条件を記述するものである。

みたいな感じでしょうか。

2020-12-07 03:55 UTC, momdo commented on techniques/failures/F100.html
> +            <p>利用者のデバイスの向きを検出して対応すること自体は問題ではない。コンテンツを一つの方向でのみ提供するというコンテンツ制作者の判断が、達成基準 1.3.4 表示の向き の要件を満たさないことになる。検出されたデバイスの向きに対して、利用者にデバイスを回転させるよう指示するメッセージを表示するだけでは、不適切である (根底にあるアクティビティに回転が必要不可欠でない場合
```suggestion
            <p>利用者のデバイスの向きを検出して対応すること自体は問題ではない。コンテンツを一つの方向でのみ提供するというコンテンツ制作者の判断が、達成基準 1.3.4 表示の向きの要件を満たさないことになる。検出されたデバイスの向きに対して、利用者にデバイスを回転させるよう指示するメッセージを表示するだけでは、不十分である (根底にあるアクティビティに回転が必要不可欠でない場合) 。達成基準を満たすためには、コンテンツ制作者が管理するコンテンツ全体の向きが変更される必要がある。
```

2020-12-07 03:55 UTC, momdo commented on techniques/failures/F100.html
> +            <p>コンテンツが横向きなのか縦向きなのかをデバイスが判断するには、様々な方法がある。その方法のひとつは、ビューポートの幅と高さのアスペクト比を見ることである。つまり、横幅が縦幅よりも小さいか大きいかを調べるということである。CSS メディア特性 <code>orientation</code> は、<code>height</code> の値が <code>width<
```suggestion
            <p>コンテンツが横向きなのか縦向きなのかをデバイスが判断するには、様々な方法がある。その方法の一つは、ビューポートの幅と高さのアスペクト比を調べることである。つまり、横幅が縦幅よりも小さいか大きいかを調べる。CSS メディア特性 <code>orientation</code> は、<code>height</code> の値が <code>width</code> の値と同じ又はそれ以上の場合、 <code>portrait</code> になる。それ以外の場合は、高さメディア特性の値が幅メディア特性の値以上であれば縦向きになる。それ以外の場合は、<code>orientation</code> は <code>landscape</code> になる。
```

2020-12-07 03:55 UTC, momdo commented on techniques/failures/F100.html
> +               <p>向きを <code>portrait</code> に変更すると、メッセージは消える。<code>portrait</code> プロパティがメディアクエリで定義されたビューポート空間と一致した場合、メッセージは消え、そうでない場合、メッセージが表示される。この例では、CSS のメディアクエリプロパティ <code>landscape</code> と <co
```suggestion
               <p>向きを <code>portrait</code> に変更すると、メッセージは消える。<code>portrait</code> プロパティがメディアクエリで定義されたビューポート空間と一致した場合、メッセージは消える。逆の場合も同様である。この例では、CSS のメディアクエリプロパティ <code>landscape</code> と <code>portrait</code> を使用している。
```

2020-12-07 03:55 UTC, momdo commented on techniques/failures/F100.html
> +                  <li>コンテンツの閲覧や操作に、縦向き又は横向きの表示が必要不可欠であるかどうかを確認する
```suggestion
                  <li>コンテンツの閲覧及び操作に、縦向き又は横向きの表示が必要不可欠であるかどうかを確認する。
```

2020-12-10 12:32 UTC, caztcha commented on techniques/failures/F100.html
> +            <p>これは、望ましくないと考えられるデバイスの向きが検出された場合に、コンテンツ制作者が、コンテンツすべての向きを変更する代わりに、利用者にデバイスの向きを変更するよう指示するメッセージを表示する、という失敗条件を記述するものである。
```suggestion
            <p>これは、望ましくないと考えられるデバイスの向きが検出された場合、コンテンツ制作者が、コンテンツすべての向きを変更する代わりに利用者にデバイスの向きを変更するよう指示するメッセージを表示したときに起こる、失敗条件を記述するものである。
```

2020-12-10 12:42 UTC, caztcha commented
@momdo レビューありがとうございました。
ひととおり確認し、提案をコミットしました。
一点、https://github.com/waic/wcag21/pull/673#discussion_r537205142 について、修正の提案をしましたので、再度レビューいただけますと幸いです。

あと、inxex.html の更新 (F100 のラベルを日本語に置き換え) も実施しました。
8aa1e27 です。

2020-12-20 06:49 UTC, momdo approved these changes

2020-12-20 06:49 UTC, momdo commented
@caztcha 

調整ありがとうございます。マージします！

2020-12-20 06:49 UTC, merged