[WIP ]達成方法集 F104 の翻訳
waic/wcag21 pull request #674
Opened 2020-11-16 11:24 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2020-11-17 12:45 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをよろしくお願いいたします。

2020-12-20 07:02 UTC, momdo requested changes
@caztcha 

激しくお待たせしていますが、レビューしました。

2020-12-20 07:02 UTC, momdo commented on techniques/failures/F104.html
> +                  <li>ユーザースタイルシート、ブックマークレット、拡張機能、又はアプリケーションを用いて、達成基準にリストされた値で、そのページの CSS を上書きする。
```suggestion
                  <li>ユーザスタイルシート、ブックマークレット、拡張機能、又はアプリケーションを用いて、達成基準に記載された値で、そのページの CSS を上書きする。
```

2020-12-20 07:02 UTC, momdo commented on techniques/failures/F104.html
> +                  <li>テキストの間隔が新しく変更されたことにより、コンテンツが切り取られたり、隠されたり、又は失われたりしていないかどうかを確認する。</li>
```suggestion
                  <li>テキストの間隔を新しく変更したことにより、コンテンツが切り取られたり、隠されたり、又は失われたりしていないかどうかを確認する。</li>
```

2020-12-22 13:30 UTC, caztcha commented
@momdo レビューありがとうございます。いただいた変更提案、いずれも問題ありませんのでコミットしました。
また、index.html も更新しました。
よろしければ、マージいただけますと幸いです。

2020-12-23 14:56 UTC, momdo approved these changes

2020-12-23 14:56 UTC, merged

2020-12-23 14:56 UTC, momdo commented
@caztcha 
作業ありがとうございました。マージしました。