Issue647 aria24
waic/wcag21 pull request #677
Opened 2020-11-25 15:30 UTC by kurome9

# プルリクエスト作成時の確認事項

- [X] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [X] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [X] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2020-12-20 06:37 UTC, momdo requested changes
@kurome9 

遅くなりましたが、レビューしました。

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +      <title>ARIA24: アイコンフォントを意味的に識別するために、 role="img" を使用する</title>
```suggestion
      <title>ARIA24: アイコンフォントを意味的に識別するために role="img" を使用する</title>
```
タイトルなので、読点は取ってしまいます。

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +      <h1>アイコンフォントを意味的に識別するために、 <code>role="img"</code> を使用する</h1>
```suggestion
      <h1>アイコンフォントを意味的に識別するために <code>role="img"</code> を使用する</h1>
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/info-and-relationships">達成基準  1.3.1: 情報及び関係性を理解する</a></span>  (十分な達成方法) に関する達成方法である。
```suggestion
            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/info-and-relationships">達成基準  1.3.1: 情報及び関係性を理解する</a></span> (十分な達成方法) に関する達成方法である。
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +            <p>この達成方法の目的は、アイコンにフォントファイルが使用されている要素を、意味的に識別する方法を示すことである。ユーザーがフォントファミリーを上書きすると、識別する手段がない限りそのアイコンは消える。つまり、アイコンフォントを一般的なフォント（テキスト）使用と区別する手段を提供する。
```suggestion
            <p>この達成方法の目的は、アイコンにフォントファイルが使用されている要素を、意味的に識別する方法を示すことである。利用者がフォントファミリーを上書きすると、識別する手段がない限りそのアイコンは消える。つまり、アイコンフォントを一般的なフォント（テキスト）の使用法と区別する手段を提供する。
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +            <p>一部の弱視の利用者は、テキストコンテンツを認識するために利用者用のスタイルシート、スクリプト、又は拡張機能を使いページ上のフォントを上書きする。しかし、お気に入りを示す星やリンク内のメールアイコンなど、意味のあるアイコンフォントは認識できる必要がある。
```suggestion
            <p>一部のロービジョンの利用者は、テキストコンテンツを認識するためにユーザスタイルシート、スクリプト、又は拡張機能を使いページ上のフォントを上書きする必要がある。しかし、お気に入りを示す星やリンク内のメールアイコンなど、意味のあるアイコンフォントは認識できる必要がある。
```

複合語利用者としなくてだいたい大丈夫です

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +            <p>重要なのは、コンテンツ製作者が <code>role="img"</code> を使用してアイコンフォントを意味的にマークアップすることである。これにより利用者の指定フォントへの変換は <code>role="img"</code> を除いて意味的に機能する。この結果、アイコンフォントは表示されたままである。
```suggestion
            <p>重要なのは、コンテンツ製作者が <code>role="img"</code> を使用してアイコンフォントを意味的にマークアップすることである。これにより利用者のフォント置換セレクターはそのセマンティックにフックして <code>role="img"</code> を除外できる。この結果、アイコンフォントは表示されたままとなる。
```

CSSのセレクターの話をしているので。

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +            <p>まず最初に、 CSS ファイル内で @font-face を用いてアイコンを指定する。
```suggestion
            <p>まず最初に、 CSS ファイルでアイコンのフォントを追加する。
```

原文に寄せてみました。

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +               <p>この例では星のアイコンがお気に入りを示すものとして使われる。インタラクティブではなく、又、利用者がCSSでフォントファミリーを上書きしても消えることはない。
```suggestion
               <p>この例では星のアイコンがお気に入りを示すものとして使われる。インタラクティブではなく、かつ、利用者がCSSでフォントファミリーを上書きしても消えることはない。
```

andなので

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +                  <h4>コンテンツ製作者のCSS</h4>
```suggestion
                  <h4>コンテンツ製作者の CSS</h4>
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +               <h3>事例 2: 2色を重ねた星のアイコンフォント</h3>
```suggestion
               <h3>事例 2: 2 色を重ねた星のアイコンフォント</h3>
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +               <p>この例では、異なる色のフォントを重ね合わせて2色の星のアイコンを作成する。このようにすると、星の半分までを示しているように見せることができる。これはインタラクティブではなく、利用者がCSSを介してフォントファミリーを上書きしても消えない。
```suggestion
               <p>この例では、異なる色のフォントを重ね合わせて 2 色の星のアイコンを作成する。このようにすると、星の半分までを示しているように見せることができる。これはインタラクティブではなく、利用者が CSS を介してフォントファミリーを上書きしても消えない。
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +               <p>この例では、メールのアイコンがリンク内にあり、テキストは表示されていない。利用者がフォントファミリーを上書きしても消えない。アイコンフォントは、支援技術（キーボード又はマウス）によって "リンク付き画像" および "電子メール" として識別されます。
```suggestion
               <p>この例では、メールのアイコンがリンク内にあり、テキストは表示されていない。利用者がフォントファミリーを上書きしても消えない。アイコンフォントは、支援技術（キーボード又はマウス）によって "リンク付き画像" および "電子メール" として識別される。
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +               <h3>実例 4: 表示テキストのあるセマンティック要素の一部として、複数のアイコンフォント</h3>
```suggestion
               <h3>実例 4: 表示テキストのあるセマンティック要素の一部としての複数のアイコンフォント</h3>
```

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +                  これは、アイコンがそれぞれの要素に含まれ、又、支援技術によってフォントアイコンが無視されるように属性 <code>aria-hidden="true"</code>  が使用されることで実現できる。
```suggestion
                  これは、アイコンがそれぞれの要素に含まれ、かつ、支援技術によってフォントアイコンが無視されるように属性 <code>aria-hidden="true"</code>  が使用されることで実現できる。
```

日本語訳で改行があるので改行を取り除いてください。

2020-12-20 06:37 UTC, momdo commented on techniques/aria/ARIA24.html
> +                     <a href="https://www.w3.org/WAI/WCAG21/working-examples/aria-icon-font-img-role/#example4">表示テキストのあるセマンティック要素の一部として、複数のアイコンフォント</a>
```suggestion
                     <a href="https://www.w3.org/WAI/WCAG21/working-examples/aria-icon-font-img-role/#example4">表示テキストのあるセマンティック要素の一部としての複数のアイコンフォント</a>
```

2021-01-24 13:18 UTC, kurome9 commented
レビューありがとうございました。今後の作業で気をつけます。
ご指摘箇所は修正したつもりですので再度ご確認をお願いいたします。

2021-01-28 11:49 UTC, momdo commented
@kurome9 

作業ありがとうございます。問題なさそうなのでマージします。

2021-01-28 11:50 UTC, momdo approved these changes

2021-01-28 11:53 UTC, merged