達成方法集C37の翻訳
waic/wcag21 pull request #916
Opened 2020-12-23 10:28 UTC by k-octopus

翻訳の反映

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

#640

# コメント
遅くなりすみません。翻訳いたしましたのでお手数ですがレビューをお願いいたします。

fit image や fitting image の翻訳について迷いました。英語だとニュアンスはわかるのですが、どのように訳すべきか迷いまして、、
（もし同様のワードを既に翻訳してしているものなどありましたらお教えいただきたく思います。）

2020-12-30 03:38 UTC, momdo requested changes
@k-octopus 

遅くなりましたが、レビューしました。
年明けの比較的忙しくないだろうときに対応いただければと思います。

また、index.htmlのタイトルについてもあわせて差し替えていただければと思います。

よろしくお願いします。

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +      <title>C37: 画像を適応させるために、CSS の max-width と height を使用する</title>
fitを「収める」と取るのはどうでしょう？

```suggestion
      <title>C37: 画像を収めるために、CSS の max-width 及び height を使用する</title>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +      <h1>画像を適応させるために、CSS の max-width と height を使用する</h1>
titleと同じく

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/reflow">達成基準 1.4.10: リフロー</a> (十分な達成方法) </span>に関連する達成方法である。</p>
Advisoryですので十分なとはならないはずです。

```suggestion
            <p>これは<span><a href="https://waic.jp/docs/WCAG21/Understanding/reflow">達成基準 1.4.10: リフロー</a> (参考) </span>に関連する達成方法である。</p>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +            <p>この達成方法の目的は、320 CSS ピクセルに相当する幅において横スクロールバーを、又は 256 CSS ピクセルに相当する高さにおいて縦スクロールバーを導入することなく、画像を表示できるようにすることである。これは、画像の元のサイズを維持しつつ使用可能なスペースに適応させる、CSS の <code>max-width</code> 及び <code>height
1文目の文末の for content intended to scroll horizontally. がまるっと抜けてしまっているようです。

```suggestion
            <p>この達成方法の目的は、横方向にスクロールすることを目的としたコンテンツの場合、320 CSS ピクセルに相当する幅において横スクロールバーを、又は 256 CSS ピクセルに相当する高さにおいて縦スクロールバーを導入することなく、画像を表示できるようにすることである。これは、画像の元のサイズを維持しつつ使用可能なスペースに収める、CSS の <code>max-width</code> 及び <code>height</code> プロパティ手法を用いることによって行われる。</p>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +            <p>レスポンシブなレイアウトでは、カラムやレイアウトブロックを追加したり削除したりできる。また、レイアウトの各部分は、さまざまなポイントで幅を広くしたり小さくしたりできる。この手法により、スクロールが発生する1カラムのレイアウトを含めて、画像がレイアウト領域からはみ出すことがなくなる。</p>
すこし接続詞の訳を変えました。
```suggestion
            <p>レスポンシブなレイアウトでは、カラム又はレイアウトブロックを追加したり削除したりできる。さらに、レイアウトの各部分は、さまざまなポイントで幅を広くしたり小さくしたりできる。この手法により、スクロールが発生する1カラムのレイアウトを含めて、画像がレイアウト領域からはみ出すことがなくなる。</p>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +            <p>画像を適応させるための基本原則は次のとおりである:</p>
```suggestion
            <p>画像を収めるための基本原則は次のとおりである:</p>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +               <li> 画像の <code>height</code> プロパティを定義して、使用可能なスペースで画像を拡大又は縮小し、ズームレベルに対応させる。
[respond](https://ejje.weblio.jp/content/respond)を見た感じで。
```suggestion
               <li> 画像の <code>height</code> プロパティを定義して、使用可能なスペースで画像を拡大又は縮小し、ズームレベルに応答させる。  
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +            <p>全ての画像は、さまざまなビューポートサイズとズームレベルで綺麗な見ためになるようにするために、元のサイズが利用可能なスペースの最大サイズに確実に適応させるようにすることによる、デザインの精巧さを必要とする。
全体的にいじくってみました

```suggestion
            <p>全ての画像は、さまざまなビューポートサイズ及びズームレベルで綺麗な見た目を実現するために、元のサイズが利用可能なスペースの最大サイズに確実に収めるよるようにすることによる、デザインの精巧さを必要とする。
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +               <h3>例 1: HTML と CSS での画像の適応</h3>
[fitting](https://eow.alc.co.jp/search?q=fitting) を形容詞と取ってみるとか

```suggestion
               <h3>例 1: HTML 及び CSS での適切な画像</h3>
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +               <p>次の簡単な例では、適応した画像を設置するために HTML と CSS を使用する。ビューポートが調整されると、レイアウト領域は同じようにサイズが調整される。その後、画像はレイアウト領域のコンテナ内に収まるようにサイズが調整される。
```suggestion
               <p>次の簡単な例では、適切な画像を作成するために HTML 及び CSS を使用する。ビューポートが調整されると、レイアウト領域は同じようにサイズが調整される。その後、画像はレイアウト領域のコンテナ内に収まるようにサイズが調整される。
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +               <p>複数の方向にスクロールしなくても、ズームレベルを400％まで上げることができる。この例では、画像の <code>max-width</code> にパーセントサイズを使用し、<code>height</code> には自動（auto）サイズを使用することにより、元のサイズを維持している。
コード中に auto があるわけではないので削除しておきます。

```suggestion
               <p>複数の方向にスクロールしなくても、ズームレベルを400％まで上げることができる。この例では、画像の <code>max-width</code> にパーセントサイズを使用し、<code>height</code> には自動サイズを使用することにより、元のサイズを維持している。
```

2020-12-30 03:38 UTC, momdo commented on techniques/css/C37.html
> +                  <li>400％ ズームが可能なユーザエージェントでウェブページを表示し、ビューポートの寸法 (CSSピクセル単位) を幅 1280、高さ 1024 に設定する。
```suggestion
                  <li>400％ ズームが可能なユーザエージェントでウェブページを表示し、ビューポートの寸法 (CSS ピクセル単位) を幅 1280、高さ 1024 に設定する。
```

2021-02-18 08:39 UTC, k-octopus commented
@momdo さん
遅くなりましてすみません。
いただいたレビュー点を反映いたしました。
お手数おかけいたしますがご確認のほどよろしくお願いいたします。

2021-02-20 10:35 UTC, momdo approved these changes

2021-02-20 10:36 UTC, merged

2021-02-20 10:36 UTC, momdo commented
@k-octopus 
作業ありがとうございます…！1箇所追加でコミットさせてもらいました。