F99の翻訳
waic/wcag21 pull request #925
Opened 2021-01-10 04:28 UTC by 8845musign

Close: #653 

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

本文中に出てくる *STRキー* が一体何を指すのかわかりませんでした。
検索してもそれらしき情報が見つからず……。

2021-01-17 09:26 UTC, momdo commented
@8845musign 

まだ中身は見れてないのですが、

> 本文中に出てくる STRキー が一体何を指すのかわかりませんでした。

文脈からしてCtrlの typoじゃないですかねえ…。

余裕があれば、https://github.com/w3c/wcag/ でissueを立てて聞いて見るなりしてみてください。

2021-01-18 02:59 UTC, 8845musign commented
> 文脈からしてCtrlの typoじゃないですかねえ…。
>
> 余裕があれば、https://github.com/w3c/wcag/ でissueを立てて聞いて見るなりしてみてください。

確かに……。
聞いてみます。

2021-01-31 07:56 UTC, momdo requested changes
@8845musign 
お待たせしました。レビューしましたのでご確認ください。

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +            <p>コンテンツは単一文字キーのショートカットを実装しないか、又はそれらのショートカットを停止する、もしくはそれらを <kbd>Alt</kbd> もしくは <kbd>Ctrl</kbd> などの、追加修飾キーを用いるキーボードショートカットにマッピングする設定のどちらかを提供しなければならない。</p>
```suggestion
            <p>コンテンツは単一文字キーのショートカットを実装しないか、又はそれらのショートカットを停止する、もしくはそれらを <kbd>Alt</kbd> もしくは <kbd>Ctrl</kbd> などの、追加の修飾キーを用いるキーボードショートカットにマッピングする設定のどちらかを提供しなければならない。</p>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +               <p>単一キーのキーボードショートカットの使用は、特定のインターフェース要素がフォーカス持つ場合のみショートカットがアクティブであるときは失敗ではない。例えば、セレクト要素又はカスタムリストボックスがフォーカスを持つ場合、リストをナビゲートするための単一の文字キーの入力は便利な機能である。</p>
```suggestion
               <p>特定のインターフェース要素がフォーカス持つ場合にのみショートカットがアクティブであるとき、単一キーのキーボードショートカットの使用は失敗ではない。例えば、select 要素又はカスタムリストボックスがフォーカスを持つ場合、リストをナビゲートするための単一の文字キーの入力は便利な機能である。</p>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +            <p>この試験方法はキーボードショートカットが使用されているかどうかを制作者 (しばしばサイトの開発者) へ尋ねることを提案している。 その情報が信頼に足る場合、すべてのキーを押下するより手順は簡略化するはずである。</p>
```suggestion
            <p>この試験方法はキーボードショートカットが使用されているかどうかをコンテンツ制作者 (しばしばサイトの開発者) へ尋ねることを提案している。 その情報が信頼に足る場合、すべてのキーを押下するより手順は簡略化するはずである。</p>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +            <p>いくつかのブラウザは <kbd>Shift</kbd> を併用した単一キーショートカットを採用している。例えば、Firefox は <kbd>Shift</kbd> + <kbd>/</kbd> を押下した場合はページ検索を開く、及び <kbd>Shift</kbd> + <kbd>'</kbd> を押下した場合はページリンクを検索する。いずれの場合でも、ブラウザの
例示の中なので「及び」にしない方向で
removeは「削除」ではない（deleteではない）と思うので

```suggestion
            <p>いくつかのブラウザは <kbd>Shift</kbd> を併用した単一キーショートカットを採用している。例えば、Firefox は <kbd>Shift</kbd> + <kbd>/</kbd> を押下した場合はページ検索を開き、<kbd>Shift</kbd> + <kbd>'</kbd> を押下した場合はページリンクを検索する。いずれの場合でも、ブラウザの入力からフォーカスを外すためには、Esc を押下する又はページの空である部分をクリックする必要があるはずである。</p>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +            <p>アプリケーションは検索ポップアップを表示するために単一キーショートカットの <kbd>S</kbd> を使用する。 停止又はショートカットの変更を行う設定が存在しない。</p>
```suggestion
            <p>アプリケーションは検索ポップアップを表示するために単一キーショートカットの <kbd>S</kbd> を使用する。このショートカットを停止又は変更を行う設定が存在しない。</p>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +                  <li>制作者がショートカットキーとして指定したキーを押下する、又はこの情報が利用不可能な場合、全ての印刷文字 (例、数字、アルファベット、記号及び句読点キー) を押下する。<kbd>Ctrl</kbd>、<kbd>Alt</kbd>、<kbd>Esc</kbd>、矢印キー及び (存在する場合) <kbd>F1</kbd>-<kbd>F12</kbd> ファン
```suggestion
                  <li>コンテンツ制作者がショートカットキーとして指定したキーを押下する、又はこの情報が利用不可能な場合、全ての印刷文字 (すなわち、全ての数字、アルファベット、記号及び句読点キー) を押下する。<kbd>Ctrl</kbd>、<kbd>Alt</kbd>、<kbd>Esc</kbd>、矢印キー及び (存在する場合) <kbd>F1</kbd>-<kbd>F12</kbd> ファンクションキーなどの非印刷の修飾キー及びコントロールキーは押下しない。<kbd>スペース</kbd>、<kbd>Enter</kbd>、<kbd>Return</kbd>、<kbd>Tab</kbd> 及び <kbd>Delete</kbd> キーも免除される。</li>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +                  <li><kbd>Shift</kbd> キーを押下し続ける、かつ同様のキーを再度押下する。</li>
```suggestion
                  <li><kbd>Shift</kbd> キーを押下したまま、同じキーを再度押下する。</li>
```

2021-01-31 07:56 UTC, momdo commented on techniques/failures/F99.html
> +               <p>手順 #4 が偽である場合、この失敗例の条件は適用される、及びコンテンツは達成基準の失敗となる</p>
```suggestion
               <p>手順 #4 が偽である場合、この失敗例の条件は適用される、及びコンテンツは達成基準の失敗となる。</p>
```

2021-02-01 03:26 UTC, 8845musign commented
ありがとうございます！修正たします🙏

2021-02-04 17:43 UTC, 8845musign commented
取り急ぎ、「STRキー」について質問を投げました。
https://github.com/w3c/wcag/issues/1620

2021-02-04 17:57 UTC, 8845musign commented
ご指摘いただいた箇所は、全て確認いたしました。
修正提案全てマージさせていただきました。

ありがとうございました。

2021-02-05 10:54 UTC, merged

2021-02-07 06:43 UTC, 8845musign commented
STR キーですがドイツ語でいうCtrl キーのことのようです。
Ctrl キーで統一してしまって良いと思うので、別途プルリクを送ります。

2021-02-07 11:01 UTC, momdo commented
なるほど、ありがとうございます。

https://en.wikipedia.org/wiki/German_keyboard_layout

それにしてもStrgと記載しないあたりがなんとも中途半端ですね…。