F107の翻訳
waic/wcag21 pull request #932
Opened 2021-02-07 15:19 UTC by cure-tmk

closes: #661

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

2021-02-07 15:41 UTC, cure-tmk commented on techniques/failures/F107.html
> +            <p>達成基準 1.3.5 で <a href="https://www.w3.org/TR/WCAG21/#input-purposes">Input Purposes for User Interface Components</a> の（HTML 5.2 の <code>autocomplete</code> 属性のトークン値の固定リストに基づく）トークンの固定リス
`modality` という単語は「法性」「様相性」 ([参考](https://ejje.weblio.jp/content/modality)) などと直訳されますが，このコンテキストにおいては不適切 / カタカナの「モダリティ」がやや浸透しつつあることからそれに落ち着きました．

原文：
> ... such as expressing the input label in different modalities

翻訳：
> 入力ラベルを異なるモダリティで表現する等の...

2021-02-11 04:38 UTC, momdo requested changes
@cure-tmk 
レビューしましたのでご確認ください。

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://w3c.github.io/wcag/understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セク
```suggestion
         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://waic.jp/docs/WCAG21/Understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セクションは、その達成方法の範囲について説明しており、特定の技術に関する達成方法があるからといって、WCAG 2.1 を満たすコンテンツを作成する際に、常にその技術が使用可能であるわけではない。</p>
```
URLをWAICに向けます

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +            <p>達成基準 1.3.5 で <a href="https://www.w3.org/TR/WCAG21/#input-purposes">Input Purposes for User Interface Components</a> の（HTML 5.2 の <code>autocomplete</code> 属性のトークン値の固定リストに基づく）トークンの固定リス
```suggestion
            <p>達成基準 1.3.5 で (HTML 5.2 の <code>autocomplete</code> 属性のトークン値の固定リストに基づく) <a href="https://waic.jp/docs/WCAG21/#input-purposes">ユーザインタフェース コンポーネントの入力目的</a> のトークンの固定リストを使用する。これは、トークン値（メタデータ）をプログラム的に関連づけることで、入力ラベルを異なるモダリティで表現する等の機械的な処理を可能にするためである。</p>
```
WAICのリソースに置き換えつつ、2文に分割しました。

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +               <p>利用者の名前と誕生日を収集するためのオンラインフォームで、誤った autocomplete 属性が使用されている。この例では、一つ目のコントロールの正しい属性値は <code>name</code> であり、二つ目のコントロールでは <code>bday</code> の代わりに <code>birthday</code> が使用されています。</p>
```suggestion
               <p>利用者の名前と誕生日を収集するためのオンラインフォームで、誤った autocomplete 属性が使用されている。この例では、一つ目のコントロールの正しい属性値は <code>name</code> であり、二つ目のコントロールでは <code>bday</code> の代わりに <code>birthday</code> が使用されている。</p>
```

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +               <li>WCAG 2.1 - Input Purposes for User Interface Components:
```suggestion
               <li>WCAG 2.1 - ユーザインタフェース コンポーネントの入力目的:
```

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +                  <a href="https://www.w3.org/TR/WCAG21/#input-purposes">https://www.w3.org/TR/WCAG21/#input-purposes</a>
```suggestion
                  <a href="https://waic.jp/docs/WCAG21/#input-purposes">https://waic.jp/docs/WCAG21/#input-purposes</a>
```

2021-02-11 04:38 UTC, momdo commented on techniques/failures/F107.html
> +               <p>フォーム利用者に関する情報を集める入力フィールドそれぞれに対して：</p>
```suggestion
               <p>フォーム利用者に関する情報を集める入力フィールドそれぞれに対して:</p>
```
半角にします

2021-02-11 06:34 UTC, cure-tmk commented on techniques/failures/F107.html
> +         <p>これらの達成方法 (参考) の使用法及び、それらが WCAG 2.1 達成基準 (規定) とどのように関係するかに関する重要な情報については、<a href="https://w3c.github.io/wcag/understanding/understanding-techniques">WCAG 達成基準の達成方法を理解する</a>を参照のこと。適用 (対象) セク
おぉ... こちら気をつけます🙇‍♂️

2021-02-11 06:34 UTC, cure-tmk commented
@momdo レビューありがとうございます🙇‍♂️
指摘事項修正しました，再度ご確認よろしくお願いいたします！

2021-02-17 04:54 UTC, momdo approved these changes

2021-02-17 04:54 UTC, merged

2021-02-17 04:55 UTC, momdo commented
@cure-tmk 
作業ありがとうございました…！マージしました。