translate c39
waic/wcag21 pull request #934
Opened 2021-02-23 05:30 UTC by cure-tmk

# プルリクエスト作成時の確認事項

closes: #642 

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

2021-03-27 14:27 UTC, momdo requested changes
@cure-tmk 

大変お待たせしました。レビューしましたのでご確認ください。

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +            <p>この達成方法は 'prefers-reduced-motion' CSS メディアクエリを使用して、ユーザーが Web ページのアニメーションを非表示にできることを目的とする。</p>
MDNを読む限り、
https://developer.mozilla.org/ja/docs/Web/CSS/@media/prefers-reduced-motion

あくまで減らすのであって、なくすわけではないので、非表示は誤りではと。（タイトルでは防止としていますし）
https://ejje.weblio.jp/content/prevent を見ながら以下のようにしてみました。

user：利用者
web：ウェブ

```suggestion
            <p>この達成方法は 'prefers-reduced-motion' CSS メディアクエリを使用して、利用者にウェブページでアニメーションが表示されないようにすることを目的とする。</p>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +            <p>これの代表的な例として、背景が前景とは異なる速度で動くパララックススクロールが挙げられる。スクロールによるページの動きは必要不可欠である（かつユーザーのコントロール下にある）が、スクロールによって発生する追加の動きは前庭障害を引き起こす可能性がある。</p>
```suggestion
            <p>これの代表的な例としては、背景が前景とは異なる速度で動くパララックススクロールが挙げられる。スクロールによるページの動きは必要不可欠である（かつ利用者のコントロール下にある）が、スクロールによって発生する追加の動きは前庭障害を引き起こす可能性がある。</p>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +               <p>ユーザーはシステム内のインタフェースのモーションに関する意向を設定することができ、'prefers-reduced-motion' CSS メディアクエリはその選択を尊重する。モーションに CSS を適用することで、要求したユーザーに対しては無効化することができる。</p>
```suggestion
               <p>利用者はシステム内のインタフェースのモーションに関する意向を設定することができ、'prefers-reduced-motion' CSS メディアクエリはその選択を尊重する。モーションに CSS を適用することで、要求した利用者に対しては無効化することができる。</p>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +                  <a href="../../working-examples/css-reduced-motion-query/index.html">'prefers-reduced-motion' CSS メディアクエリの実装例</a>
リンクが切れてしまうので、WAIのリソースに向けておきます。

```suggestion
                  <a href="https://www.w3.org/WAI/WCAG21/working-examples/css-reduced-motion-query/index.html">'prefers-reduced-motion' CSS メディアクエリの実装例</a>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +               <p>ユーザーのインタラクションによって動くインタラクティブな要素それぞれについて:</p>
```suggestion
               <p>利用者のインタラクションによって動くインタラクティブな要素それぞれについて:</p>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +                  <li>システムの「視差効果を減らす」設定を有効化する;</li>
セミコロンはあまり日本語では出てこないと思いますので

```suggestion
                  <li>システムの「視差効果を減らす」設定を有効化する、</li>
```

2021-03-27 14:27 UTC, momdo commented on techniques/css/C39.html
> +                  <li>その動作が必要不可欠でないことを確認する;</li>
```suggestion
                  <li>その動作が必要不可欠でないことを確認する、</li>
```

2021-04-08 01:06 UTC, cure-tmk commented
@momdo レビューありがとうございます．
指摘いただいた箇所を修正が完了しましたので，再度ご確認の程よろしくお願いいたします🙇‍♂️

2021-04-08 11:14 UTC, momdo approved these changes

2021-04-08 11:14 UTC, merged

2021-04-08 11:15 UTC, momdo commented
@cure-tmk 修正作業ありがとうございました。
内容に問題ないことを確認したので、マージしました。