[WIP] 達成方法集 ARIA 22 の翻訳
waic/wcag21 pull request #935
Opened 2021-02-25 12:28 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-02-27 08:40 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-03-27 15:05 UTC, momdo requested changes
@caztcha 

大変お待たせしました。レビューしましたのでご確認ください。

2021-03-27 15:09 UTC, momdo commented
@caztcha 表紙（index.html）についてもあわせて更新ください。

2021-03-31 09:03 UTC, caztcha commented on techniques/aria/ARIA22.html
> +	&lt;div role="status"&gt;5 件の検索結果&lt;/div&gt;
```suggestion
	&lt;div role="status"&gt;5 results returned.&lt;/div&gt;
```

2021-03-31 09:05 UTC, caztcha commented on techniques/aria/ARIA22.html
> +	&lt;div role="status"&gt;5 件の検索結果&lt;/div&gt;
いただいた修正提案、「&gt」の後のセミコロンが落ちていたので、イキの形で改めて修正提案させていただきます。

2021-03-31 09:16 UTC, caztcha commented
@momdo レビューありがとうございました。一点、修正提案に対して、別コミットで対応しました。
9f96e50

また、表紙（index.html）についてもあわせて更新しました。
186fd6d

よろしければ、マージいただけますと幸いです。

2021-03-31 11:50 UTC, momdo approved these changes

2021-03-31 11:51 UTC, merged