[WIP] 達成方法集 ARIA 23 の翻訳
waic/wcag21 pull request #936
Opened 2021-02-27 12:34 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-02-27 13:17 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-03-29 02:26 UTC, momdo requested changes
@caztcha 
お待たせしました。レビューしましたのでご確認ください。

2021-03-29 02:26 UTC, momdo commented on techniques/aria/ARIA23.html
> +		&lt;h4 id="chatHeading"&gt;チャット履歴&lt;/h4&gt;
```suggestion
		&lt;h4 id="chatHeading"&gt;Chat History&lt;/h4&gt;
```

2021-03-29 02:26 UTC, momdo commented on techniques/aria/ARIA23.html
> +			&lt;li&gt;最新のチャットメッセージ&lt;/li&gt;
```suggestion
			&lt;li&gt;The latest chat message&lt;/li&gt;
```

2021-03-29 02:26 UTC, momdo commented on techniques/aria/ARIA23.html
> +		&lt;h4 id="logHeading"&gt;直近のアクティビティ&lt;/h4&gt;
```suggestion
		&lt;h4 id="logHeading"&gt;Recent activity&lt;/h4&gt;
```

2021-03-30 09:16 UTC, caztcha commented
@momdo レビューありがとうございました。いただいた修正提案を確認し、commit しました。
併せて、表紙 (index.html) のリンクラベルも、日本語に修正しました。
よろしければ、マージいただけますと幸いです。

2021-03-30 23:57 UTC, momdo approved these changes

2021-03-30 23:58 UTC, momdo commented
@caztcha 
ご対応ありがとうございました。確認しましたのでマージします。

2021-03-30 23:58 UTC, merged