[WIP] 達成方法集 F95 の翻訳
waic/wcag21 pull request #937
Opened 2021-02-27 21:41 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-02-27 22:31 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-03-30 03:02 UTC, momdo requested changes
@caztcha 
お待たせしました。ざっくりとレビューしましたのでご確認ください。

2021-03-30 03:02 UTC, momdo commented on techniques/failures/F95.html
> +               <li>データポイントのある図の上にホバーすると、ポップアップが開き、該当するデータポイントの詳細を、いくらかデータポイント自体からずれたところに表示する。ポインタをポップアップに向けて動かし、画面拡大した状態でも完全に読めるようにしようとすると、ポインタは別のデータポイントの上を移動し、利用者が見たかった特定のポップアップに取って代わる、別のポップアップの出現を引
```suggestion
               <li>データポイントのあるグラフの上にホバーすると、ポップアップが開き、該当するデータポイントの詳細を、いくらかデータポイント自体からずれたところに表示する。ポインタをポップアップに向けて動かし、画面拡大した状態でも完全に読めるようにしようとすると、ポインタは別のデータポイントの上を移動し、利用者が見たかった特定のポップアップに取って代わる、別のポップアップの出現を引き起こしてしまう。
```

2021-03-30 03:02 UTC, momdo commented on techniques/failures/F95.html
> +               <p>ポインタホバーによって表示される追加コンテンツの各領域について、以下を確認する。</p>
```suggestion
               <p>ポインタホバーによって表示される追加コンテンツの各領域について:</p>
```

2021-03-30 09:00 UTC, caztcha commented
@momdo レビューありがとうございました。いただいた修正提案を確認し、commit いたしました。また、表紙 (index.html) のリンクラベルも日本語に修正しました。
よろしければ、マージいただけますと幸いです。

2021-03-30 23:59 UTC, momdo approved these changes

2021-03-30 23:59 UTC, momdo commented
@caztcha 
ご対応ありがとうございました。確認したのでマージします。

2021-03-31 00:00 UTC, merged