[WIP] 達成方法集 F97 の翻訳
waic/wcag21 pull request #938
Opened 2021-02-27 22:50 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-02-27 23:26 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-03-31 01:35 UTC, momdo requested changes
@caztcha 
お待たせしました。レビューしましたのでご確認ください。

2021-03-31 01:35 UTC, momdo commented on techniques/failures/F97.html
> +            <p>この達成方法の目的は、コンテンツの表示を単一の向きに制限することが、コンテンツを複数の向きで表示することの妨げになることを記述することである。コンテンツが特定の向きに制限されて提示されている場合、利用者は、コンテンツ制作者が課した向きでコンテンツを表示するようにデバイスを向けなければならない。利用者の中には、デバイスを固定された向き (例えば、電動車椅子のアームの上
1文目
> コンテンツを複数の向きで表示することの妨げになることを記述することである。

「こと」が3回続くのは流石に厳しいので見直しいただきたく。。

2021-03-31 01:35 UTC, momdo commented on techniques/failures/F97.html
> +            <p>特定の向きが、コンテンツを表示するうえで<a href="https://waic.jp/docs/WCAG21/#dfn-essential">必要不可欠</a>と判断される場合は、この達成方法 (失敗例) は適用されない。
operationがどこかに行ってしまったので
```suggestion
            <p>特定の向きが、コンテンツの操作及び表示に<a href="https://waic.jp/docs/WCAG21/#dfn-essential">必要不可欠</a>と判断される場合は、この達成方法 (失敗例) は適用されない。
```

2021-03-31 01:35 UTC, momdo commented on techniques/failures/F97.html
> +               <li>あるニュースアプリは、常に縦向き (portrait) で表示される。利用者は、横向き (landscape) 及び縦向き (portrait) の表示方向をサポートしているデバイスでコンテンツを表示することができる。デバイスを横向き (landscape) にすると、コンテンツは利用者にとって横倒しされた形で表示される。
```suggestion
               <li>あるニュースアプリは、常に縦向き (portrait) でコンテンツを表示する。利用者は、横向き (landscape) 及び縦向き (portrait) の表示方向をサポートしているデバイスでコンテンツを表示することができる。デバイスを横向き (landscape) にすると、コンテンツは利用者にとって横倒しされた形で表示される。
```

2021-04-01 09:14 UTC, caztcha commented
@momdo レビューありがとうございました。
[コメント](https://github.com/waic/wcag21/pull/938#discussion_r604529922)のご指摘の修正、および index.html のリンクラベルの更新を、コミットしました。 b2f6686
お手数ですが、ご確認いただけますと幸いです。

2021-04-01 10:02 UTC, momdo reviewed
@caztcha 

修正ありがとうございます。ただ、原文の言いたいことが若干取れ切れていないのかな…ということで案を提示してみました。

この案で問題なさそうであれば、土屋さんのほうでコミットしてマージしてもらえればと…！

2021-04-01 10:03 UTC, momdo approved these changes

2021-04-01 11:06 UTC, caztcha commented on techniques/failures/F97.html
> +            <p>この達成方法の目的は、コンテンツの表示を単一の向きに制限することが、コンテンツの複数の向きでの表示をいかに妨げるかを記述することである。コンテンツが特定の向きに制限されて提示されている場合、利用者は、コンテンツ制作者が課した向きでコンテンツを表示するようにデバイスを向けなければならない。利用者の中には、デバイスを固定された向き (例えば、電動車椅子のアームの上など)
修正提案ありがとうございます。「how」がどこにかかるか、について私の方で誤解があったようです。もんどさんの案のほうが適切だと思いますので、コミットさせていただきます！

2021-04-01 11:07 UTC, merged