[WIP] 達成方法集 F98 の翻訳
waic/wcag21 pull request #939
Opened 2021-03-05 12:32 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-03-07 08:31 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-03-31 13:33 UTC, momdo requested changes
@caztcha 
お待たせしました。ざっくりとレビューしました。

2021-03-31 13:33 UTC, momdo commented on techniques/failures/F98.html
> +				</code></pre><p>特定の実装によっては、タッチジェスチャを反映したウィジェットに対して、コンテンツ制作者はマウスによるインタラクションを可能にすることができる。例えば、マウス利用者が、クリック可能な前へ／次へのコントロール又はスクロールバーだけでなく、カルーセルのドラッグ／スワイプもできるようにするなどである。
段落に改行が入ってしまっているので取り除いてください。。

2021-04-01 11:57 UTC, caztcha commented on techniques/failures/F98.html
> +               <h3>例 2: タッチスクリーンが検知されたときに、マウス及びキーボードの利用者のためのコントロールを、非表示／省略している。
「例 1」も、同様に句点をトリます。

2021-04-01 12:10 UTC, caztcha commented on techniques/failures/F98.html
> +/* Touch Events API のサポートに基づいて、タッチスクリーンの存在を検知する */
コミット dc47f36 にて、コメントの記述をすべて英語に戻しました。

2021-04-01 12:11 UTC, caztcha commented on techniques/failures/F98.html
> +                  <p>一般的に、これらのアプローチは、達成基準 2.1.1 キーボード <em>も併せて</em>満たさないことになるが、それはタッチスクリーンインターフェースも検知された状況でのみ、該当する。
そうですね。ちょっと意訳しすぎた感があるので、原文に忠実にいきたいと思います。コミット dc47f36 にて、修正しました。

2021-04-01 12:12 UTC, caztcha commented on techniques/failures/F98.html
> +				</code></pre><p>特定の実装によっては、タッチジェスチャを反映したウィジェットに対して、コンテンツ制作者はマウスによるインタラクションを可能にすることができる。例えば、マウス利用者が、クリック可能な前へ／次へのコントロール又はスクロールバーだけでなく、カルーセルのドラッグ／スワイプもできるようにするなどである。
ご指摘ありがとうございます。コミット dc47f36 にて、改行をトルツメしました。

2021-04-01 12:27 UTC, caztcha commented
@momdo レビューありがとうございました。いただいたご指摘を、dc47f36 にて修正対応しました。
お手数ですが、ご確認いただけますと幸いです。

2021-04-02 00:58 UTC, merged

2021-04-02 00:58 UTC, momdo commented
@caztcha 

作業ありがとうございました。マージしました。