[WIP] 達成方法集 F102 の翻訳
waic/wcag21 pull request #940
Opened 2021-03-11 12:47 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-04-01 10:37 UTC, momdo requested changes
@caztcha 

お待たせしました。レビューしましたのでご確認ください。

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +            <p>この文書は、ビューポート幅を 320 ピクセルに変更したときに生じる、より広いビューポート幅で利用可能だったコンテンツが表示されなくなる不具合について記述するものである。より広いビューポート幅で利用可能なコンテンツの中には、ビューポート幅が 320 ピクセルになると、単純に表示できるスペース (画面上の「土地」) が少なくなるため、同じような形で又は同じ位置で表示さ
最初の文は、whenの取る位置を修正しています。
最後の文は、for example以下のorを単なる読点とし、either ～,or ... をより明示してみました。

```suggestion
            <p>この文書は、ビューポート幅を 320 ピクセルに変更すると、より広いビューポート幅で利用可能だったコンテンツが表示されなくなるときに生じる失敗について説明するものである。より広いビューポート幅で利用可能なコンテンツの中には、ビューポート幅が 320 ピクセルになると、単純に表示できるスペース (画面上の「土地」) が少なくなるため、同じような形で又は同じ位置で表示されないものがある。しかし、このようなコンテンツは、320 ピクセルのビューポート幅にリフローされた後であっても、単一のカラムビューに再配置されることによって、又は、情報展開エリア、ダイアログ、他のビューへのリンクなど他の方法で情報を提供する何らかのインタラクションによってのいずれかで、利用可能であるべきである。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +            <p>以下の例は、より広いビューポート幅で見ることができるコンテンツが、320 ピクセルにリフローされた後も利用可能である、ということを満たさないことを示している。
ちょっと意訳気味ですが…

```suggestion
            <p>以下の例は、コンテンツをより広いビューポート幅で見ることができ、320 ピクセルにリフローされた後も利用可能にすることに失敗していることを示している:
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +               <li>テキスト入力の上にあるラベルが、リフロー後に隠されてプレースホルダーのテキストに置き換えられ、フィールドにフォーカスしたときにそのフィールド用のラベルを表示する技術が用いられていない。
語順を変更しました。

```suggestion
               <li>テキスト入力の上にあるラベルが、フィールドにフォーカスしたときにそのフィールド用のラベルを表示する技術が用いられずに、リフロー後に隠されてプレースホルダーのテキストに置き換えられる。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +               <li>リフロー後にコンテンツテキストのセクションが消えてしまい、展開ウィジェットを介して利用することもできない。
```suggestion
               <li>コンテンツテキストのセクションは、展開ウィジェットを介して利用できずに、リフロー後に消えてしまう。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +               <li>情報の入った画像がリフロー後に消えてしまい、リンク又は利用可能な同等の代替手段もない。
```suggestion
               <li>情報の入った画像が、リンク又は利用可能な同等の代替手段もなく、リフロー後に消えてしまう。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +               <li>グローバル検索フィールドがリフロー後に消えてしまい、検索機能を展開する、あるいは同等の検索ページにたどり着くためのアイコン又はメニューオプションもない。
```suggestion
               <li>グローバル検索フィールドが、検索機能を展開する、もしくは同等の検索ページにたどり着くためのアイコン又はメニューオプションもなしに、リフロー後に消えてしまう。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +                  <li>ブラウザのウィンドウを狭める、又はビューポート幅が320 ピクセルになるようにズームインすることで、ビューポート幅を320pxに設定する (ブラウザのズーム率が 100 %で、ビューポート幅が 1280 ピクセルの場合は、400 %にズームインすることによって設定できる)。
```suggestion
                  <li>ブラウザのウィンドウを狭める、又はビューポート幅が 320 ピクセルになるようにズームインすることで、ビューポート幅を 320 ピクセルに設定する (ブラウザのズーム率が 100 %で、ビューポート幅が 1280 ピクセルの場合は、400 %にズームインすることによって設定できる)。
```

2021-04-01 10:37 UTC, momdo commented on techniques/failures/F102.html
> +                  <li>ビューポート幅 320 ピクセルで提供されない各コンテンツ要素について、同じ又は同等のコンテンツにたどり着くための方法が、展開ウィジェット、ポップアップ、あるいは他のビューへのリンクを介して存在するかどうかを確認する。
```suggestion
                  <li>ビューポート幅 320 ピクセルで提供されない各コンテンツ要素について、同じ又は同等のコンテンツにたどり着くための方法が、展開ウィジェット、ポップアップ、又は他のビューへのリンクを介して存在するかどうかを確認する。
```

2021-04-02 06:54 UTC, caztcha commented on techniques/failures/F102.html
> +				<li><a href="../#introduction" title="Introduction to Techniques">イントロダクション</a></li>
コミット b2eabfa にて、余計なタブを削除しました。

2021-04-02 06:59 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案を一通り確認し、一点、別コミット b2eabfa で余計なタブが入っているのを削除しました。併せて、index.html を更新し、リンクラベルを日本語化しました。
よろしければ、マージいただけますと幸いです。

2021-04-03 10:21 UTC, momdo approved these changes

2021-04-03 10:21 UTC, merged

2021-04-03 10:22 UTC, momdo commented
@caztcha 
修正ありがとうございました。マージしました。