[WIP] 達成方法集 F101 の翻訳
waic/wcag21 pull request #941
Opened 2021-03-12 21:47 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-03-12 23:16 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをお願いいたします！

2021-04-02 01:22 UTC, momdo requested changes
@caztcha 
お待たせしました。レビューしましたのでご確認ください。

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +            <p>この失敗例の目的は、以下のような状況を解説することである。</p>
```suggestion
            <p>この失敗例の目的は、以下のような状況を解説することである:</p>
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +            <p>コンテンツ制作者は、<code>click</code> イベントを利用する代わりに、<code>mousedown</code>、<code>touchstart</code>、<code>pointerdown</code>といったダウンイベントを使用することができる。その結果、マウスボタンが押される (ただしまだ離されていない)、あるいは、指又はスタイラスがタ
```suggestion
            <p>コンテンツ制作者は、<code>click</code> イベントを利用する代わりに、<code>mousedown</code>、<code>touchstart</code>、<code>pointerdown</code>といったダウンイベントを使用することができる。その結果、マウスボタンが押される (ただしまだ離されていない)、もしくは、指又はスタイラスがタッチスクリーンに接触することで、即座に機能が実行されるようになる。
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +            <p>ダウンイベントを使用しつつ、潜在的な問題を軽減することで、達成基準を満たさないことを回避することは可能である。例えば、機能を容易に元に戻す又は中止する、あるいはアップイベント (マウスボタンが離されたとき、又はタッチスクリーンから指やスタイラスが離されたとき) によって結果を反転させる、という方法を提供することができる。
```suggestion
            <p>ダウンイベントを使用しつつ、潜在的な問題を軽減することで、達成基準の失敗を回避することは可能である。例えば、機能を容易に元に戻す又は中止する、もしくはアップイベント (マウスボタンが離されたとき、又はタッチスクリーンから指やスタイラスが離されたとき) によって結果を反転させる、という方法を提供することができる。
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +				また、ダウンイベントの使用が、機能にとって必要不可欠なものもあり (例えば、コントロールがピアノ鍵盤のような楽器の操作をシミュレートする、あるいはコントロールが、迅速かつ即時の反応が必要なゲームの画面制御として使用される、など)、その場合は、この達成基準を満たさないことにはならないことに注意されたい。
改行が入っていますので削除ください。

```suggestion
				また、ダウンイベントの使用が、機能にとって必要不可欠なものもあい (例えば、コントロールがピアノ鍵盤のような楽器の操作をシミュレートする、あるいはコントロールが、迅速かつ即時の反応が必要なゲームの画面制御として使用される、など)、その場合は、この達成基準の失敗にはならないことに注意されたい。
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +               <p>あるモーダルダイアログには、利用者が入力しなければならない長いフォームが含まれている。そのモーダルダイアログには、ダイアログを閉じ、かつ利用者がフォームに入力したすべての情報を失う、シンプルな「閉じる」コントロールが提供されている。しかしコンテンツ制作者は、単純に <code>click</code> イベント (ほとんどのユーザエージェントではアップイベント
need to ≠ must

```suggestion
               <p>あるモーダルダイアログには、利用者が入力する必要がある長いフォームが含まれている。そのモーダルダイアログには、ダイアログを閉じ、かつ利用者がフォームに入力したすべての情報を失う、シンプルな「閉じる」コントロールが提供されている。しかしコンテンツ制作者は、単純に <code>click</code> イベント (ほとんどのユーザエージェントではアップイベントによって引き起こされる) をリスニングする代わりに、ダウンイベントによってダイアログを閉じることにしてしまった。これにより、利用者が誤ってダイアログを閉じてしまい、それまでにフォームに入力したすべてのデータを失う可能性がある。
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +&lt;button id="close"&gt;閉じる&lt;/button&gt;
英語に戻します（以下略）

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +               <p>利用可能なすべてのコントロール (ボタン、リンク、複雑なウィジェット) に対して、ポインタによる入力 (マウス、タッチスクリーン、スタイラス) を備えたデバイスで、コンテンツを開く。
```suggestion
               <p>利用可能なすべてのコントロール (ボタン、リンク、複雑なウィジェット) に対して、ポインタによる入力 (マウス、タッチスクリーン、スタイラス) を備えたデバイスで、コンテンツを開く:
```

2021-04-02 01:22 UTC, momdo commented on techniques/failures/F101.html
> +                  <li>ダウンイベントで機能が実行された場合、アップイベントのトリガー (押したマウスボタンを離す、あるいはタッチスクリーンから指又はスタイラスを持ち上げる) によって結果が反転するかどうかを確認する。
```suggestion
                  <li>ダウンイベントで機能が実行された場合、アップイベントのトリガー (押したマウスボタンを離す、もしくはタッチスクリーンから指又はスタイラスを持ち上げる) によって結果が反転するかどうかを確認する。
```

2021-04-02 07:09 UTC, caztcha commented on techniques/failures/F101.html
> +&lt;button id="close"&gt;閉じる&lt;/button&gt;
コミット 741a470 にて、ひととおりコード例の記述を英語に戻しました。

2021-04-02 07:12 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案を一通り確認し、一点、別コミット 741a470 にてコード例の日本語訳を英語に戻しました。併せて、index.html を更新し、リンクラベルを日本語化しました。
よろしければ、マージいただけますと幸いです。

2021-04-03 10:23 UTC, momdo approved these changes

2021-04-03 10:23 UTC, merged

2021-04-03 10:24 UTC, momdo commented
@caztcha 
ありがとうございました。マージしました。
これで土屋さんからの一連のPRはすべてマージしたことになります。おつかれさまでした。