C40の翻訳
waic/wcag21 pull request #942
Opened 2021-03-19 02:32 UTC by cure-tmk

closes: #643 

# プルリクエスト作成時の確認事項

- [x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

2021-04-03 12:02 UTC, momdo requested changes
@cure-tmk 
お待たせしました。レビューしましたのでご確認ください。

2021-04-03 12:02 UTC, momdo commented on techniques/css/C40.html
> +               <h3>事例 1: 明暗のあるドット状のインジケータ</h3>
https://eow.alc.co.jp/search?q=dotted

```suggestion
               <h3>事例 1: 明暗のある点線のインジケータ</h3>
```

2021-04-03 12:02 UTC, momdo commented on techniques/css/C40.html
> +                  <li></li>
空のli要素がなぜか増えているので削除しておいてください…

2021-04-08 01:41 UTC, cure-tmk commented on techniques/css/C40.html
> +                  <li></li>
翻訳がまるまる一文漏れておりました... 失礼しました... 🙇‍♂️

2021-04-08 01:42 UTC, cure-tmk commented
@momdo こちら修正しました．再度確認よろしくお願いいたします🙇‍♂️

2021-04-08 11:22 UTC, momdo approved these changes

2021-04-08 11:23 UTC, merged

2021-04-08 11:24 UTC, momdo commented
@cure-tmk 
修正作業ありがとうございました。
内容について問題ないことを確認しましたので、マージしました。