達成方法 C36 の翻訳
waic/wcag21 pull request #944
Opened 2021-04-09 09:03 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-04-09 09:05 UTC, caztcha commented
@momdo 翻訳完了しました。お手数ですが、レビューをよろしくお願いします。

2021-04-11 10:09 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +            <p>英語では、コンテンツ制作者が CSS の <code>height</code> プロパティを設定しなければ、段落が確実に広がるようにすることができる。段落は、英語のように横読みされる言語やスクリプトの場合はテキストが縦に伸び、又、縦読みされる言語やスクリプトの場合はテキストが横に伸びるようにする必要がある。
こちらもいろいろと触ってみました。
```suggestion
            <p>英語では、コンテンツ制作者が CSS の <code>height</code> プロパティを設定しなければ、段落が確実に広がるようにすることができる。段落は、水平方向に読まれる英語のような言語もしくはスクリプトの場合はテキストを垂直方向に増やすことができる、又は、垂直方向に読まれる言語もしくはスクリプトの場合はテキストを水平方向に増やすことができる必要がある。
```

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +            <p>利用者がページを調整してテキストの間隔を広げると、テキストはコンテナのボックスの範囲内に収まる。
```suggestion
            <p>利用者がページを調整してテキストの間隔を広げると、テキストは包含ボックスの範囲内に収まる。
```

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +                  <li>ズームのレベルを100％に設定する。</li>
```suggestion
                  <li>ズームのレベルを 100％に設定する。</li>
```

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +                  <li>ツール又は別のメカニズム、例えば <a href="http://www.html5accessibility.com/tests/tsbookmarklet.html">Text Spacing Bookmarklet</a> 又はユーザースタイルのブラウザプラグインなどを用いて、テキスト間隔のメトリクス (行の高さ、および段落、文字、単語の間隔)
```suggestion
                  <li>ツール又は別のメカニズム、例えば <a href="http://www.html5accessibility.com/tests/tsbookmarklet.html">Text Spacing Bookmarklet</a> 又はユーザスタイルのブラウザプラグインなどを用いて、テキスト間隔のメトリクス (行の高さ、及び段落、文字、単語の間隔) を適用する。
```

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +                  <li>すべてのコンテンツと機能が利用可能であることを確認する。例えば、コンテナ内のテキストが切り捨てられていないか、他のコンテンツと重なっていないか、など。
```suggestion
                  <li>すべてのコンテンツと機能が利用可能であることを確認する。例えば、コンテナ内のテキストが切り取られていないか、他のコンテンツと重なっていないか、など。
```

2021-04-11 10:09 UTC, momdo commented on techniques/css/C36.html
> +                  <p>1 つのページに複数のレイアウトがある場合 (例: レスポンシブデザインなど)、テキストの間隔は各レイアウトでテストする必要がある。
```suggestion
                  <p>1 つのページに複数のレイアウトがある場合 (例: レスポンシブデザインなど)、テキストの間隔は各レイアウトでテストすべきである。
```

2021-04-12 02:03 UTC, caztcha commented
@momdo レビューありがとうございました。いただいた修正提案、ひととおり確認し、コミットしました。
よろしければ、マージいただけますと幸いです。

2021-04-12 07:04 UTC, momdo approved these changes

2021-04-12 07:07 UTC, merged

2021-04-12 07:07 UTC, momdo commented
@caztcha 
作業ありがとうございます。マージしました。
このマイルストーン（https://github.com/waic/wcag21/milestone/6 ）の多数のPull Request作成について、
この場を借りてお礼申し上げます。