達成方法ARIA7の翻訳
waic/wcag21 pull request #962
Opened 2021-05-25 13:56 UTC by makoto-ogata

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

@momdo 
「Applicability」の箇所が2.0と若干違ったので調べながら翻訳しました。
お手すきの際にご確認お願いいたします。

2021-05-26 05:20 UTC, momdo requested changes
@makoto-ogata 
作業ありがとうございます。2点コメントしたほか、以下についても確認ください。

次のファイルを削除しておきます。（.gitignoreを置かないとダメですね…）

- .vscode/settings.json
- techniques/.DS_Store

また、index.htmlにある、目次のARIA7へのリンクタイトルについても更新してください。

> 「Applicability」の箇所が2.0と若干違ったので調べながら翻訳しました。

こちらのほう、問題ないと思います。

よろしくお願いいたします。

2021-05-26 05:20 UTC, momdo commented on techniques/aria/ARIA7.html
> +               <code class="att">aria-labelledby</code> 属性を用いることで、制作者は、ページ上の可視テキスト要素を、フォーカス可能な要素 (フォームコントロール又はリンク) のラベルとして使用できる。たとえば、"read more..." のリンクは、リンクの目的を明確にするために、先行するセクションの見出しテキストと関連付けることができる
```suggestion
               <code class="att">aria-labelledby</code> 属性を用いることで、コンテンツ制作者は、ページ上の可視テキスト要素を、フォーカス可能な要素 (フォームコントロール又はリンク) のラベルとして使用できる。たとえば、"read more..." のリンクは、リンクの目的を明確にするために、先行するセクションの見出しテキストと関連付けることができるかもしれない (事例 1 を参照)。
```

元の翻訳の修正です。

2021-05-30 22:39 UTC, makoto-ogata commented
@momdo 
対応が遅くなり申し訳ありませんでした。
指摘されていた箇所について修正いたしましたので、ご確認お願いいたします。

2021-06-01 12:30 UTC, momdo approved these changes

2021-06-01 12:30 UTC, merged

2021-06-01 12:30 UTC, momdo commented
@makoto-ogata 

対応ありがとうございました。マージしました。