達成方法集 ARIA9 の翻訳
waic/wcag21 pull request #965
Opened 2021-05-27 07:54 UTC by MasahikoNegishi

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-05-27 07:57 UTC, MasahikoNegishi commented on techniques/aria/ARIA9.html
> +               <h3>例 1: 連結されたラベルをもつタイムアウト入力フィールド</h3>
`Example 1` が、2.0のページだと「事例 1」となっていたのですが、2.1の他のページだと「例 1」となっていたので、そちらに合わせました。
いくつかのページでは、「例」と訳されているものもあるようです。

2021-05-27 12:12 UTC, momdo requested changes
@MasahikoNegishi 

コメントしましたのでご確認ください。

2021-05-27 12:12 UTC, momdo commented on techniques/aria/ARIA9.html
> +            <p>
改行を削除します（他の箇所も同様）

2021-05-27 12:12 UTC, momdo commented on techniques/aria/ARIA9.html
> +                 実装例 <a href="https://www.w3.org/WAI/WCAG21/Techniques/working-examples/ARIA9/ex1.html">連結されたラベルをもつタイムアウト入力フィールド</a> は、Marco Zeheによってまとめられた Easy ARIA tip #2: <code class="att">aria-la
```suggestion
                 実装例 <a href="https://www.w3.org/WAI/WCAG21/working-examples/aria-labelledby-time-out-input-concatenated-label/">連結されたラベルをもつタイムアウト入力フィールド</a> は、Marco Zeheによってまとめられた Easy ARIA tip #2: <code class="att">aria-labelledby</code> and <code class="att">aria-describedby</code> から翻案した。
```

2021-05-27 12:12 UTC, momdo commented on techniques/aria/ARIA9.html
> +               <p class="working-example">実装例 <a href="../../working-examples/aria-labelledby-table-text-inputs/">テキスト入力をもつ単純なテーブルに対する aria-labelledby を使用する</a>は、Jim Thatcher による例に基づく。
```suggestion
               <p class="working-example">実装例 <a href="https://www.w3.org/WAI/WCAG21/Techniques/working-examples/aria-labelledby-table-text-inputs/">テキスト入力をもつ単純なテーブルに対する aria-labelledby を使用する</a>は、Jim Thatcher による例に基づく。
```

2021-05-27 12:12 UTC, momdo commented on techniques/aria/ARIA9.html
> +&lt;/table&gt;</pre><p class="working-example">実装例: <a href="../../working-examples/aria-labelledby-workshop-booking-timetable/">会議ワークショップ予約時間表</a>
```suggestion
&lt;/table&gt;</pre><p class="working-example">実装例: <a href="https://www.w3.org/WAI/WCAG21/Techniques/working-examples/aria-labelledby-workshop-booking-timetable/">会議ワークショップ予約時間表</a>
```

2021-05-28 13:15 UTC, MasahikoNegishi commented on techniques/aria/ARIA9.html
> +               <p class="working-example">実装例 <a href="../../working-examples/aria-labelledby-table-text-inputs/">テキスト入力をもつ単純なテーブルに対する aria-labelledby を使用する</a>は、Jim Thatcher による例に基づく。
@momdo 
上記提案のURLだと404になるようですが、下記のURLではなく、上記が正ということで合っていますでしょうか？
`https://www.w3.org/WAI/WCAG21/working-examples/aria-labelledby-table-text-inputs/`

2021-05-28 14:08 UTC, momdo commented on techniques/aria/ARIA9.html
> +               <p class="working-example">実装例 <a href="../../working-examples/aria-labelledby-table-text-inputs/">テキスト入力をもつ単純なテーブルに対する aria-labelledby を使用する</a>は、Jim Thatcher による例に基づく。
@MasahikoNegishi 

`https://www.w3.org/WAI/WCAG21/working-examples/aria-labelledby-table-text-inputs/` が正ですねすみません…（なおしました）

2021-05-29 07:44 UTC, MasahikoNegishi commented
@momdo ご指摘箇所の修正完了しましたmm

2021-05-29 08:35 UTC, momdo approved these changes
@MasahikoNegishi 
作業ありがとうございました。マージします。

2021-05-29 08:35 UTC, merged