達成方法集 H2 の翻訳
waic/wcag21 pull request #974
Opened 2021-05-31 08:34 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-05-31 08:36 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-06-02 12:43 UTC, momdo requested changes
@caztcha 

レビューしましたのでご確認ください。

2021-06-02 12:43 UTC, momdo commented on techniques/html/H2.html
> +            <p>制作者がリンク画像の代替テキストを省略した場合、テキストによる代替が視覚的なリンクと同じ目的を果たさないため、<a href="https://www.w3.org/TR/WCAG21/#text-equiv-all">達成基準 1.1.1</a> を満たせなくなる。
WCAG 2.1日本語訳に置き換えておきます

```suggestion
            <p>制作者がリンク画像の代替テキストを省略した場合、テキストによる代替が視覚的なリンクと同じ目的を果たさないため、<a href="https://waic.jp/docs/WCAG21/#non-text-content">達成基準 1.1.1</a> を満たせなくなる。
```

2021-06-02 12:43 UTC, momdo commented on techniques/html/H2.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。<a href="https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text">HTML 5.1§4.7.5.1. Requirements for provi
HTML 5.1をHTMLに置き換えておきます（WCAG 2.0達成方法集もそうすべきなのですが）
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。<a href="https://html.spec.whatwg.org/multipage/images.html#alt">HTML §4.8.4.4 Requirements for providing text to act as an alternative for images</a> を代わりに参照できる。
```

2021-06-02 12:43 UTC, momdo commented on techniques/html/H2.html
> +               <p>この達成方法を適用しているすべての <code class="el">a</code> 要素に対して:
しれっと直しておきます
```suggestion
               <p>この達成方法を適用している全ての <code class="el">a</code> 要素に対して:
```

2021-06-02 12:43 UTC, momdo commented on techniques/html/H2.html
> +                  <li><code class="el">a</code> 要素に含まれるすべての <code class="el">img</code> 要素の <code class="att">alt</code> 属性値が空に設定されていることを確認する。
```suggestion
                  <li><code class="el">a</code> 要素に含まれる全ての <code class="el">img</code> 要素の <code class="att">alt</code> 属性値が空に設定されていることを確認する。
```

2021-06-03 00:10 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案を確認の上、コミットいたしました。

2021-06-03 11:14 UTC, momdo approved these changes

2021-06-03 11:15 UTC, merged

2021-06-03 11:15 UTC, momdo commented
@caztcha ありがとうございます。マージしました。