達成方法集 H24 の翻訳
waic/wcag21 pull request #975
Opened 2021-06-01 01:56 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-06-01 01:58 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-06-02 12:53 UTC, momdo requested changes
@caztcha 
レビューしました

2021-06-02 12:53 UTC, momdo commented on techniques/html/H24.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記はそれぞれ、<a href="https://www.w3.org/TR/html51/semantics-embedded-content.html#embedded-content-image-maps">HTML 5.1§4.7.
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記はそれぞれ、<a href="https://html.spec.whatwg.org/multipage/image-maps.html#image-maps">HTML §4.8.15 Image maps</a> 及び <a href="https://html.spec.whatwg.org/multipage/images.html#alt">HTML §4.8.4.4 Requirements for providing text to act as an alternative for images</a> を代わりに参照できる。
```

2021-06-03 00:06 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案を確認の上、コミットいたしました。

2021-06-03 11:15 UTC, momdo approved these changes

2021-06-03 11:15 UTC, merged

2021-06-03 11:16 UTC, momdo commented
@caztcha ありがとうございます。マージしました。