達成方法集 H25 の翻訳
waic/wcag21 pull request #976
Opened 2021-06-01 03:41 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-06-01 03:44 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-06-02 12:55 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-06-02 12:55 UTC, momdo commented on techniques/html/H25.html
> +                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記は、<a href="https://www.w3.org/TR/html52/document-metadata.html#the-title-element">HTML 5.2§4.2.2. The title element</a
```suggestion
                  <p>HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記は、<a href="https://html.spec.whatwg.org/multipage/semantics.html#the-title-element">HTML §4.2.2 The title element</a> を代わりに参照できる。
```

2021-06-03 00:04 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認の上、コミットいたしました。

2021-06-03 11:16 UTC, momdo approved these changes

2021-06-03 11:17 UTC, merged

2021-06-03 11:17 UTC, momdo commented
@caztcha ありがとうございます。マージしました。