達成方法集 H33 の翻訳
waic/wcag21 pull request #980
Opened 2021-06-02 08:17 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-06-02 08:18 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-06-02 13:17 UTC, momdo requested changes
@caztcha 
レビューしましたのでご確認ください。

2021-06-02 13:17 UTC, momdo commented on techniques/html/H33.html
> +                  <p><a href="https://www.w3.org/TR/html52/dom.html#the-title-attribute">HTML 5.2§3.2.5.1. The title attribute</a> の Warning で述べられているように、多くのユーザエージェントではアクセシブルな形でこの属性を公開しないので、<code>titl
```suggestion
                  <p><a href="https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute">HTML §3.2.6.1 The title attribute</a> の Note で述べられているように、多くのユーザエージェントではアクセシブルな形でこの属性を公開しないので、<code>title</code> 属性に依存することを勧めていない。
```

2021-06-02 23:59 UTC, caztcha commented
@momdo レビューありがとうございます。修正提案、確認のうえコミットいたしました。

2021-06-03 11:20 UTC, momdo approved these changes

2021-06-03 11:20 UTC, merged