H37作業（Issue 864 ）
waic/wcag21 pull request #987
Opened 2021-06-09 07:36 UTC by kurome9

# プルリクエスト作成時の確認事項

- [ x] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ x] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [x ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-06-09 12:06 UTC, momdo requested changes
@kurome9 
作業ありがとうございます。レビューしましたのでご確認ください。

2021-06-09 12:06 UTC, momdo commented on techniques/html/H37.html
> +            <p>画像がコンテンツを理解するために重要な文字を含むとき、代替テキストにはそれらの文字を含めなくてはならない。これにより、代替テキストはページ上で画像と同じ役割を果たすことができる。 代替テキストは、画像自体の視覚的な特徴を説明する必要はないが、画像と同じ意味を伝えなければらないことに注意する。
スペースをツメておきます。
```suggestion
            <p>画像がコンテンツを理解するために重要な文字を含むとき、代替テキストにはそれらの文字を含めなくてはならない。これにより、代替テキストはページ上で画像と同じ役割を果たすことができる。代替テキストは、画像自体の視覚的な特徴を説明する必要はないが、画像と同じ意味を伝えなければらないことに注意する。
```

2021-06-09 12:06 UTC, momdo commented on techniques/html/H37.html
>           </section>
WCAG 2.0達成方法集にあるように、訳注を入れておきます。文章は以下に差し替えます。
```
HTML 4.01 は Superseded Recommendation としてマークされ、廃止された仕様である。上記はそれぞれ、<a href="https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element">HTML §4.8.3 The img element</a> 及び <a href="https://html.spec.whatwg.org/multipage/images.html#alt">HTML §4.8.4.4 Requirements for providing text to act as an alternative for images</a> を代わりに参照できる。
```

2021-07-07 08:24 UTC, momdo commented
@kurome9 こちらレビュー済みですがいかがでしょうか。。

2021-07-08 12:57 UTC, kurome9 commented
ありがとうございました。
レビューいただきました箇所を取り込み、漏れていた訳注を追加しました。

2021-07-17 06:21 UTC, momdo approved these changes

2021-07-17 06:21 UTC, merged

2021-07-17 06:22 UTC, momdo commented
@kurome9 
遅くなりましたが作業ありがとうございます。マージしました。