達成方法集 H97の翻訳
waic/wcag21 pull request #992
Opened 2021-06-15 05:00 UTC by caztcha

# プルリクエスト作成時の確認事項

- [ ] [翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)を確認し、ガイドラインに沿っているかチェックした
- [ ] [WCAGの用語集](https://waic.jp/docs/WCAG20/Overview.html#glossary)を確認し、用語が揃っているかチェックした
- [ ] [WG4の用語集](https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0)を確認し、用語が揃っているかチェックした

# コメント

2021-06-15 05:01 UTC, caztcha commented
@momdo 翻訳作業を実施しました。
2.0から、特に変更がありませんでした。
2.0の日本語訳で、訳注がありましたので、流用しました。

2021-06-15 14:51 UTC, momdo requested changes
@caztcha 
ありがとうございます。作業自体は問題ないのですが、1点コメントしましたので確認ください。。

2021-06-15 14:51 UTC, momdo commented on techniques/html/H97.html
> +            <p>この参考リソースは、あくまでも情報提供のみが目的であり、推薦などを意味するものではない。</p>
レビューコメントを直接書けないのでここに書きますが、
リンクURL https://www.w3.org/TR/html-markup/nav.html がリダイレクトに失敗するんですよね…

しれっと翻訳でHTML Standardに書き換えるか、訳注で記載するかどうしましょうか…？
（いずれにかかわらず、W3Cリポジトリーにコメントを投げるかPR作ってもらうのが正ですが…）

2021-06-16 06:10 UTC, caztcha commented on techniques/html/H97.html
> +            <p>この参考リソースは、あくまでも情報提供のみが目的であり、推薦などを意味するものではない。</p>
@momdo コメントありがとうございます！

正しいリンク先は、以下ですかね。
https://html.spec.whatwg.org/multipage/sections.html#the-nav-element

訳注で記載するのがよいのかも...
W3Cへのコメントは、私のほうから投げておきましょうか。

2021-06-16 10:05 UTC, momdo commented on techniques/html/H97.html
> +            <p>この参考リソースは、あくまでも情報提供のみが目的であり、推薦などを意味するものではない。</p>
@caztcha コメントありがとうございます。

> 正しいリンク先は、以下ですかね。
https://html.spec.whatwg.org/multipage/sections.html#the-nav-element

よいと思います…！

> 訳注で記載するのがよいのかも...
W3Cへのコメントは、私のほうから投げておきましょうか。

お手数ですがその方向で進めてもらうと助かります…！

2021-06-17 06:46 UTC, caztcha commented
@momdo b3d525d にて、訳注を追加しました。
併せて、W3C に issue としてリンク切れの指摘を出しておきました。

2021-06-17 07:21 UTC, momdo approved these changes

2021-06-17 07:21 UTC, merged

2021-06-17 07:22 UTC, momdo commented
@caztcha 諸々ありがとうございます！